assurance-maladie-digital/design-system

- packages/vue-dot/playground/examples/RulesEx.vue
- packages/vue-dot/src/helpers/ruleMessage.ts
- packages/vue-dot/src/rules/email.ts
- packages/vue-dot/src/rules/isDateValid.ts
- packages/vue-dot/src/rules/maxLength.ts
- packages/vue-dot/src/rules/minLength.ts
- packages/vue-dot/src/rules/notAfterToday.ts
- packages/vue-dot/src/rules/notBeforeToday.ts
- packages/vue-dot/src/rules/required.ts
- packages/vue-dot/src/rules/types.d.ts
Fix rule require function for error messages
> ✨ vue-dot: Add ruleMessage function

- packages/vue-dot/playground/examples/FileUploadEx.vue
- packages/vue-dot/playground/examples/PaginatedTableEx.vue
- packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
- packages/vue-dot/src/patterns/FileList/FileList.vue
- packages/vue-dot/src/patterns/FileList/types.d.ts
- packages/vue-dot/src/patterns/FileUpload/FileUpload.vue
- packages/vue-dot/src/patterns/FileUpload/errorCodes.ts
- packages/vue-dot/src/patterns/FileUpload/types.d.ts
- packages/vue-dot/src/patterns/LangBtn/LangBtn.vue
- packages/vue-dot/src/patterns/LangBtn/types.d.ts
- packages/vue-dot/src/patterns/PaginatedTable/PaginatedTable.vue
- packages/vue-dot/src/patterns/PaginatedTable/types.d.ts
- packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
- packages/vue-dot/src/patterns/UploadWorkflow/types.d.ts
- packages/vue-dot/src/types.d.ts
- packages/vue-dot/types/index.d.ts
Extract types definition into separate file in folder component.
> ♻️ vue-dot: Refactor typings

- packages/vue-dot/playground/Playground.vue
- packages/vue-dot/src/patterns/PageCard/PageCard.vue
- packages/vue-dot/src/patterns/PageCard/tests/__snapshots__/PageCard.spec.ts.snap
- packages/vue-dot/src/tokens/index.scss
- packages/vue-dot/src/tokens/index.ts
- packages/vue-dot/tests/integration/__snapshots__/tokens.spec.ts.snap
Update PageCard width and padding to match spec
> ♻️ vue-dot: Update PageCard settings

- packages/vue-dot/src/elements/CustomIcon/CustomIcon.vue
- packages/vue-dot/src/elements/CustomIcon/tests/CustomIcon.spec.ts
- packages/vue-dot/src/global.d.ts
- packages/vue-dot/src/index.ts
- packages/vue-dot/types/index.d.ts
Put all options in $vd instead of theme only since we'll add more options soon
> ♻️ vue-dot: Put all options in $vd instead of theme only

- packages/vue-dot/playground/examples/FormBuilderEx.vue
- packages/vue-dot/src/functions/setFormErrors/index.ts
- packages/vue-dot/src/functions/setFormErrors/tests/__snapshots__/setFormErrors.spec.ts.snap
- packages/vue-dot/src/functions/setFormErrors/tests/data/formErrors.ts
- packages/vue-dot/src/functions/setFormErrors/tests/setFormErrors.spec.ts
- packages/vue-dot/src/functions/setFormErrors/types.d.ts
- packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
- packages/vue-dot/src/patterns/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/vue-dot/src/patterns/FormBuilder/tests/data/questionForm.ts
- packages/vue-dot/src/patterns/FormField/fields/PeriodField.vue
- packages/vue-dot/src/patterns/FormField/types.d.ts
QUE 80 parsing retour d'erreurs
add function setFormErrors
add tests
update DatePicker component to accept common 'errorMessages' from option and not option.textField
> QUE 80 parsing retour d'erreurs

- packages/vue-cli-plugin-vue-dash/README.md
- packages/vue-cli-plugin-vue-dash/generator/functions/fixPackageIndentation.js
- packages/vue-cli-plugin-vue-dash/generator/index.js
- packages/vue-cli-plugin-vue-dash/index.js
- packages/vue-cli-plugin-vue-dash/prompts.js
- packages/vue-cli-plugin-vue-dash/shouldRenderTemplate.js
Do not copy template when invoking (manually installing the plugin) except if `--render-template` option is provided.
> ♻️ vue-dash: Do not copy template when invoking

- packages/vue-cli-plugin-vue-dash/generator/getResourcesToDelete.js
- packages/vue-cli-plugin-vue-dash/generator/index.js
Add cypress option (disabled for now, we'll add a prompt when the feature will be stable)
> ✨ vue-dash: Add cypress option

- packages/vue-dot/playground/Playground.vue
- packages/vue-dot/playground/examples/SubHeaderEx.vue
- packages/vue-dot/playground/examples/index.ts
- packages/vue-dot/playground/theme/theme.scss
- packages/vue-dot/src/patterns/SubHeader/SubHeader.vue
- packages/vue-dot/src/patterns/SubHeader/config.ts
- packages/vue-dot/src/patterns/SubHeader/index.ts
- packages/vue-dot/src/patterns/SubHeader/locales.ts
- packages/vue-dot/src/patterns/SubHeader/tests/SubHeader.spec.ts
- packages/vue-dot/src/patterns/SubHeader/tests/__snapshots__/SubHeader.spec.ts.snap
- packages/vue-dot/src/patterns/SubHeader/types.d.ts
- packages/vue-dot/src/patterns/index.ts
- packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
- packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
- packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Ajout du composant `SubHeader`
> ✨ vue-dot: Add SubHeader

- packages/vue-dot/playground/theme/theme.scss
> 🐛 vue-dot : fix slider style for the thumb and the ticks

- packages/vue-dot/src/patterns/FormField/mixins/choiceField.ts
- packages/vue-dot/src/patterns/FormField/mixins/tests/choiceField.spec.ts
Defect/que 91 choix bouton pas reactif
Reset data 'choiceValue' when the prop 'field.value' become null.
> 🐛vue-dot : ChoiceField mixin

- packages/vue-dot/playground/Playground.vue
- packages/vue-dot/playground/examples/DataListItemEx.vue
- packages/vue-dot/playground/examples/index.ts
- packages/vue-dot/src/elements/DataListItem/DataListItem.vue
- packages/vue-dot/src/elements/DataListItem/config.ts
- packages/vue-dot/src/elements/DataListItem/index.ts
- packages/vue-dot/src/elements/DataListItem/locales.ts
- packages/vue-dot/src/elements/DataListItem/tests/DataListItem.spec.ts
- packages/vue-dot/src/elements/DataListItem/tests/__snapshots__/DataListItem.spec.ts.snap
- packages/vue-dot/src/elements/index.ts
- packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
- packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
- packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Ajout du composant `DataListItem` qui servira à la `DataList` :
> ✨ vue-dot: Add DataListItem

- packages/vue-dot/src/elements/CopyBtn/CopyBtn.vue
- packages/vue-dot/src/elements/CopyBtn/config.ts
- packages/vue-dot/src/elements/CopyBtn/tests/__snapshots__/CopyBtn.spec.ts.snap
Ajout de la possibilité de passer une fonction comme paramètre pour récupérer le contenu et corrections
> ♻️ vue-dot: Add prop function to get text in CopyBtn

- packages/vue-cli-plugin-vue-dash/generator/getResourcesToDelete.js
- packages/vue-cli-plugin-vue-dash/generator/template/src/router/types.d.ts
correction de la config router
> 🐛 vue-dash: Fix router in template

- package.json
- yarn.lock
Malheureusement le paquet `monorepo-run` ne semble plus maintenu.
> ➖ Remove monorepo-run

- packages/vue-dot/src/rules/exactLength/index.ts
- packages/vue-dot/src/rules/exactLength/locales.ts
- packages/vue-dot/src/rules/exactLength/tests/exactLength.spec.ts
> ✨ vue-dot: Add rule exact length

- package.json
- yarn.lock
- Functionality Dialog Box adding ( slot, dynamic size, draggable)
- ListButtonAction: 
- Test coverage: not complet
> DialogBox: Component

- packages/vue-dot/playground/Playground.vue
- packages/vue-dot/playground/examples/FooterEx.vue
- packages/vue-dot/playground/examples/index.ts
- packages/vue-dot/src/patterns/FooterWrapper/FooterBtn/FooterBtn.vue
- packages/vue-dot/src/patterns/FooterWrapper/FooterBtn/index.ts
- packages/vue-dot/src/patterns/FooterWrapper/FooterBtn/tests/FooterBtn.spec.ts
- packages/vue-dot/src/patterns/FooterWrapper/FooterBtn/tests/__snapshots__/FooterBtn.spec.ts.snap
- packages/vue-dot/src/patterns/FooterWrapper/FooterWrapper.vue
- packages/vue-dot/src/patterns/FooterWrapper/index.ts
- packages/vue-dot/src/patterns/FooterWrapper/tests/FooterBtn.spec.ts
- packages/vue-dot/src/patterns/FooterWrapper/tests/__snapshots__/FooterBtn.spec.ts.snap
- packages/vue-dot/src/patterns/index.ts
- packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
- packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
- packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
> ✨ vue-dot: Add FooterWrapper & FooterBtn

- packages/docs/src/.vuepress/config.js
- packages/docs/src/elements/page-card/README.md
- packages/docs/src/elements/page-card/examples/page-card-playground.vue
- packages/docs/src/elements/page-card/examples/page-card-transparent.vue
- packages/docs/src/elements/page-card/examples/page-card-width.vue
- packages/docs/src/elements/page-card/examples/page-card.vue
Add the PageCard documentation
> 📝 docs: Add PageCard

- packages/docs/src/elements/dialog-box/README.md
- packages/docs/src/elements/dialog-box/examples/dialog-box-btn-text.vue
Update with new example for new props cancel-btn-text and confirm-btn-text
> 📝 docs: Update DialogBox 

- packages/docs/src/directives/debounce/examples/debounce-arg.vue
- packages/docs/src/directives/debounce/examples/debounce-native.vue
- packages/docs/src/directives/debounce/examples/debounce.vue
- packages/docs/src/elements/copy-btn/examples/copy-btn-no-tooltip.vue
- packages/docs/src/elements/copy-btn/examples/copy-btn-slots.vue
- packages/docs/src/elements/copy-btn/examples/copy-btn-vuetify-options.vue
- packages/docs/src/elements/copy-btn/examples/copy-btn.vue
- packages/docs/src/elements/data-list/examples/data-list-action.vue
- packages/docs/src/elements/data-list/examples/data-list-chip.vue
- packages/docs/src/elements/data-list/examples/data-list-icons.vue
- packages/docs/src/elements/data-list/examples/data-list-options.vue
- packages/docs/src/elements/data-list/examples/data-list-playground.vue
- packages/docs/src/elements/data-list/examples/data-list-slot.vue
- packages/docs/src/elements/data-list/examples/data-list.vue
change existing examples form js to ts
> ♻️ docs: Convert examples to TypeScript

- packages/docs/src/.vuepress/config.js
- packages/docs/src/patterns/footer-wrapper/README.md
- packages/docs/src/patterns/footer-wrapper/examples/footer-wrapper-inert.vue
- packages/docs/src/patterns/footer-wrapper/examples/footer-wrapper-slot.vue
- packages/docs/src/patterns/footer-wrapper/examples/footer-wrapper.vue
Add the FooterWrapper documentation
> 📝 docs: Add FooterWrapper

- packages/vue-dot/tests/index.ts
- packages/vue-dot/tests/utils/addVApp.ts
> ♻️ vue-dot: Add addVApp util in unit tests

- packages/vue-dot/src/patterns/SubHeader/SubHeader.vue
I don"t know why i changed this key and didn't saw the change 😄
> 🐛 vue-dot: Fix title used instead of listTitle in SubHeader

- packages/vue-dot/src/elements/DataList/DataListItem/DataListItem.vue
- packages/vue-dot/src/elements/DataList/DataListItem/tests/__snapshots__/DataListItem.spec.ts.snap
- packages/vue-dot/src/elements/DataList/tests/__snapshots__/DataList.spec.ts.snap
Il faudra rajouter un warning dans la doc sur la sécurité
> ♻️ vue-dot: Use v-html in DataListItem

- packages/vue-dot/src/helpers/deepRemoveKeys/index.ts
- packages/vue-dot/src/helpers/deepRemoveKeys/tests/deepRemoveKeys.spec.ts
Move: 
-  deepRemoveKeys from formBuilder to vue-dot package helpers
> ✨ vue-dot: Add deepRemoveKeys helper

- packages/vue-dot/src/tokens/index.scss
- packages/vue-dot/src/tokens/index.ts
- packages/vue-dot/tests/integration/__snapshots__/tokens.spec.ts.snap
Update tokens with new 'input-width: 328px'
> ✨ vue-dot: Add input-width token

- packages/vue-dot/src/patterns/UploadWorkflow/FileList/FileList.vue
- packages/vue-dot/src/patterns/UploadWorkflow/FileList/config.ts
- packages/vue-dot/src/patterns/UploadWorkflow/FileList/tests/__snapshots__/FileList.spec.ts.snap
- packages/vue-dot/src/patterns/UploadWorkflow/FileList/types.d.ts
- packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
- packages/vue-dot/src/patterns/UploadWorkflow/mixins/tests/__snapshots__/updateFileModel.spec.ts.snap
- packages/vue-dot/src/patterns/UploadWorkflow/mixins/tests/updateFileModel.spec.ts
- packages/vue-dot/src/patterns/UploadWorkflow/types.d.ts
> ✨ vue-dot: Add upload btn to FileList and UploadWorkflow

- packages/vue-dot/src/functions/copyToClipboard/tests/copyToClipboard.spec.ts
- packages/vue-dot/src/helpers/deepCopy/tests/deepCopy.spec.ts
- packages/vue-dot/src/helpers/localStorageUtility/tests/localStorageUtility.spec.ts
- packages/vue-dot/src/mixins/getThemeIcon/tests/getThemeIcon.spec.ts
- packages/vue-dot/src/mixins/warningRules/tests/warningRules.spec.ts
- packages/vue-dot/src/patterns/DatePicker/tests/maskValue.spec.ts
Voir https://jestjs.io/docs/en/expect#tobeundefined
> ✅ vue-dot: Use toBeUndefined() instead of toBe(undefined)

- packages/vue-dot/playground/examples/FileUploadEx.vue
- packages/vue-dot/playground/examples/UploadWorkflowEx.vue
- packages/vue-dot/src/helpers/convertToUnit/index.ts
- packages/vue-dot/src/helpers/convertToUnit/tests/convertToUnit.spec.ts
- packages/vue-dot/src/mixins/widthable/index.ts
- packages/vue-dot/src/mixins/widthable/tests/__snapshots__/widthable.spec.ts.snap
- packages/vue-dot/src/mixins/widthable/tests/widthable.spec.ts
- packages/vue-dot/src/patterns/FileUpload/FileUpload.vue
- packages/vue-dot/src/patterns/FileUpload/tests/__snapshots__/FileUpload.spec.ts.snap
- packages/vue-dot/src/patterns/SubHeader/SubHeader.vue
- packages/vue-dot/src/patterns/SubHeader/tests/__snapshots__/SubHeader.spec.ts.snap
- packages/vue-dot/src/patterns/UploadWorkflow/FileList/FileList.vue
- packages/vue-dot/src/patterns/UploadWorkflow/FileList/tests/__snapshots__/FileList.spec.ts.snap
- packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
- packages/vue-dot/src/patterns/UploadWorkflow/tests/__snapshots__/UploadWorkflow.spec.ts.snap
Inspiré de https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/mixins/measurable/index.ts
> ✨ vue-dot: Add widthable mixin and convertToUnit helper

- packages/form-builder/src/components/FormBuilder/FormBuilder.vue
- packages/form-builder/src/components/FormBuilder/FormSection/FormSection.vue
- packages/form-builder/src/components/FormBuilder/FormSection/types.d.ts
- packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/form-builder/src/components/FormBuilder/tests/data/questionForm.ts
Ajout d'une description en plus du titre sur les sections
Ajout d'une propriété sur les sections en plus du titre
> ✨ form-builder: Add section description

- packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/form-builder/src/components/FormBuilder/tests/data/questionForm.ts
- packages/form-builder/src/components/FormField/FormField.vue
type other than select can accept sub types with => fieldOptions.type
> 🐛 form-builder: Handle subtypes that are not in type select

- packages/design-tokens/index.ts
- packages/design-tokens/scripts/build.ts
- packages/design-tokens/src/index.ts
- packages/design-tokens/src/tokens.ts
- Le type `Tokens` était trop restrictif, on a besoin de l'utiliser uniquement dans le script de build
- Il manquait un fichier root `index.ts` (ou un fichier de types mais il serait quasi identique à la source)
> 🐛 design-tokens: Fix types and missing index file

- packages/form-builder/playground/Playground.vue
- packages/form-builder/playground/examples/FormFieldListEx.vue
- packages/form-builder/playground/examples/index.ts
- packages/form-builder/src/components/FormBuilder/FormBuilder.vue
- packages/form-builder/src/components/FormBuilder/FormSection/index.ts
- packages/form-builder/src/components/FormBuilder/mixins/formBuilderCore.ts
- packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/form-builder/src/components/FormBuilder/types.d.ts
- packages/form-builder/src/components/FormField/fields/ChoiceField.vue
- packages/form-builder/src/components/FormFieldList/FormFieldList.vue
- packages/form-builder/src/components/FormFieldList/index.ts
- packages/form-builder/src/components/FormFieldList/tests/FormBuilder.spec.ts
- packages/form-builder/src/components/FormFieldList/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/form-builder/src/components/FormFieldList/types.d.ts
- packages/form-builder/src/components/index.ts
- packages/form-builder/tests/integration/__snapshots__/plugin.spec.ts.snap
- packages/form-builder/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Refonte de `FormSection` en `FormFieldList` suite aux discussions avec l'équipe questionnaire
> ♻️ form-builder: Refactor FormSection into FormFieldList

- packages/form-builder/package.json
- packages/vue-dot/package.json
Mise à jour des peer dependencies et suppression de `vue-router` de celles-ci car il n'est pas utilisé directement dans Vue Dot
> ♻️ Update peer dependencies

- packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
Mise à jour des dépendances de Vue Dash
- x ] Mes modifications ne génèrent aucun nouveau warning
> ⬆️ vue-dash: Upgrade dependencies

- CHANGELOG.md
Mise à jour du CHANGELOG pour la prochaine version et rattrapage des versions jusqu'à la `v2.0.0-alpha.49`
Il manque le guide migration de la `v2.0.0-alpha.51` qui sera fait plus tard
Une question : est-ce la prochaine version est la `v2.0.0-beta.1` ou la `v2.0.0-beta.0` ?
On a commencé avec la version `v2.0.0-alpha.0`, mais c'est peut-être moins logique de commencer à 0 ?
> 📝 Update CHANGELOG

- .github/PULL_REQUEST_TEMPLATE.md
Mise à jour du template pour les Pull Requests
> 📝 Update PULL_REQUEST_TEMPLATE

- packages/vue-cli-plugin-vue-dash/generator/template/src/components/global/ErrorPage/ErrorPage.vue
- packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppHeader.vue
- packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/HeaderMenu.vue
- packages/vue-cli-plugin-vue-dash/generator/template/src/views/About.vue
- packages/vue-cli-plugin-vue-dash/generator/template/src/views/Home.vue
Suppression de styles qui ne sont plus nécessaires car inclus comme classes d'aide dans Vuetify
(également ajout de `width="155px"` sur le logo pour fixer sa largeur, même si le CSS ne charge pas et petites corrections de qualité de code)
> ♻️ vue-dash: Remove unnecessary styles in template

- packages/docs/src/.vuepress/components/DocMarkup.vue
- packages/form-builder/src/components/FormField/fields/ChoiceField.vue
Correction de l'import asynchrone du composant `Prism`, la syntaxe a évolué à priori https://vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions
> 🐛 docs: Fix prism component import

- CHANGELOG.md
- CONTRIBUTING.md
- packages/cli-helpers/src/logger.ts
- packages/cli-helpers/src/renderHeader.ts
- packages/vue-dot/playground/store/types.d.ts
- packages/vue-dot/src/functions/debounce/index.ts
- packages/vue-dot/src/helpers/localStorageUtility/tests/localStorageUtility.spec.ts
Suppression des anciens commentaires TSLint (plus utilisé sur le Design System)
> 🔥 Remove old TSLint comments

- .travis.yml
- CHANGELOG.md
Mise à jour de la version de yarn dans Travis (la 1.22.0 échoue régulièrement à être téléchargée, on verra si ça corrige ça aussi)
> 👷 Update yarn version in Travis config

- CHANGELOG.md
- packages/vue-dot/vue.config.js
Augmentation de la limite du build de 435 000 à 450 000
> 🔨 vue-dot: upgrade build limite size

- CHANGELOG.md
- packages/vue-dot/src/patterns/LangBtn/LangBtn.vue
- packages/vue-dot/src/patterns/LangBtn/locales.ts
- packages/vue-dot/src/patterns/LangBtn/tests/__snapshots__/LangBtn.spec.ts.snap
- packages/vue-dot/src/patterns/LangBtn/types.d.ts
> ♻️ vue-dot: Refactor LangBtn

- packages/docs/src/.vuepress/config.js
- packages/docs/src/composants/form-builder/README.md
- packages/docs/src/composants/form-builder/examples/form-builder-events.vue
- packages/docs/src/composants/form-builder/examples/form-builder.vue
- packages/docs/src/composants/form-field-list/README.md
- packages/docs/src/composants/form-field-list/examples/form-field-list-events.vue
- packages/docs/src/composants/form-field-list/examples/form-field-list-playground.vue
- packages/docs/src/composants/form-field-list/examples/form-field-list-props.vue
- packages/docs/src/composants/form-field-list/examples/form-field-list.vue
- packages/docs/src/composants/sub-header/README.md
- packages/docs/src/composants/upload-workflow/examples/upload-workflow-optional.vue
Ajout de la documentation du composant `FormFieldList`
> 📝 docs: Add FormFieldList

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppHeader.vue
- packages/vue-cli-plugin-vue-dash/generator/template/src/translations/fr/components/layout/appHeader.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/translations/fr/views/about.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/translations/fr/views/home.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/views/About.vue
- packages/vue-cli-plugin-vue-dash/generator/template/src/views/Home.vue
Les routes ne changent pas en fonction de la langue, il n'est pas nécessaire de mettre les routes dans les traductions
- Refactoring
> ♻️ vue-dash: Remove route from translations

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
Mise à jour de Cypress de la `v3` à la `v5` suite à la [`v4.5.9` de Vue CLI](https://github.com/vuejs/vue-cli/releases/tag/v4.5.9).
- Maintenance
> ⬆️ vue-dash: Update cypress to v5

- CHANGELOG.md
Correction du fichier changelog
> 📝 Fix CHANGELOG

- CHANGELOG.md
- packages/form-builder/package.json
Correction des intervalles des `peerDependencies` ; notamment `@cnamts/vue-dot` dont la version était fixée
> 🐛 form-builder: Fix range for peer dependencies

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
Mise à jour du template pour les Pull Request
> 📝 Update Pull Request template

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppHeader.vue
Correction de la variable `maintenance` utilisée à la place de `$maintenanceEnabled` dans `AppHeader`
> 🐛 vue-dash: Fix undefined variable maintenance in AppHeader

- .circleci/config.yml
- CHANGELOG.md
- packages/vue-dot/vue.config.js
Utilisation de snake_case au lieu de kebab-case dans la config de CircleCI
- Maintenance
> 🎨 Use snake_case in CircleCI config

- CHANGELOG.md
- package.json
Ajout du champ `engines` dans le `package.json`
- Maintenance
> 🔧 Add engines to package.json

- CHANGELOG.md
- packages/vue-dot/src/elements/DataList/DataListLoading/DataListLoading.vue
- packages/vue-dot/src/elements/DataList/DataListLoading/tests/__snapshots__/DataListLoading.spec.ts.snap
- packages/vue-dot/src/patterns/SubHeader/tests/__snapshots__/SubHeader.spec.ts.snap
Ce composant étend le `SkeletonLoader` de Vuetify, on peut lui appliquer les mêmes [attributs ARIA](https://vuetifyjs.com/en/components/skeleton-loaders/#accessibility)
- Accessibilité
> ♿️ vue-dot: Add ARIA attributes on DataListLoading

- .github/ISSUE_TEMPLATE/feature_request.md
- CHANGELOG.md
Correction du template pour les demandes de nouvelles fonctionnalités suite à la démo
> 📝 Fix Feature Request issue template

- CHANGELOG.md
- packages/vue-dot/src/styles/vuetify.scss
Revert de la modification de `font-weight` sur les onglets
> 🐛 vue-dot: Fix tabs in vuetify.scss

- CHANGELOG.md
- packages/form-builder/src/components/FormBuilder/FormBuilder.vue
- packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/form-builder/src/components/FormFieldList/FormFieldList.vue
- packages/form-builder/src/components/FormFieldList/tests/__snapshots__/FormFieldList.spec.ts.snap
Utilisation des classes utilitaires de Vue Dot dans le FormBuilder
- Refactoring
> ♻️ form-builder: Use common styles from Vue Dot

- CHANGELOG.md
- packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
- packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
Correction des warnings (sûrement suite à la mise à jour du plugin ESLint Vue)
- Maintenance
> 🚨 vue-dot: Fix lint warnings

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/src/views/Maintenance.vue
- packages/vue-cli-plugin-vue-dash/generator/template/src/views/NotFound.vue
- packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/specs/NotFound.spec.ts
Correction de l'utilisation du composant `ErrorPage` dans le template de Vue Dash
> 🐛 vue-dash: Fix ErrorPage usage

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/src/services/dateFormatter.ts
Correction de l'export du service `formatDate`
> 🐛 vue-dash: Fix formatDate export

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/src/services/folders/api.ts
Réécriture du commentaire du service API exemple `folders`
- Refactoring
> ♻️ vue-dash: Update comment in folder API service

- CHANGELOG.md
- packages/vue-dot/playground/examples/TableToolbarEx.vue
- packages/vue-dot/src/patterns/TableToolbar/TableToolbar.vue
- packages/vue-dot/src/patterns/TableToolbar/config.ts
- packages/vue-dot/src/patterns/TableToolbar/locales.ts
- packages/vue-dot/src/patterns/TableToolbar/tests/TableToolbar.spec.ts
Renommage de `createBtn` en `addBtn`
- Refactoring
> ♻️ vue-dot: Rename createdBtn to addBtn in TableToolbar

- CHANGELOG.md
- packages/vue-dot/src/constants/enums/StateEnum.ts
Ajout de l'énumération `STATE_ENUM`
- Nouvelle fonctionnalité*
> ✨ vue-dot: Add STATE_ENUM constant

- CHANGELOG.md
- packages/form-builder/playground/theme/theme.scss
- packages/vue-dot/playground/components/DocSection.vue
- packages/vue-dot/playground/examples/DatePickerEx.vue
- packages/vue-dot/playground/examples/FileUploadEx.vue
- packages/vue-dot/playground/examples/UploadWorkflowEx.vue
- packages/vue-dot/playground/theme/theme.scss
Mise à jour des styles des playgrounds
- Refactoring
> ♻️ vue-dot: Refactor playground styles

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
Ajout du champ `engines` au fichier `package.json`
Fixes #905
- Maintenance
> 🔧 vue-dash: Add engines field to package.json

- CHANGELOG.md
- packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
Correction de l'espacement du slot `prepend`
Fixes #907
> 🐛 vue-dot: Fix spacing on prepend slot in DatePicker

- CHANGELOG.md
- packages/design-tokens/src/colors.ts
- packages/design-tokens/tests/__snapshots__/tokens.spec.ts.snap
Mise à jour des couleurs du thème.
Fixes #928 
- Refactoring
> ♻️ design-tokens: Update theme colors

- CHANGELOG.md
- LICENSE
- packages/form-builder/playground/Playground.vue
- packages/vue-dot/playground/Playground.vue
Mise à jour de la licence
- Maintenance
> 📄 Update license

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/vueDotLoader.js
Ajout des composants manquants pour le tree-shaking de VueDot
> 🐛 vue-dash: Add missing components in VueDotLoader

- CHANGELOG.md
- packages/form-builder/playground/Playground.vue
- packages/form-builder/playground/components/DocSection.vue
- packages/vue-dot/playground/Playground.vue
- packages/vue-dot/playground/components/DocSection.vue
- packages/vue-dot/playground/examples/UploadWorkflowEx.vue
Mise à jour des styles des playgrounds suite à la mise à jour du thème
- Refactoring
> ♻️ Update playgrounds styles

- CHANGELOG.md
- packages/vue-dot/src/patterns/SubHeader/SubHeader.vue
Correction de la couleur des boutons d'actions dans les `DataList` du `SubHeader`
Fixes #956 
> 🐛 vue-dot: Fix SubHeader action button color

- CHANGELOG.md
- packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
- packages/vue-dot/src/patterns/UploadWorkflow/mixins/tests/uploadWorkflowCore.spec.ts
- packages/vue-dot/src/patterns/UploadWorkflow/mixins/uploadWorkflowCore.ts
Correction de l'événement `view-file` non émis
Fixes #958 
> 🐛 vue-dot: Fix view-file event not emitted in UploadWorkflow

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/tsconfig.json
Suppression des commentaires inutiles dans le fichier `tsconfig.json`
- Refactoring
> 🔥 vue-dash: Remove unnecessary comments in tsconfig.json

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/_editorconfig
Correction d'une faute d'orthographe dans le fichier `.editorconfig`
- Maintenance
> ✏️ vue-dash: Fix typo in .editorconfig

- CHANGELOG.md
- packages/vue-dot/playground/examples/DataListEx.vue
- packages/vue-dot/src/elements/DataList/DataList.vue
- packages/vue-dot/src/elements/DataList/DataListLoading/DataListLoading.vue
- packages/vue-dot/src/elements/DataList/DataListLoading/tests/DataListLoading.spec.ts
- packages/vue-dot/src/elements/DataList/DataListLoading/tests/__snapshots__/DataListLoading.spec.ts.snap
- packages/vue-dot/src/elements/DataList/tests/DataList.spec.ts
- packages/vue-dot/src/elements/DataList/tests/__snapshots__/DataList.spec.ts.snap
- packages/vue-dot/src/patterns/SubHeader/tests/__snapshots__/SubHeader.spec.ts.snap
Suppression de la prop `flex` sur le composant `DataList`
Ce comportement sera porté par le composant `DataListGroup`
> 🔥 vue-dot: Remove flex prop in DataList

- CHANGELOG.md
- packages/vue-dot/src/elements/DataList/DataList.vue
- packages/vue-dot/src/elements/DataList/tests/__snapshots__/DataList.spec.ts.snap
- packages/vue-dot/src/patterns/SubHeader/SubHeader.vue
- packages/vue-dot/src/patterns/SubHeader/tests/__snapshots__/SubHeader.spec.ts.snap
Mise à jour du style par défaut du titre de la `DataList`
- Refactoring
> ♻️ vue-dot: Update default title styles in DataList

- CHANGELOG.md
- packages/vue-dot/playground/examples/DataListEx.vue
- packages/vue-dot/src/elements/DataList/DataList.vue
- packages/vue-dot/src/elements/DataList/DataListLoading/DataListLoading.vue
- packages/vue-dot/src/elements/DataList/types.d.ts
Correction d'un espace en trop sur le dernier item de la liste dans le composant `DataList`
> 🐛 vue-dot: Fix spacing on last item in DataList

- CHANGELOG.md
- packages/vue-dot/src/elements/DialogBox/DialogBox.vue
- packages/vue-dot/src/elements/DialogBox/config.ts
- packages/vue-dot/src/elements/DialogBox/tests/__snapshots__/DialogBox.spec.ts.snap
Correction des styles de la `DialogBox`
> 💄 vue-dot: Fix DialogBox styles

- CHANGELOG.md
- packages/vue-dot/vue.config.js
Mise à jour de la taille maximale du build
- Maintenance
> 🔧 vue-dot: Update build limit size

- CHANGELOG.md
- packages/vue-dot/src/elements/PageContainer/PageContainer.vue
- packages/vue-dot/src/elements/PageContainer/index.ts
- packages/vue-dot/src/elements/PageContainer/tests/PageContainer.spec.ts
- packages/vue-dot/src/elements/PageContainer/tests/__snapshots__/PageContainer.spec.ts.snap
- packages/vue-dot/src/elements/index.ts
- packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
- packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
- packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Création du composant PageContainer basé sur le composant vutify "v-sheet"
> ✨ vue-dot: Add PageContainer element

- CHANGELOG.md
- packages/vue-dot/src/elements/PageContainer/PageContainer.vue
- packages/vue-dot/src/elements/PageContainer/tests/__snapshots__/PageContainer.spec.ts.snap
Correction de l'espace non calculé correctement dans le composant `PageContainer`
> 🐛 vue-dot: Fix spacing in PageContainer

- CHANGELOG.md
- packages/vue-dot/src/elements/PageContainer/PageContainer.vue
Ajout de la prop `spacing` dans le composant `PageContainer`
> ✨ vue-dot: Add spacing prop in PageContainer

- CHANGELOG.md
- packages/vue-dot/src/elements/PageContainer/PageContainer.vue
- packages/vue-dot/src/elements/PageContainer/tests/__snapshots__/PageContainer.spec.ts.snap
Ajout de la prop `color` au composant `PageContainer`
> ✨ vue-dot: Add color prop in PageContainer

- CHANGELOG.md
- packages/cli-helpers/tests/traceLine.spec.ts
- packages/vue-dot/src/patterns/SubHeader/tests/SubHeader.spec.ts
Correction des erreurs de lint
- Maintenance
> 🚨 Fix lint warnings

- CHANGELOG.md
- packages/cli-helpers/package.json
- packages/form-builder/package.json
- packages/vue-cli-plugin-vue-dash/package.json
- packages/vue-dot/package.json
Suppression des propriétés `gitHead` dans les fichiers `package.json`.
Cette propriété est créée temporairement par lerna et ne devrait pas être versionnée ; je pense que c'est le résultat d'une commande loupée.
Voir https://github.com/lerna/lerna/issues/1880
- Refactoring
> 🔥 Remove gitHead properties in package.json files

- CHANGELOG.md
- packages/form-builder/dev/App.vue
- packages/vue-dot/dev/App.vue
Suppression d'une `div` inutile dans les playgrounds.
- Refactoring
> 🔥 Remove useless div in playgrounds

- CHANGELOG.md
- packages/form-builder/dev/App.vue
- packages/form-builder/dev/form-builder.ts
- packages/form-builder/dev/main.ts
- packages/vue-dot/dev/App.vue
> 🐛 Fix playgrounds

- CHANGELOG.md
- renovate.json
Mise à jour de la configuration de renovate :
- Ajout de `⬆️` en préfixe du message de commit
- Ajout du label `dependencies` sur les PR
- Correction de l'indentation du fichier
- Maintenance
> 🔧 Update renovate configuration

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
- packages/vue-cli-plugin-vue-dash/generator/template/public/index.html
Correction des erreurs de lint.
- Refactoring
> 🚨 vue-dash: Fix lint warnings

- CHANGELOG.md
- packages/form-builder/src/components/FormField/fields/ChoiceField.vue
- packages/form-builder/src/components/FormField/fields/PeriodField.vue
- packages/form-builder/src/components/FormField/fields/RangeField.vue
Correction de la réinitialisation de la valeur de certains champs.
Fixes #1135 
> 🐛 form-builder: Fix value not resetting in some fields

- CHANGELOG.md
- packages/vue-dot/src/elements/DialogBox/DialogBox.vue
- packages/vue-dot/src/patterns/FileUpload/FileUpload.vue
- packages/vue-dot/src/patterns/FileUpload/mixins/fileValidation.ts
Amélioration de la qualité du code
- Refactoring
> 🎨 vue-dot: Improve code quality

- CHANGELOG.md
- packages/vue-dot/src/patterns/SubHeader/SubHeader.vue
Correction de l'événement `click:list-item` ne fonctionnant pas dans le composant `SubHeader`.
<details>
```vue
<template>
<div>
<SubHeader
:data-list-group-items="dataListGroupItems"
title-text="Paul Dupont"
sub-title-text="1 69 08 75 125 456 75"
@click:list-item="setItemValue"
/>
<VSnackbar v-model="snackbar">
{{ snackbarText }}
<VBtn
text
color="red"
@click="snackbar = false"
>
Fermer
</VBtn>
</VSnackbar>
</div>
</template>
import { DataListGroupItems, DataListActionEvent } from '@cnamts/vue-dot/src/patterns/DataListGroup/types';
@Component
snackbar = false;
snackbarText = '';
dataListGroupItems: DataListGroupItems = [
{
title: 'Informations patient', …
```
> 🐛 vue-dot: Fix click:list-item event not working in SubHeader

- CHANGELOG.md
- packages/vue-dot/src/patterns/PaginatedTable/PaginatedTable.vue
Modification de la valeur par défaut de la prop `suffix` à `undefined` dans le composant `PaginatedTable`.
- Refactoring
> ♻️ vue-dot: Update default suffix value in PaginatedTable

- CHANGELOG.md
- packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue
Correction de l'affichage du bouton en mobile dans le composant `ExternalLinks`.
> 🐛 vue-dot: Fix button on mobile in ExternalLinks

- packages/docs/src/components/global/DocRoadmap.vue
- packages/docs/src/components/global/DocRoadmapItem.vue
- packages/docs/src/components/global/DocRoadmapRequestBtn.vue
- packages/docs/src/content/demarrer/roadmap.md
- packages/docs/src/data/drawerItems.ts
- packages/docs/src/data/roadmap/roadmap.ts
- packages/docs/src/types/roadmap.d.ts
<details>
```vue
```
</details>
> ✨ docs: Add Roadmap page

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
- packages/vue-cli-plugin-vue-dash/generator/getResourcesToDelete.js
- packages/vue-cli-plugin-vue-dash/generator/template/src/main.ts
- packages/vue-cli-plugin-vue-dash/prompts.js
Installer le FormBuilder par defaut dans le staterKit
- Refactoring
> 🔥 vue-dash: Remove FormBuilder prompt

- CHANGELOG.md
- packages/docs/src/components/global/DocExpansionPanel.vue
- packages/docs/src/components/global/DocExpansionPanels.vue
- packages/docs/src/content/demarrer/installation.md
Correction de l'affichage des `ExpansionPanels` dans la documentation.
Voir https://github.com/nuxt/content/issues/700.
> 🐛 docs: Fix expansion panels display

- CHANGELOG.md
- packages/docs/src/data/roadmap/roadmap.ts
Mise à jour de la page roadmap.
> 📝 docs: Update roadmap

- CHANGELOG.md
- packages/docs/src/content/composants/france-connect-btn.md
- packages/docs/src/content/examples/france-connect-btn/usage.vue
- packages/docs/src/data/api/france-connect-btn.ts
- packages/docs/src/data/drawerItems.ts
Documentation FranceConnectBtn
> 📝 docs: Add FranceConnectBtn documentation

- CHANGELOG.md
- packages/vue-dot/src/elements/DialogBox/tests/DialogBox.spec.ts
- packages/vue-dot/src/elements/DialogBox/tests/__snapshots__/DialogBox.spec.ts.snap
- packages/vue-dot/src/elements/ExternalLinks/tests/ExternalLinks.spec.ts
- packages/vue-dot/src/elements/ExternalLinks/tests/__snapshots__/ExternalLinks.spec.ts.snap
Mise à jour des labels des blocs `describe` dans les tests.
- Maintenance
> 🎨 vue-dot: Update describe labels in tests

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/tests/unit/App.spec.ts
Mise à jour des labels des blocs `describe` dans les tests.
- Maintenance
> 🎨 vue-dash: Update describe labels in tests

- CHANGELOG.md
- packages/docs/src/content/guides/nouveau-composant.md
Fix typing error and change the parameter name value as newValue
Correction d'une faute de frappe (`d'ne`)     
Modification du nom du parameter `value` dans les exemples,  car la variable utilisée est `newValue`
> 📝 docs: Update new component guide

- CHANGELOG.md
- packages/docs/nuxt.config.js
- packages/docs/src/content/guides/utilisation-store.md
- packages/docs/src/data/roadmap/roadmap.ts
Correction de fautes d'orthographe dans la documentation.
- Maintenance
> ✏️ docs: Fix typos

- CHANGELOG.md
- packages/docs/nuxt.config.js
- packages/docs/src/content/guides/utilisation-store.md
- packages/docs/src/hooks/applyTypographicRules.js
Ajout d'un hook pour appliquer des règles typographiques sur la documentation.
> ✨ docs: Add typographic rules hook

- CHANGELOG.md
- packages/docs/src/components/page/DocGithubLink.vue
- packages/docs/src/constants/index.ts
Correction du lien d'édition GitHub de la documentation.
> 🐛 docs: Fix GitHub edit link

- CHANGELOG.md
- packages/docs/src/content/demarrer/contribuer.md
- packages/docs/src/content/demarrer/glossaire.md
- packages/docs/src/content/demarrer/installation.md
- packages/docs/src/content/demarrer/roadmap.md
- packages/docs/src/content/guides/authentification-token.md
- packages/docs/src/content/guides/gestion-evenements.md
- packages/docs/src/content/guides/nouveau-composant.md
- packages/docs/src/content/guides/nouvelle-page.md
- packages/docs/src/content/guides/utilisation-store.md
- packages/docs/src/content/guides/v-model.md
- packages/docs/src/content/guides/validation-formulaire.md
- packages/docs/src/content/guides/variables-environnement.md
Ajout d'une indentation au début des sections de la documentation.
> 📝 docs: Add indent at sections start

- CHANGELOG.md
- packages/docs/src/content/demarrer/introduction.md
- packages/docs/src/pages/_.vue
Correction d'un lien "précédent" cassé dans la documentation.
> 🐛 docs: Fix broken prev link

- CHANGELOG.md
- packages/docs/src/components/global/DocContentExplorer.vue
Correction de l'affichage du Starter Kit Explorer dans la documentation.
> 🐛 docs: Fix ContentExplorer display

- CHANGELOG.md
- packages/docs/src/hooks/applyTypographicRules.js
Correction des règles typographiques (`\?`)
> 🐛 docs: Fix typographic rules

- CHANGELOG.md
- packages/docs/src/content/guides/nouveau-composant.md
- packages/docs/src/content/guides/validation-formulaire.md
Correction d'une mauvaise formulation dans la documentation.
> 📝 docs: Fix wording

- CHANGELOG.md
- packages/docs/src/content/demarrer/contribuer.md
Mise à jour de la page de contribution.
> 📝 docs: Update contribution guide

- CHANGELOG.md
- packages/docs/src/data/api/paginated-table.ts
Ajout de l'interface `DataOptions` dans l'api du composant PaginatedTable
> 📝 docs: Add DataOptions interface in PaginatedTable API

- CHANGELOG.md
- packages/docs/src/data/drawerItems.ts
Correction de l'import d'une icône inexistante.
> 🐛 docs: Fix wrong icon import

- CHANGELOG.md
- packages/docs/src/data/homePageListItems.ts
Mise à jour des icônes de la page d'introduction.
- Refactoring
> ♻️ docs: Update introduction page icons

- CHANGELOG.md
- packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/form-builder/src/components/FormBuilder/tests/data/questionForm.ts
- packages/form-builder/src/components/FormField/mixins/tests/choiceComponent.spec.ts
- packages/form-builder/src/components/FormFieldList/tests/data/addressFields.ts
- packages/form-builder/src/functions/setFormErrors/tests/__snapshots__/setFormErrors.spec.ts.snap
- packages/form-builder/src/functions/setFormErrors/tests/setFormErrors.spec.ts
Mise à jour de la formulation dans les tests du FormBuilder.
- Refactoring
> ♻️ form-builder: Update wording in tests

- CHANGELOG.md
- README.md
Mise à jour du badge npm dans le README.
> 📝 Update npm badge in README

- CHANGELOG.md
- packages/docs/package.json
- packages/docs/src/functions/slugify.ts
- packages/docs/src/functions/slugifyAnchors.ts
- packages/docs/src/pages/_.vue
- packages/docs/src/types/content.d.ts
- yarn.lock
Correction des accents dans les ancres HTML et utilisation du [package slugify](https://www.npmjs.com/package/slugify).
Issue liée :
- https://github.com/nuxt/content/issues/702
> 🐛 docs: Slugify anchors

- CHANGELOG.md
- packages/form-builder/package.json
- packages/vue-dot/package.json
Correction des fichiers de tests et de coverage publiés dans les packages.
> 🐛 Fix test & coverage files published

- CHANGELOG.md
- packages/docs/src/data/api/header-bar.ts
- packages/vue-dot/dev/main.ts
- packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
- packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/HeaderBrandSection.vue
- packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/tests/__snapshots__/HeaderBrandSection.spec.ts.snap
- packages/vue-dot/src/patterns/HeaderBar/tests/__snapshots__/HeaderBar.spec.ts.snap
Ajout d'un lien vers la page d'accueil sur le logo dans le composant `HeaderBar`.
<details>
```vue
<template>
<div class="d-flex flex-column w-100">
<h2 class="text-h6">
Logo initial
</h2>
<h3 class="text-subtitle-1 mt-2">
theme="default"
</h3>
<HeaderBar />
<h3 class="text-subtitle-1 mt-2">
theme="cnam"
</h3>
<HeaderBar theme="cnam">
Slot
<template #navigation-bar-content>
Test
</template>
</HeaderBar>
<h3 class="text-subtitle-1 mt-4">
theme="ameli"
</h3>
<HeaderBar theme="ameli" />
<h3 class="text-subtitle-1 mt-4">
theme="ameli-pro"
</h3>
<HeaderBar
theme="ameli-pro"
/>
<h3 class="text-subtitle-1 mt-4">
theme="risque-pro"
</h3>
<HeaderBar
theme="risque-pro"
>
<template #navigation-bar-content>
Test
</template> …
```
> ✨ vue-dot: Add link to home page on logo in HeaderBar

- CHANGELOG.md
- packages/docs/src/components/drawer/DocDrawerListGroup.vue
- packages/docs/src/components/drawer/DocDrawerListItem.vue
- packages/docs/src/content/demarrer/contribuer.md
- packages/docs/src/data/drawerItems.ts
- packages/docs/src/functions/getSurroundDrawerItemsPaths.ts
- packages/docs/src/types/drawer.d.ts
Ajout d'un lien vers la politique de signalement de vulnérabilités à la documentation.
> 📝 docs: Add link to vulnerability reporting policy

- CHANGELOG.md
- SECURITY.md
Ajout du fichier `SECURITY.md`.
> 📝 Add SECURITY.md

- CHANGELOG.md
- packages/docs/src/functions/slugifyAnchors.ts
Correction des liens externes ne fonctionnant pas.
Closes #1635 
> 🐛 docs: Fix external links not working

- CHANGELOG.md
- packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/tests/HeaderBrandSection.spec.ts
- packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/tests/__snapshots__/HeaderBrandSection.spec.ts.snap
Correction d'un warning dans le test du composant `HeaderBrandSection`.
- Maintenance
> ✅ vue-dot: Fix warning in HeaderBrandSection test

- CHANGELOG.md
- packages/design-tokens/src/colors.ts
- packages/design-tokens/tests/__snapshots__/tokens.spec.ts.snap
Mise à jour de la couleur de warning.
- Refactoring
> ♻️ design-tokens: Update warning color

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/public/css/base.css
Mise à jour de la couleur de fond par défaut dans le template du Starter Kit.
- Refactoring
> ♻️ vue-dash: Update default background color in template

- CHANGELOG.md
- packages/vue-dot/src/patterns/DatePicker/mixins/dateLogic.ts
Correction de la valeur du composant `DatePicker` mal réinitialisée sans `v-model`.
> 🐛 vue-dot: Fix value not reset without v-model

- CHANGELOG.md
- packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
- packages/vue-dot/src/patterns/DatePicker/mixins/dateLogic.ts
- packages/vue-dot/src/patterns/DatePicker/mixins/tests/dateLogic.spec.ts
Ajout de la gestion du copier/coller dans le composant `DatePicker`.
<details>
```vue
<template>
<DatePicker />
</template>
@Component
</script>
```
</details>
> ✨ vue-dot: Handle copy-paste in DatePicker

- CHANGELOG.md
- packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
- packages/vue-dot/src/patterns/DatePicker/mixins/birthdate.ts
- packages/vue-dot/src/patterns/DatePicker/mixins/tests/birthdate.spec.ts
Correction d'une erreur lors de la mise à jour de la prop `activePicker` en mode `birthdate`  dans le composant `DatePicker`.
<details>
```vue
<template>
<DatePicker
v-model="date"
birthdate
/>
</template>
@Component
date: string | null = null;
}
</script>
```
</details>
> 🐛 vue-dot: Fix error when updating pickerDate in DatePicker

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppHeader/tests/AppHeader.spec.ts
Ajout d'un test sur `AppHeader` dans le Starter Kit.
- Maintenance
> ✅ vue-dash: Add test on AppHeader

- CHANGELOG.md
- packages/docs/src/data/contentExplorerItems.ts
- packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
- packages/vue-cli-plugin-vue-dash/generator/template/jest.config.js
Utilisation de TypeScript pour la configuration de Jest dans le Starter Kit.
- Refactoring
> ♻️ vue-dash: Use TypeScript for Jest configuration

- CHANGELOG.md
- packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/form-builder/src/components/FormField/fields/ChoiceButtonField.vue
- packages/form-builder/src/components/FormField/fields/ChoiceSliderField.vue
- packages/form-builder/src/components/FormField/fields/tests/__snapshots__/ChoiceField.spec.ts.snap
Utilisation de la couleur primaire au lieu de la couleur d'accent dans les champs du composant `FormField`.
<details>
```vue
<template>
<div>
<FormField v-model="choiceBtnField" />
<FormField v-model="choiceSliderField" />
</div>
</template>
@Component
choiceBtnField: Field = {
items: [
{
text: 'Email',
value: 'email'
},
{
value: 'mail'
},
{
text: 'SMS',
value: 'sms'
}
],
value: null,
type: 'choiceButton',
label: 'Moyen de contact',
outlined: true
}
};
choiceSliderField: Field = {
items: [
{
text: …
```
> ♻️ form-builder: Use primary color instead of accent in FormField

- CHANGELOG.md
- packages/docs/src/components/global/DocA11yCriteria.vue
- packages/docs/src/constants/ExpertiseLevelEnum.ts
- packages/docs/src/constants/RGAALevelEnum.ts
- packages/docs/src/content/demarrer/accessibilite.md
- packages/docs/src/data/a11yCriteriaItems.ts
- packages/docs/src/data/drawerItems.ts
Ajout de la page accessibilité à la documentation.
> 📝 docs: Add a11y page

- CHANGELOG.md
- packages/docs/src/content/explorer/public/css/base.css.md
Mise à jour du content du fichier `base.css` dans le StarterKit Explorer.
> 📝 docs: Update base.css content in explorer

- CHANGELOG.md
- packages/docs/src/functions/formatReleaseDate.ts
Correction de l'affichage de la date de dernière publication dans la documentation.
> 🐛 docs: Fix last release date formatting

- CHANGELOG.md
- packages/docs/src/components/global/DocHomePageHeader.vue
- packages/docs/src/pages/_.vue
Mise à jour de l'espacement des pages de la documentation.
- Refactoring
> ♻️ docs: Update page spacing

- CHANGELOG.md
- packages/docs/src/pages/_.vue
Utilisation du composant `PageContainer` dans la documentation.
- Refactoring
> ♻️ docs: Use PageContainer component

- CHANGELOG.md
- packages/docs/src/components/global/DocHomePageHeader.vue
Refonte du layout de la page d'introduction de la documentation.
- Refactoring
> ♻️ docs: Refactor introduction page layout

- CHANGELOG.md
- packages/docs/src/components/global/DocRoadmapRequestBtn.vue
Mise à jour du lien pour créer une nouvelle demande et de la taille du bouton de demande dans la documentation.
- Refactoring
> ♻️ docs: Update roadmap request URL & button size

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
Correction du hook de qualité manquant dans le Starter Kit.
> 🐛 vue-dash: Fix missing lint hook in template

- CHANGELOG.md
- packages/docs/src/content/composants/footer-bar.md
- packages/vue-dot/src/patterns/FooterBar/FooterBar.vue
Bind de `$attrs` au composant `FooterBar`.
> ✨ vue-dot: Pass down attributes in FooterBar

- CHANGELOG.md
- packages/docs/src/content/composants/dialog-box.md
- packages/docs/src/content/composants/download-btn.md
- packages/docs/src/content/composants/header-bar.md
- packages/docs/src/content/composants/header-loading.md
- packages/docs/src/content/composants/paginated-table.md
Ajout d'informations sur les propriétés transmises aux composants dans la documentation.
> 📝 docs: Add information about passed down attributes

- CHANGELOG.md
- packages/docs/src/data/api/upload-workflow.ts
Mise à jour de la description de la prop `customizable` du composant `UploadWorkflow`.
> 📝 docs: Update customizable prop description in UploadWorkflow

- CHANGELOG.md
- packages/vue-dot/src/templates/ErrorPage/ErrorPage.vue
Utilisation d'une constante `MixinsDeclaration` dans le composant `ErrorPage`.
- Refactoring
> 🎨 vue-dot: Use MixinsDeclaration in ErrorPage

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/src/components/Links/Links.vue
Utilisation d'une constante `MixinsDeclaration` dans le composant `Links` dans le Starter Kit.
- Refactoring
> 🎨 vue-dash: Use MixinsDeclaration in Links component

- CHANGELOG.md
- packages/docs/src/components/global/DocExpansionPanel.vue
- packages/docs/src/components/global/DocExpansionPanels.vue
Mise à jour des styles du composant `DocExpansionPanels`.
- Refactoring
> ♻️ docs: Update DocExpansionPanels style

- CHANGELOG.md
- packages/docs/src/assets/styles/index.scss
- packages/docs/src/assets/styles/utilities.scss
- packages/docs/src/components/code/DocCodeBlock.vue
- packages/docs/src/components/content-explorer/ContentExplorer.vue
- packages/docs/src/components/global/DocRoadmapItem.vue
- packages/docs/src/components/global/DocTabs.vue
- packages/docs/src/components/global/DocUsage.vue
Mise à jour des couleurs de fond dans la documentation en utilisant les couleurs de la charte.
- Refactoring
> ♻️ docs: Update background colors

- CHANGELOG.md
- packages/docs/src/content/examples/data-list-group/options.vue
- packages/docs/src/content/examples/data-list/options.vue
- packages/docs/src/content/examples/date-picker/range.vue
- packages/docs/src/content/examples/external-links/btn-text.vue
- packages/docs/src/content/examples/external-links/no-data.vue
- packages/docs/src/content/examples/external-links/nudge-top.vue
- packages/docs/src/content/examples/external-links/options.vue
- packages/docs/src/content/examples/external-links/slots.vue
- packages/docs/src/content/examples/external-links/usage.vue
- packages/docs/src/content/examples/footer-bar/options.vue
- packages/docs/src/content/examples/footer-bar/slots.vue
- packages/docs/src/content/examples/header-bar/secondary-logo-slot.vue
- packages/docs/src/content/examples/header-bar/slots.vue
- packages/docs/src/content/examples/header-bar/title-sub-title.vue
- packages/docs/src/content/examples/table-toolbar/options.vue
Mise à jour des exemples dans la documentation.
> 📝 docs: Update examples

- CHANGELOG.md
- packages/docs/src/pages/_.vue
Correction de la hauteur minimale des pages de la documentation.
> 🐛 docs: Fix page minimum height

- CHANGELOG.md
- packages/docs/src/content/explorer/jest.config.ts.md
Renommage du fichier `jest.config.js` en `jest.config.ts` dans le Starter Kit Explorer.
> 📝 docs: Rename jest.config.js to jest.config.ts

- CHANGELOG.md
- packages/docs/src/components/global/DocUsage.vue
Mise à jour des styles du composant `DocUsage` de la documentation.
- Refactoring
> ♻️ docs: Update DocUsage styles

- CHANGELOG.md
- packages/docs/src/assets/styles/code-block-theme.scss
- packages/docs/src/assets/styles/code.scss
Mise à jour des couleurs du thème pour le code dans la documentation.
- Refactoring
> ♻️ docs: Update code theme colors

- CHANGELOG.md
- packages/docs/src/components/global/DocUsage.vue
Affichage du langage dans le composant `DocUsage` dans la documentation.
> ✨ docs: Display language in DocUsage

- CHANGELOG.md
- packages/vue-dot/src/patterns/FooterBar/FooterBar.vue
Application des styles au contenu des slots dans le composant `FooterBar`
> 🐛 vue-dot: Fix styles not applied to slot content in FooterBar

- CHANGELOG.md
- packages/vue-dot/src/patterns/FooterBar/FooterBar.vue
- packages/vue-dot/src/patterns/FooterBar/tests/__snapshots__/FooterBar.spec.ts.snap
Correction de l'affichage du composant `FooterBar` sur les écrans mobiles.
> 🐛 vue-dot: Fix FooterBar display on mobile

- CHANGELOG.md
- packages/docs/src/data/api/date-picker.ts
Mise à jour de la description de la prop `picker-date` du composant `DatePicker`.
> 📝 docs: Update picker-date prop description in DatePicker

- CHANGELOG.md
- packages/docs/src/content/examples/guides/form-validation/final-form.vue
- packages/docs/src/content/guides/validation-formulaire.md
- packages/vue-dot/src/types.d.ts
Ajout de l'interface `VForm` dans les types de Vue Dot.
> ✨ vue-dot: Add VForm interface in types

- CHANGELOG.md
- packages/docs/src/data/designPrinciplesPageItems.ts
Mise à jour de la page principes de design dans la documentation.
> 📝 docs: Update design principles page

- CHANGELOG.md
- packages/vue-dot/src/functions/formatNir/tests/formatNir.spec.ts
Correction d'une faute d'orthographe dans le fichier `formatNir.spec.ts`.
- Maintenance
> ✏️ vue-dot: Fix typo in formatNir test

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/src/components/Links/tests/Links.spec.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppFooter/tests/AppFooter.spec.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppHeader/tests/AppHeader.spec.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppHeader/tests/HeaderMenu.spec.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/views/tests/About.spec.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/views/tests/Home.spec.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/views/tests/Maintenance.spec.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/views/tests/NotFound.spec.ts
- packages/vue-cli-plugin-vue-dash/generator/template/tests/unit/App.spec.ts
Suppression des commentaires inutiles dans les tests.
- Maintenance
> 🔥 vue-dash: Remove unnecessary comments in test files

- CHANGELOG.md
- packages/form-builder/src/components/FormBuilder/mixins/tests/formBuilderCore.spec.ts
- packages/form-builder/src/components/FormBuilder/tests/FormBuilder.spec.ts
- packages/form-builder/src/components/FormField/fields/tests/ChoiceField.spec.ts
- packages/form-builder/src/components/FormField/mixins/tests/fieldComponent.spec.ts
- packages/form-builder/src/components/FormField/mixins/tests/fieldMap.spec.ts
- packages/form-builder/src/components/FormField/tests/FormField.spec.ts
- packages/form-builder/src/components/FormFieldList/tests/FormFieldList.spec.ts
- packages/form-builder/src/functions/getFormValues/tests/getFormValue.spec.ts
- packages/form-builder/src/functions/setFormErrors/tests/setFormErrors.spec.ts
Suppression des commentaires inutiles dans les tests.
- Maintenance
> 🔥 form-builder: Remove unnecessary comments in test files

- CHANGELOG.md
- packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
Correction de l'affichage du bouton pour activer le menu sur les écrans mobiles affiché même s'il n'y a pas d'éléments de navigation.
<details>
```vue
<template>
<HeaderBar />
</template>
```
</details>
> 🐛 vue-dot: Fix menu button display on mobile in HeaderBar

- CHANGELOG.md
- packages/vue-dot/src/types.d.ts
Ajout de la propriété `resetValidation` à l'interface `VForm`.
> ✨ vue-dot: Add resetValidation property to VForm interface

- CHANGELOG.md
- packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
Correction de l'affichage de la barre de navigation dans le composant `HeaderBar`.
> 🐛 vue-dot: Fix navigation bar display in HeaderBar

- CHANGELOG.md
- packages/docs/src/content/regles-validation/min-length.md
- packages/docs/src/data/api/rules/min-length.ts
- packages/vue-dot/src/rules/minLength/index.ts
- packages/vue-dot/src/rules/minLength/tests/minLength.spec.ts
Ajout de l'option `ignoreSpaces` à la règle de validation `minLength` .
> ✨ vue-dot: Add ignoreSpaces option to minLength rule

- CHANGELOG.md
- packages/docs/src/content/demarrer/installation.md
- packages/vue-cli-plugin-vue-dash/README.md
Ajout du tree-shaking de VueDot dans le README de Vue Dash.
> 📝 vue-dash: Add Vue Dot tree-shaking in README

- CHANGELOG.md
- packages/docs/src/assets/styles/typography/index.scss
- packages/docs/src/components/global/DocDesignPrinciplesPage.vue
- packages/docs/src/content/demarrer/contribuer.md
- packages/docs/src/content/demarrer/roadmap.md
- packages/docs/src/content/examples/data-list-group/options.vue
- packages/docs/src/content/examples/data-list/options.vue
- packages/docs/src/data/designPrinciplesPageItems.ts
Correction des styles et des espacements dans la documentation.
Closes #1428
> 🐛 docs: Fix styles & spacing

- CHANGELOG.md
- packages/docs/src/content/regles-validation/not-after-date.md
- packages/docs/src/data/api/rules/not-after-date.ts
- packages/docs/src/data/api/rules/not-after-today.ts
- packages/docs/src/data/drawerItems.ts
- packages/vue-dot/src/functions/formatDate/index.ts
- packages/vue-dot/src/functions/formatDate/tests/formatDate.spec.ts
- packages/vue-dot/src/functions/isDateAfterValue/index.ts
- packages/vue-dot/src/functions/isDateAfterValue/tests/isDateAfterValue.spec.ts
- packages/vue-dot/src/rules/minLength/tests/minLength.spec.ts
- packages/vue-dot/src/rules/notAfterDate/index.ts
- packages/vue-dot/src/rules/notAfterDate/locales.ts
- packages/vue-dot/src/rules/notAfterDate/tests/notAfterDate.spec.ts
Ajout de la règle de validation `notAfterDate`.
> ✨ vue-dot: Add notAfterDate rule

- CHANGELOG.md
- packages/docs/src/content/regles-validation/not-after-today.md
- packages/docs/src/content/regles-validation/not-before-date.md
- packages/docs/src/data/api/rules/not-before-date.ts
- packages/docs/src/data/drawerItems.ts
- packages/vue-dot/src/functions/isDateBeforeValue/index.ts
- packages/vue-dot/src/functions/isDateBeforeValue/tests/isDateBeforeValue.spec.ts
- packages/vue-dot/src/rules/notBeforeDate/index.ts
- packages/vue-dot/src/rules/notBeforeDate/locales.ts
- packages/vue-dot/src/rules/notBeforeDate/tests/notBeforeDate.spec.ts
Ajout de la règle de validation `notBeforeDate`.
> ✨ vue-dot: Add notBeforeDate rule

- CHANGELOG.md
- packages/vue-dot/src/directives/debounce/core.ts
- packages/vue-dot/src/directives/debounce/index.ts
- packages/vue-dot/src/directives/debounce/tests/debounce.spec.ts
- packages/vue-dot/src/directives/debounce/types.d.ts
Refonte de la directive `debounce` pour améliorer la qualité du code.
- Refactoring
> ♻️ vue-dot: Refactor debounce directive

- CHANGELOG.md
- packages/design-tokens/scripts/build.ts
- packages/design-tokens/src/colors.ts
- packages/design-tokens/tsconfig.json
Suppression et mise à jour des commentaires.
- Refactoring
> ♻️ design-tokens: Remove & update comments

- CHANGELOG.md
- packages/docs/src/assets/styles/base.scss
- packages/docs/src/assets/styles/code-block-theme.scss
- packages/docs/src/components/global/DocMaterialLoader.vue
- packages/docs/src/content/examples/sub-header/action.vue
- packages/docs/src/modules.d.ts
- packages/docs/src/plugins/axios.ts
- packages/docs/src/plugins/vue-dot.ts
- packages/docs/tsconfig.json
Suppression et mise à jour des commentaires.
- Refactoring
> ♻️ docs: Remove & update comments

- CHANGELOG.md
- packages/docs/src/assets/styles/base.scss
- packages/docs/src/assets/styles/index.scss
- packages/docs/src/components/content-explorer/ContentExplorer.vue
- packages/docs/src/components/drawer/DocDrawerListGroup.vue
- packages/docs/src/components/global/DocExample.vue
- packages/docs/src/components/global/DocRoadmapItem.vue
- packages/docs/src/components/global/DocUsage.vue
- packages/docs/src/content/examples/debounce/arg.vue
- packages/docs/src/content/examples/dialog-box/slots.vue
- packages/docs/src/content/examples/download-btn/slots.vue
- packages/docs/src/content/examples/table-toolbar/labels.vue
- packages/docs/src/content/examples/table-toolbar/nb-filtered.vue
- packages/docs/src/content/examples/upload-workflow/events.vue
- packages/docs/src/data/api/custom-icon.ts
- packages/docs/src/data/api/data-list-group.ts
- packages/docs/src/data/api/logo.ts
- packages/docs/src/data/api/shared/mixins/customizable.ts
- packages/docs/src/data/api/shared/mixins/widthable.ts
- packages/docs/src/decorators.ts
- packages/docs/src/functions/toCamelCase.ts
- packages/docs/src/functions/toKebabCase.ts
- packages/docs/src/functions/toPascalCase.ts
- packages/docs/src/global.d.ts
- packages/docs/src/layouts/error.vue
- packages/docs/src/pages/_.vue
- packages/docs/src/plugins/form-builder.ts
- packages/docs/src/services/getUsers/types.d.ts
Amélioration de la qualité du code.
- Refactoring
> 🎨 docs: Improve code quality

- CHANGELOG.md
- packages/form-builder/dev/README.md
- packages/form-builder/scripts/build.ts
- packages/form-builder/src/components/FormBuilder/FormBuilder.vue
- packages/form-builder/src/components/FormBuilder/mixins/formBuilderCore.ts
- packages/form-builder/src/components/FormField/FormField.vue
- packages/form-builder/src/components/FormField/fields/ChoiceAutocompleteField.vue
- packages/form-builder/src/components/FormField/fields/ChoiceButtonField.vue
- packages/form-builder/src/components/FormField/fields/ChoiceField.vue
- packages/form-builder/src/components/FormField/fields/ChoiceSelectField.vue
- packages/form-builder/src/components/FormField/fields/ChoiceSliderField.vue
- packages/form-builder/src/components/FormField/fields/DateField.vue
- packages/form-builder/src/components/FormField/fields/NumberField.vue
- packages/form-builder/src/components/FormField/fields/PasswordField.vue
- packages/form-builder/src/components/FormField/fields/PeriodField.vue
- packages/form-builder/src/components/FormField/fields/TextField.vue
- packages/form-builder/src/components/FormField/fields/TextareaField.vue
- packages/form-builder/src/components/FormField/mixins/choiceComponent.ts
- packages/form-builder/src/components/FormField/mixins/fieldComponent.ts
- packages/form-builder/src/components/FormField/mixins/fieldMap.ts
- packages/form-builder/src/components/FormFieldList/FormFieldList.vue
- packages/form-builder/src/functions/getFormValues/index.ts
- packages/form-builder/src/functions/setFormErrors/index.ts
- packages/form-builder/src/functions/setFormErrors/tests/data/formErrors.ts
- packages/form-builder/src/index.ts
- packages/form-builder/src/registerAllComponents.ts
- packages/form-builder/vue.config.js
Suppression et mise à jour des commentaires.
- Refactoring
> ♻️ form-builder: Remove & update comments

- CHANGELOG.md
- packages/docs/src/content/examples/header-bar/default-slot.vue
Mise à jour de l'exemple d'utilisation du slot par défaut du composant `HeaderBar`.
> 📝 docs: Update HeaderBar default slot example

- CHANGELOG.md
- packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/form-builder/src/components/FormField/FormField.vue
- packages/form-builder/src/components/FormField/fields/RangeField.vue
- packages/form-builder/src/components/FormField/mixins/fieldComponent.ts
Amélioration de la qualité du code.
- Refactoring
> 🎨 form-builder: Improve code quality

- CHANGELOG.md
- packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/form-builder/src/components/FormField/FormField.vue
- packages/form-builder/src/components/FormField/fields/ChoiceButtonField.vue
- packages/form-builder/src/components/FormField/fields/tests/__snapshots__/ChoiceField.spec.ts.snap
Ajout des attributs ARIA manquants sur le composant `ChoiceButtonField`.
> ♿️ form-builder: Add missing ARIA attributes in ChoiceButtonField

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/fixEnvFile.js
- packages/vue-cli-plugin-vue-dash/generator/functions/deleteOldResources.js
- packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
- packages/vue-cli-plugin-vue-dash/generator/functions/parseIndexFile.js
- packages/vue-cli-plugin-vue-dash/generator/index.js
- packages/vue-cli-plugin-vue-dash/index.js
- packages/vue-cli-plugin-vue-dash/prompts.js
- packages/vue-cli-plugin-vue-dash/vueDotLoader.js
Suppression et mise à jour des commentaires.
- Refactoring
> ♻️ vue-dash: Remove & update comments

- CHANGELOG.md
- packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/HeaderBrandSection.vue
- packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/locales.ts
- packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/tests/__snapshots__/HeaderBrandSection.spec.ts.snap
Ajout des attributs ARIA manquants sur le composant `HeaderBar`.
> ♿️ vue-dot: Add missing ARIA attributes in HeaderBar

- CHANGELOG.md
- packages/docs/src/data/api/header-bar.ts
Le nom du slot pour la marque partenaire n'est pas bon dans la documentation (secondary-logo et non secondary-brand)
> 📝 docs: Fix HeaderBar secondary-logo slot name

- CHANGELOG.md
- packages/vue-dot/src/elements/HeaderLoading/HeaderLoading.vue
- packages/vue-dot/src/elements/HeaderLoading/tests/__snapshots__/HeaderLoading.spec.ts.snap
- packages/vue-dot/src/patterns/SubHeader/tests/__snapshots__/SubHeader.spec.ts.snap
Ajout de l'attribut `aria-hidden` sur le composant `HeaderLoading`.
> ♿️ vue-dot: Add aria-hidden on HeaderLoading

- CHANGELOG.md
- packages/docs/src/data/api/form-builder.ts
- packages/docs/src/data/api/form-field-list.ts
- packages/docs/src/data/api/upload-workflow.ts
Utilisation du caractère apostrophe dans la documentation.
- Refactoring
> ♻️ docs: Use proper quote character

- CHANGELOG.md
- packages/vue-dot/src/elements/DataList/DataListLoading/DataListLoading.vue
- packages/vue-dot/src/elements/DataList/DataListLoading/tests/DataListLoading.spec.ts
- packages/vue-dot/src/elements/DataList/DataListLoading/tests/__snapshots__/DataListLoading.spec.ts.snap
Suppression des styles inutiles dans le composant `DataListLoading`.
- Refactoring
> 🔥 vue-dot: Remove unnecessary styles in DataListLoading

- CHANGELOG.md
- packages/vue-dot/src/elements/DialogBox/DialogBox.vue
- packages/vue-dot/src/elements/DialogBox/config.ts
- packages/vue-dot/src/elements/DialogBox/tests/__snapshots__/DialogBox.spec.ts.snap
Correction de l'alignement du titre dans le composant `DialogBox`.
> 🐛 vue-dot: Fix title alignment in DialogBox

- CHANGELOG.md
- packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
Correction de l'affichage des menus dans le composant `HeaderBar`.
> 🐛 vue-dot: Fix menus display in HeaderBar

- CHANGELOG.md
- packages/docs/src/components/DocHeader.vue
Correction du chevauchement du composant `DocHeader`.
> 🐛 docs: Fix DocHeader overlap

- CHANGELOG.md
- packages/vue-dot/src/patterns/SubHeader/SubHeader.vue
- packages/vue-dot/src/patterns/SubHeader/config.ts
- packages/vue-dot/src/patterns/SubHeader/tests/__snapshots__/SubHeader.spec.ts.snap
Correction de l'espacement interne du bouton *Retour* dans le composant `SubHeader`.
> 🐛 vue-dot: Fix back button padding in SubHeader

- CHANGELOG.md
- packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
Modification de la valeur de la propriété `z-index` dans le composant `HeaderBar`.
- Refactoring
> ♻️ vue-dot: Update z-index value in HeaderBar

- CHANGELOG.md
- packages/docs/src/components/DocHeader.vue
Correction de l'affichage du menu de navigation dans le header de la documentation.
> 🐛 docs: Fix drawer display in DocHeader

- CHANGELOG.md
- packages/docs/src/content/examples/header-bar/themes.vue
- packages/docs/src/content/examples/header-bar/usage.vue
- packages/docs/src/data/api/header-bar.ts
- packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
- packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/HeaderBrandSection.vue
- packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/locales.ts
- packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/tests/__snapshots__/HeaderBrandSection.spec.ts.snap
- packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/types.d.ts
- packages/vue-dot/src/patterns/HeaderBar/ThemeEnum.ts
- packages/vue-dot/src/patterns/HeaderBar/colorMapping.ts
- packages/vue-dot/src/patterns/HeaderBar/tests/__snapshots__/HeaderBar.spec.ts.snap
Ajout du thème *Compte entreprise* dans le composant `HeaderBar`.
> ✨ vue-dot: Add compte-entreprise theme in HeaderBar

- CHANGELOG.md
- packages/docs/src/content/examples/user-menu-btn/usage.vue
- packages/vue-dot/src/elements/UserMenuBtn/UserMenuBtn.vue
- packages/vue-dot/src/elements/UserMenuBtn/config.ts
Correction de l'espacement interne du composant `UserMenuBtn`.
> 🐛 vue-dot: Fix padding in UserMenuBtn

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/getResourcesToDelete.js
- packages/vue-cli-plugin-vue-dash/generator/index.js
Correction du fichier `main.js` non supprimé dans le Starter Kit.
> 🐛 vue-dash: Fix main.js file not deleted

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/functions/deleteOldResources.js
- packages/vue-cli-plugin-vue-dash/generator/index.js
Correction de la suppression des anciens fichiers dans le Starter Kit.
> 🐛 vue-dash: Fix old resources deletion

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/index.js
- packages/vue-cli-plugin-vue-dash/generator/template/README.md
- packages/vue-cli-plugin-vue-dash/generator/template/public/index.html
- packages/vue-cli-plugin-vue-dash/generator/template/public/site.webmanifest
- packages/vue-cli-plugin-vue-dash/generator/template/src/App.vue
- packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppHeader/AppHeader.vue
- packages/vue-cli-plugin-vue-dash/generator/template/src/translations/fr/common.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/translations/fr/components/layout/appHeader.ts
- packages/vue-cli-plugin-vue-dash/prompts.js
Amélioration de la qualité du code en renommant `name` en `projectName` et `description` en `projectDescription` dans le Starter Kit.
- Refactoring
> 🎨 vue-dash: Improve code quality

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppHeader/tests/AppHeader.spec.ts
- packages/vue-cli-plugin-vue-dash/generator/template/tests/unit/App.spec.ts
Correction des tests unitaires dans le template du Starter Kit.
> 🐛 vue-dash: Fix unit tests in template

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/_gitignore
Correction du fichier `package-lock.json` présent dans le fichier `.gitignore` dans le Starter Kit.
> 🐛 vue-dash: Fix package-lock.json present in .gitignore

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/src/views/About.vue
- packages/vue-cli-plugin-vue-dash/generator/template/src/views/Home.vue
Modification de la position du bouton *Retour* dans le template du Starter Kit.
> ♻️ vue-dot: Update back button position in template

- CHANGELOG.md
- packages/docs/src/content/examples/header-bar/options.vue
- packages/docs/src/content/examples/header-bar/themes.vue
Mise à jour des exemples du composant `HeaderBar` dans la documentation.
> 📝 docs: Update HeaderBar examples

- CHANGELOG.md
- packages/vue-dot/src/rules/notAfterToday/index.ts
Correction des erreurs de lint dans Vue Dot.
- Maintenance
> 🚨 vue-dot: Fix lint errors

- CHANGELOG.md
- packages/docs/src/content/composants/cookie-banner.md
- packages/docs/src/content/examples/cookie-banner/options.vue
- packages/docs/src/content/examples/cookie-banner/slots.vue
- packages/docs/src/content/examples/cookie-banner/usage.vue
- packages/docs/src/data/api/cookie-banner.ts
- packages/docs/src/data/drawerItems.ts
- packages/vue-cli-plugin-vue-dash/vueDotLoader.js
- packages/vue-dot/src/patterns/CookieBanner/CookieBanner.vue
- packages/vue-dot/src/patterns/CookieBanner/config.ts
- packages/vue-dot/src/patterns/CookieBanner/index.ts
- packages/vue-dot/src/patterns/CookieBanner/locales.ts
- packages/vue-dot/src/patterns/CookieBanner/tests/CookieBanner.spec.ts
- packages/vue-dot/src/patterns/CookieBanner/tests/__snapshots__/CookieBanner.spec.ts.snap
- packages/vue-dot/src/patterns/index.ts
- packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
- packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
- packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Ajout du nouveau composant `CookieBanner`.
> ✨ vue-dot: Add CookieBanner pattern

- CHANGELOG.md
- packages/form-builder/package.json
- packages/form-builder/scripts/build.ts
- packages/form-builder/scripts/post-install.ts
Refonte des scripts `build` et `post-install` dans le Form Builder.
- Refactoring
> 🔧 form-builder: Refactor build & post-install scripts

- CHANGELOG.md
- packages/docs/src/content/examples/cookies-page/usage.vue
Mise à jour de l'exemple d'utilisation du composant `CookiesPage` dans la documentation.
> 📝 docs: Update CookiesPage usage exemple

- CHANGELOG.md
- packages/vue-dot/src/templates/CookiesPage/CookiesInformation/CookiesInformation.vue
- packages/vue-dot/src/templates/CookiesPage/types.d.ts
Amélioration de la qualité du code dans le composant `CookiesPage`.
- Refactoring
> 🎨 vue-dot: Improve code quality in CookiesPage

- CHANGELOG.md
- packages/vue-dot/src/patterns/FooterWrapper/FooterBtn/FooterBtn.vue
- packages/vue-dot/src/patterns/FooterWrapper/FooterBtn/tests/FooterBtn.spec.ts
- packages/vue-dot/src/patterns/FooterWrapper/FooterWrapper.vue
- packages/vue-dot/src/patterns/FooterWrapper/tests/FooterWrapper.spec.ts
- packages/vue-dot/vue.config.js
Utilisation de `consola` pour les logs de dépréciation dans Vue Dot.
- Refactoring
> ♻️ vue-dot: Use consola for deprecation logs in FooterWrapper

- CHANGELOG.md
- packages/docs/src/components/global/DocApi.vue
Use h2 instead of h3 in doc tabs if there is no title
> 📝docs: Use h2 when no component names in DocApi

- .circleci/config.yml
- CHANGELOG.md
Mise à jour de la configuration de CircleCI.
- Maintenance
> 🔧 Add resource class to CircleCI config

- CHANGELOG.md
- packages/docs/src/components/DocHeader.vue
- packages/docs/src/components/DocReleasesMenu.vue
Ajout d'un menu avec des informations sur les versions dans la documentation.
> ✨ docs: Add menu with versions info

- CHANGELOG.md
- packages/docs/src/components/DocHeader.vue
- packages/docs/src/components/DocReleasesMenu.vue
Ajout d'un lien vers GitHub dans le header de la documentation.
> ✨ docs: Add GitHub link in header

- CHANGELOG.md
- packages/docs/src/components/DocReleasesMenu.vue
- packages/docs/src/content/demarrer/notes-de-version.md
Ajout d'un lien vers les notes de version antérieures dans la page *Notes de version*.
> 📝 docs: Add link to old releases in release notes

- CHANGELOG.md
- packages/docs/src/components/global/DocApi.vue
Correction d'un d'affichage sur l'API des composants.
> 🐛 docs: Fix display bug in DocApi

- CHANGELOG.md
- packages/docs/src/components/global/DocExample.vue
Correction de la gestion des erreurs dans le composant `DocExample` dans la documentation.
> 🐛 docs: Fix error handling in DoxExample

- CHANGELOG.md
- packages/docs/src/components/content-explorer/ContentExplorer.vue
- packages/docs/src/content/examples/guides/api/usage.vue
- packages/docs/src/content/guides/appels-api.md
Utilisation des enums dans le template des composants dans la documentation.
- Refactoring
> 🎨 docs: Use enums in components template

- CHANGELOG.md
- packages/vue-dot/src/functions/getFileExtension/index.ts
Correction d'une faute d'orthographe dans la fonction `getFileExtension`.
> 🐛 vue-dot: Fix typo in getFileExtension function

- CHANGELOG.md
- packages/docs/src/content/demarrer/notes-de-version.md
Ajout d'une information sur les notifications dans la page *Notes de version*.
> 📝 docs: Add notification information in release notes page

- .circleci/config.yml
- CHANGELOG.md
- package.json
- packages/design-tokens/scripts/build/generateJsFile.ts
- yarn.lock
Installation de netlify-cli en local.
- Maintenance
> 🔧 Install netlify-cli locally

- CHANGELOG.md
- packages/vue-dot/src/helpers/parseDate/index.ts
Correction du parsing de date dans le composant `DatePicker`.
<details>
```vue
<template>
<DatePicker outlined />
</template>
@Component
</script>
```
</details>
> 🐛 vue-dot: Fix date parsing in DatePicker

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/src/App.vue
Correction d'une mauvaise formulation dans le fichier `App.vue` dans le Starter Kit.
> 🐛 vue-dash: Fix wrong wording in App.vue

- CHANGELOG.md
- packages/design-tokens/tsconfig.json
- packages/vue-cli-plugin-vue-dash/generator/template/tests/e2e/tsconfig.json
- packages/vue-cli-plugin-vue-dash/generator/template/tsconfig.json
- tsconfig.json
Mise à jour des champs `lib` dans les fichiers `tsconfig.json`.
- Maintenance
> ♻️ Update lib fields in tsconfig.json files

- CHANGELOG.md
- packages/vue-dot/src/patterns/DataListGroup/tests/DataListGroup.spec.ts
- packages/vue-dot/src/patterns/DataListGroup/tests/__snapshots__/DataListGroup.spec.ts.snap
- packages/vue-dot/src/patterns/DataListGroup/tests/data/dataListGroupItems.ts
Ajout de tests pour le composant `DataListGroup`.
- Maintenance
> ✅ vue-dot: Add DataListGroup tests

- CHANGELOG.md
- packages/docs/src/components/DocHeader.vue
Correction de la valeur de la propriété `z-index` dans le composant `DocHeader`.
> 🐛 docs: Fix z-index in DocHeader

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/jest.config.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/App.vue
- packages/vue-cli-plugin-vue-dash/generator/template/src/router/routes.ts
- packages/vue-cli-plugin-vue-dash/generator/template/src/store/index.ts
Mise à jour des commentaires dans le Starter Kit.
- Refactoring
> ♻️ vue-dash: Update comments

- CHANGELOG.md
- packages/docs/src/data/api/header-bar.ts
- packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
- packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationBar/HeaderNavigationBar.vue
Ajout d'options de personnalisation dans le composant `HeaderBar`.
> ✨ vue-dot: Add more customization options in HeaderBar

- CHANGELOG.md
- packages/docs/src/content/composants/formulaires/upload-workflow.md
Correction de l'affichage du message de dépréciation dans la documentation du composant `UploadWorkflow`.
> 🐛 docs: Fix deprecation message in UploadWorkflow

- CHANGELOG.md
- packages/docs/src/data/examples/cookie-banner/options.vue
- packages/docs/src/data/examples/cookie-banner/slots.vue
- packages/docs/src/data/examples/cookie-banner/usage.vue
Correction des liens dans les exemples du composant `CookieBanner`.
> 🐛 docs: Fix links in CookieBanner examples

- CHANGELOG.md
- packages/docs/src/components/DocHeader.vue
- packages/docs/src/components/DocReleasesMenu.vue
- packages/docs/src/components/DocSearch.vue
Correction de l'affichage du menu de la documentation sur les écrans mobiles.
> 🐛 docs: Fix DocHeader on mobile

- CHANGELOG.md
- packages/docs/src/data/api/filter-module.ts
- packages/vue-dot/src/patterns/FilterModule/FilterModule.vue
- packages/vue-dot/src/patterns/FilterModule/config.ts
Correction de l'ordre du contenu dans le composant `FilterModule`.
Fixes #2164 
> 🐛 vue-dot: Fix content order in FilterModule

- CHANGELOG.md
- packages/docs/src/components/global/DocHomePageContributors.vue
- packages/docs/src/components/global/DocHomePageTeam.vue
- packages/docs/src/content/demarrer/introduction.md
Correction du contenu de la section *Équipe* de la page d'introduction.
> 🐛 docs: Fix team section content in introduction page

- CHANGELOG.md
- packages/docs/src/data/examples/notification-bar/options.vue
Correction de l'exemple `options` du composant `NotificationBar`.
> 🐛 docs: Fix NotificationBar options example

- CHANGELOG.md
- packages/docs/src/content/composants/formulaires/phone-field.md
- packages/docs/src/data/api/phone-field.ts
- packages/docs/src/data/drawerItems.ts
- packages/docs/src/data/examples/phone-field/required.vue
- packages/docs/src/data/examples/phone-field/usage.vue
- packages/vue-dot/src/patterns/NirField/types.d.ts
- packages/vue-dot/src/patterns/PhoneField/PhoneField.vue
- packages/vue-dot/src/patterns/PhoneField/config.ts
- packages/vue-dot/src/patterns/PhoneField/index.ts
- packages/vue-dot/src/patterns/PhoneField/locales.ts
- packages/vue-dot/src/patterns/PhoneField/tests/PhoneField.spec.ts
- packages/vue-dot/src/patterns/PhoneField/tests/__snapshots__/PhoneField.spec.ts.snap
- packages/vue-dot/src/patterns/index.ts
- packages/vue-dot/src/types.d.ts
- packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap
- packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap
- packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Ajout du composant `PhoneField`.
> ✨ vue-dot: Add PhoneField

- CHANGELOG.md
- packages/docs/src/content/guides/tests-e2e.md
- packages/docs/src/data/drawerItems.ts
Documentation des tests end to end
> 📝 docs: Add e2e tests guide

- CHANGELOG.md
- packages/docs/src/assets/styles/index.scss
- packages/docs/src/assets/styles/utilities.scss
- packages/docs/src/components/content-explorer/ContentExplorer.vue
- packages/docs/src/components/global/DocColorPalette.vue
- packages/docs/src/components/global/DocRoadmapItem.vue
- packages/docs/src/components/global/DocTabs.vue
- packages/docs/src/components/global/DocUsage.vue
Utilisation des classes de couleurs dans la documentation.
- Refactoring
> ♻️ docs: Use color classes

- CHANGELOG.md
- packages/docs/src/content/composants-techniques/types-utilitaires.md
- packages/docs/src/data/drawerItems.ts
Ajout de la page *Types utilitaires* dans la documentation.
> 📝 docs: Add utility types page

- CHANGELOG.md
- packages/vue-dot/package.json
Mise à jour des `peerDependencies`.
- Maintenance
> ⬆️ vue-dot: Upgrade peer dependencies

- CHANGELOG.md
- packages/form-builder/package.json
Mise à jour des `peerDependencies`.
- Maintenance
> ⬆️ form-builder: Upgrade peer dependencies

- CHANGELOG.md
- packages/docs/src/content/guides/gestion-textes.md
Mise à jour du guide sur la gestion des textes dans la documentation.
> ♻️ docs: Update i18n guide

- CHANGELOG.md
- packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
Correction des options de personnalisation dans le composant `HeaderBar`.
> 🐛 vue-dot: Fix Vuetify options binding in HeaderBar

- CHANGELOG.md
- packages/vue-dot/src/helpers/testUtils/tests/testUtils.spec.ts
Ajout d'un test sur la fonction `html` dans les fonctions utilitaires de test.
- Maintenance
> ✅ vue-dot: Add test for html function in testUtils

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/src/modules.d.ts
Correction de la déclaration du module `languages` manquante dans le Starter Kit.
> 🐛 vue-dash: Fix missing languages module declaration

- CHANGELOG.md
- packages/vue-dot/src/patterns/UploadWorkflow/mixins/uploadWorkflowCore.ts
Correction de la mise à jour différée de la liste des fichiers dans le composant `UploadWorkflow`.
> 🐛 vue-dot: Fix file list lazy update in UploadWorkflow

- packages/docs/src/content/fondamentaux/couleurs.md
add exemple for : Fondamentaux > Couleur
```vue
<template>
<div class="am-blue">
<p class="am-blue-lighten-97--text">
Contenu
</p>
</div>
</template>
@Component
</script>
```
> ✨ docs: Add usage information in colors page

- CHANGELOG.md
- packages/vue-cli-plugin-vue-dash/generator/template/pipeline/front-dev.jenkinsfile
- packages/vue-cli-plugin-vue-dash/generator/template/pipeline/front-prod.jenkinsfile
- packages/vue-cli-plugin-vue-dash/generator/template/pipeline/front-rct.jenkinsfile
- packages/vue-cli-plugin-vue-dash/generator/template/pipeline/front-val.jenkinsfile
Correction de la configuration des Jenkins files dans le Starter Kit.
Fixes #2403 
> 🐛 vue-dash: Fix Jenkinsfiles config

- CHANGELOG.md
- packages/docs/src/components/global/DocApi.vue
- packages/docs/src/components/global/DocExample.vue
- packages/docs/src/components/global/DocUsage.vue
- packages/docs/src/components/global/ExampleError.vue
- packages/docs/src/components/global/VueFile.vue
- packages/docs/src/layouts/error.vue
Correction de la gestion des erreurs lors des chargements asynchrones dans la documentation.
> 🐛 docs: Fix async loading error handling

- CHANGELOG.md
- package.json
- yarn.lock
Annulation de la mise à jour de TypeScript vers la `4.9.3` car cela casse le chargement asynchrone des exemples dans la documentation.
- Maintenance
> ⏪️ revert: Update dependency typescript to v4.9.3

- CHANGELOG.md
- packages/docs/src/components/global/DocHomePageTeam.vue
Mise à jour de l'équipe dans la page introduction dans la documentation.
- Maintenance
> ♻️ docs: Update team in introduction page

- packages/docs/src/content/composants/feedback/header-loading.md
Fix header)loading component on doc
> Doc : fix header loading component

- packages/docs/src/content/templates/error-page.md
- packages/docs/src/data/examples/error-page/usage.vue
- packages/docs/src/data/examples/notfound-page/code.vue
> Feat/#2416 Doc: NotFoundPage > add 500 error page exemple

- packages/docs/src/content/composants/feedback/rating-picker.md
- packages/docs/src/data/api/rating-picker.ts
- packages/docs/src/data/examples/rating-picker/close-buttons.vue
- packages/docs/src/data/examples/rating-picker/datas.vue
- packages/docs/src/data/examples/rating-picker/emotions-2.vue
- packages/docs/src/data/examples/rating-picker/emotions-labels.vue
- packages/docs/src/data/examples/rating-picker/emotions-second-step.vue
- packages/docs/src/data/examples/rating-picker/emotions.vue
- packages/docs/src/data/examples/rating-picker/green-background.vue
- packages/docs/src/data/examples/rating-picker/multi-answer-others.vue
- packages/docs/src/data/examples/rating-picker/multi-answer.vue
- packages/docs/src/data/examples/rating-picker/multi-questions.vue
- packages/docs/src/data/examples/rating-picker/numbers.vue
- packages/docs/src/data/examples/rating-picker/shadow-mode.vue
- packages/docs/src/data/examples/rating-picker/stars.vue
- packages/docs/src/data/examples/rating-picker/text-area.vue
- packages/vue-dot/src/patterns/RatingPicker/EmotionPicker/EmotionPicker.vue
- packages/vue-dot/src/patterns/RatingPicker/RatingPicker.vue
<details>
```vue
<template>
{{ datas }}
<RatingPicker
v-model="datas"
:main-question="firstQuestion"
:questions-list="questionsList"
:after-validate="afterValidate"
modal-mode
validate-text-button="Bonsoir"
@on-validate="onValidate"
@on-close="onClose"
@after-first-question="afterFirstQuestion"
/>
</template>
import RatingPicker from '../src/patterns/RatingPicker';
@Component({
components: {
RatingPicker
}
})
datas = [];
firstQuestion = {
name: 'first-step',
type: 'numbers',
labels: ['debut', 'apres'],
question: 'la premiere question ?'
};
questionsList = [
{
name: 'first-question',
type: 'emotions',
question: 'la deuxieme …
```
> Fix #2523 : Component > Avis : add last changes

- packages/docs/src/content/composants/feedback/accessibility-banner.md
- packages/docs/src/data/api/accessibility-banner.ts
- packages/docs/src/data/drawerItems.ts
- packages/docs/src/data/examples/accessibility-banner/options.vue
- packages/docs/src/data/examples/accessibility-banner/usage.vue
- packages/docs/src/data/examples/error-page/usage.vue
- packages/vue-dot/src/patterns/AccessibilityBanner/AccessibilityBanner.vue
- packages/vue-dot/src/patterns/AccessibilityBanner/config.ts
- packages/vue-dot/src/patterns/AccessibilityBanner/index.ts
- packages/vue-dot/src/patterns/AccessibilityBanner/locales.ts
- packages/vue-dot/src/patterns/AccessibilityBanner/tests/AccessibilityBanner.spec.ts
- packages/vue-dot/src/patterns/AccessibilityBanner/tests/__snapshots__/AccessibilityBanner.spec.ts.snap
Lien d'évitement pour l'accessibilité (ex. mon espace santé)
<details>
```vue
<template>
<div class="d-flex flex-wrap align-center justify-center">
<AccessibilityBanner
v-if="active"
accessibility-route="#main"
@reject="active = false"
@accept="active = false"
/>
<VBtn
v-if="!active"
class="text-none"
@click="active = true"
>
Réinitialiser
</VBtn>
</div>
</template>
import AccessibilityBanner from '../../vue-dot/src/patterns/AccessibilityBanner';
@Component({
components: {
AccessibilityBanner
}
})
export default class AccessibilityBannerUsage extends Vue {
active = true;
}
</script>
```
</details>
- Ce changement nécessite une mise à jour de la …
> Feat/#2267 Lien d'évitement

- packages/vue-dot/src/styles/variables.scss
Fixes #2485.
<details>
```vue
```
</details>
- Refactoring
- Maintenance
> 🐛 vue-dot: Fix letter-spacing

- packages/docs/src/content/templates/error-page.md
- packages/docs/src/data/drawerItems.ts
Fix le menu de la doc ou certains composants n'apparaissent plus.
> 🐛 docs: Fix menu

- packages/docs/src/vuetify.options.ts
- packages/vue-dot/dev/vuetify.ts
Desactivate custom properties options in Vuetify
> 🐛 docs: Disable custom properties option in Vuetify

- package.json
- packages/docs/package.json
- yarn.lock
Ces mises à jour causes des problèmes lors du build et lors du chargement des exemples.
> ⏪️ Revert nuxt & typescript upgrade

- packages/docs/src/data/drawerItems.ts
Ajout du menu Couleurs dans la doc
> 🐛 docs: Fix navigation drawer

- packages/docs/src/content/guides/tests-unitaires.md
> ✏️ docs: Fix typo in unit tests guide

- packages/docs/src/components/global/DocHomePageHeader.vue
- packages/docs/src/components/global/DocHomePageTeam.vue
- packages/docs/src/components/page/DocGithubLink.vue
- packages/docs/src/pages/_.vue
Suite à la PR #2620, les styles des titres de la documentation ont été légèrement modifiés.
> 🐛 docs: Fix typo styles

- packages/vue-dot/src/patterns/FooterBar/FooterBar.vue
> 🐛 vue-dot: Fix go top button in FooterBar

- packages/docs/src/components/drawer/DocDrawerListGroup.vue
- packages/docs/src/components/drawer/DocDrawerListItem.vue
- packages/docs/src/components/global/DocExample.vue
- packages/docs/src/data/api/back-to-top-btn.ts
- packages/docs/src/data/examples/back-to-top-btn/options.vue
- packages/docs/src/data/examples/back-to-top-btn/usage.vue
> 🐛 docs: Fix missing scoped attributes

- packages/vue-dot/package.json
- packages/vue-dot/src/patterns/FooterBar/CollapsibleList/types.d.ts
ameliorer la qual 
- Refactoring
> 🔧 vue-dot: Update lint configuration

- packages/vue-dot/src/templates/MaintenancePage/MaintenancePage.vue
- packages/vue-dot/src/templates/MaintenancePage/tests/__snapshots__/MaintenancePage.spec.ts.snap
- packages/vue-dot/src/templates/NotFoundPage/NotFoundPage.vue
- packages/vue-dot/src/templates/NotFoundPage/tests/__snapshots__/NotFoundPage.spec.ts.snap
Fix title classes on MaintenancePage and NotFoundPage
> 🐛 vue-dot: Fix title in MaintenancePage and NotFoundPage

- .github/release.yml
proposition de generation automatique de release notes 
> 🔧 Configure GitHub release notes

- packages/docs/src/content/composants/formulaires/nir-field.md
- packages/docs/src/content/composants/formulaires/phone-field.md
- packages/docs/src/content/composants/navigation/external-links.md
- packages/docs/src/content/composants/tableaux/filter-module.md
Corrections des exemples avec la mauvaise structure dans la documentation.
> 🐛 docs: Fix examples with wrong structure

- packages/vue-dot/src/elements/Logo/locales.ts
- packages/vue-dot/src/elements/Logo/tests/__snapshots__/Logo.spec.ts.snap
Correction d'une faute dans la description du logo.
> 🐛 vue-dot: Fix typo in alt text in Logo

- packages/docs/src/data/api/footer-bar.ts
- packages/docs/src/data/examples/footer-bar/collapsible-list.vue
- packages/vue-dot/src/patterns/FooterBar/CollapsibleList/CollapsibleList.vue
- packages/vue-dot/src/patterns/FooterBar/CollapsibleList/tests/CollapsibleList.spec.ts
- packages/vue-dot/src/patterns/FooterBar/CollapsibleList/tests/__snapshots__/CollapsibleList.spec.ts.snap
- packages/vue-dot/src/patterns/FooterBar/CollapsibleList/types.d.ts
Fixes #2732 
L'espacement dans le slot est corrigé dans la PR #2725.
<details>
```vue
<template>
<FooterBar v-bind="docProps">
<VRow
:no-gutters="$vuetify.breakpoint.xs"
class="max-width-none"
>
<VCol
cols="12"
sm="6"
>
<CollapsibleList
:items="remboursementItems"
list-title="Remboursement"
/>
</VCol>
<VCol
cols="12"
sm="6"
>
<CollapsibleList
:items="healthItems"
list-title="Santé"
/>
</VCol>
</VRow>
</FooterBar>
</template>
import CollapsibleList from '../src/patterns/FooterBar/CollapsibleList';
import { ListItem } from '../src/patterns/FooterBar/CollapsibleList/types';
@Component ({
components: {
CollapsibleList
}
})
docProps = {
sitemapRoute: '/', …
```
> ♻️ vue-dot: Refactor CollapsibleList

- packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
Correction suite à la mise à jour du composant `FilePreview`.
> 🐛 vue-dot: Fix FilePreview options binding in UploadWorkflow

- packages/docs/src/content/composants/formulaires/form-field.md
Correction d'une faute d'orthographe dans un exemple du composant `FormField`.
> 🐛 docs: Fix typo in FormField example

- packages/docs/src/content/composants-techniques/regles-de-validation/match-pattern.md
- packages/docs/src/data/api/rules/match-pattern.ts
- packages/docs/src/data/drawerItems.ts
- packages/vue-dot/src/rules/matchPattern/index.ts
- packages/vue-dot/src/rules/matchPattern/locales.ts
- packages/vue-dot/src/rules/matchPattern/tests/matchPattern.spec.ts
Ajouter la règle de validation matchPatternFn, déjà présente dans le projet Refonte Adher en interne.
> ✨ vue-dot: Add matchPattern rule

- packages/docs/src/content/guides/tests-unitaires.md
Ajouter un exemple de test d'une méthode de composant dans le guide sur les tests unitaires.
> 📝 docs: Add method & event unit tests examples

- CHANGELOG.md
Correction des liens cassés dans le fichier Changelog.
> 📝 Fix broken links in CHANGELOG

- packages/docs/src/data/api/user-menu-btn.ts
- packages/docs/src/data/examples/user-menu-btn/usage.vue
- packages/vue-dot/src/elements/UserMenuBtn/UserMenuBtn.vue
- packages/vue-dot/src/elements/UserMenuBtn/config.ts
- packages/vue-dot/src/elements/UserMenuBtn/tests/__snapshots__/UserMenuBtn.spec.ts.snap
Ajouter la prop mobile-version au composant UserMenuBtn #2616
<details>
```vue
<template>
<div>
<UserMenuBtn
full-name="Édith Cartier"
>
<VListItem
v-for="(item, index) in items"
:key="index"
>
<VListItemTitle>{{ item }}</VListItemTitle>
</VListItem>
</UserMenuBtn>
<br>
<UserMenuBtn
full-name="Édith Cartier"
mobile-version
>
<VListItem
v-for="(item, index) in items"
:key="index"
>
<VListItemTitle>{{ item }}</VListItemTitle>
</VListItem>
</UserMenuBtn>
</div>
</template>
@Component
export default class UserMenuBtnDefaultSlot extends Vue {
items = [
'Administration',
'Profil',
'Paramètres'
];
vuetifyOptions = {
menu: {
left: false,
right: true
}
};
}
</script>
``` …
> ✨ vue-dot: Add mobile-version prop in UserMenuBtn

- packages/vue-dot/src/styles/vuetify.scss
> 🐛 vue-dot: Fix VOverlay color

- packages/vue-dot/src/styles/v-alert.scss
> 🐛 vue-dot: Fix info VAlert colors

- packages/vue-dot/src/patterns/UploadWorkflow/tests/UploadWorkflow.spec.ts
- packages/vue-dot/src/patterns/UploadWorkflow/tests/__snapshots__/UploadWorkflow.spec.ts.snap
> 🐛 vue-dot: Fix UploadWorkflow tests

- packages/vue-cli-plugin-vue-dash/generator/template/public/css/fonts.css
Fixes [#3026](https://github.com/assurance-maladie-digital/design-system/issues/3026)
> 🐛 vue-dash: Fix font declaration in template

- packages/vue-cli-plugin-vue-dash/vueDotLoader.js
Fixes [#3019](https://github.com/assurance-maladie-digital/design-system/issues/3019)
> 🐛 vue-dash: Add missing component in vueDotLoader

- packages/docs/src/data/examples/skip-link/usage.vue
- packages/vue-dot/src/elements/SkipLink/SkipLink.vue
- packages/vue-dot/src/elements/SkipLink/tests/__snapshots__/SkipLink.spec.ts.snap
- packages/vue-dot/src/styles/components.scss
Fixes [#3027](https://github.com/assurance-maladie-digital/design-system/issues/3027)
> 🐛 vue-dot: Fix SkipLink with HeaderBar

- packages/docs/src/content/composants-techniques/helpers/scroll-behavior.md
- packages/docs/src/content/composants-techniques/helpers/test-utils.md
- packages/docs/src/content/guides/authentification-token.md
- packages/docs/src/content/guides/nouvelle-page.md
- packages/docs/src/content/guides/sous-chemin.md
- packages/docs/src/data/drawerItems.ts
Ajout d'un guide sur la configuration d'un sous-chemin personnalisé.
> 📝 docs: Add custom sub-path guide

- packages/docs/src/data/api/footer-bar.ts
- packages/docs/src/data/examples/footer-bar/link-items.vue
- packages/vue-dot/src/patterns/FooterBar/FooterBar.vue
- packages/vue-dot/src/patterns/FooterBar/types.d.ts
Fixes #3018
<details>
```vue
<template>
<FooterBar :link-items="linkItems" />
</template>
import { LinkItem } from '@cnamts/vue-dot/src/patterns/FooterBar/types';
@Component
linkItems: LinkItem[] = [
{
text: 'Accueil',
to: '/'
},
{
text: 'Conditions générales d’utilisation',
to: '/'
},
{
text: 'Mentions légales',
to: '/'
},
{
text: 'Gestion des cookies',
to: '/'
},
{
text: 'Accessibilité : non conforme',
to: '/'
},
{
text: 'Plan du site',
to: '/',
ariaLabel: 'Plan du site'
},
{
text: 'Aide',
href: 'https://www.ameli.fr/assure/aide',
ariaLabel: 'Aide (s’ouvre sur le site ameli.fr)',
openInNewTab: true
}
];
}
</script>
```
</details> …
> ✨ vue-dot: Add openInNewTab property to FooterBar items

- packages/vue-dot/package.json
Correction d'une dépendance manquante.
> 🐛 vue-dot: Fix missing dependency

- packages/vue-dot/src/patterns/PeriodField/PeriodField.vue
- packages/vue-dot/src/patterns/PeriodField/locales.ts
Fixes [#2997](https://github.com/assurance-maladie-digital/design-system/issues/2997)
> ✨ vue-dot: Add validation on PeriodField

- packages/vue-dot/src/patterns/NotificationBar/NotificationBar.vue
Alignement avec les icônes du composant `AlertWrapper`.
> 🐛 vue-dot: Fix error icon in NotificationBar

- packages/synapse-bridge/dev/main.ts
- packages/synapse-bridge/package.json
- packages/synapse-bridge/src/elements/CopyBtn/CopyBtn.vue
- packages/synapse-bridge/src/elements/CopyBtn/config.ts
- packages/synapse-bridge/src/elements/CopyBtn/index.ts
- packages/synapse-bridge/src/elements/CopyBtn/locales.ts
- packages/synapse-bridge/src/functions/copyToClipboard.ts
- packages/synapse-bridge/src/mixins/customizable.ts
- packages/synapse-bridge/src/mixins/types.d.ts
- pnpm-lock.yaml
```vue
import CopyBtn from '../src/elements/CopyBtn'
import { mdiContentDuplicate } from '@mdi/js'
const vuetifyOptions = {
menu: {
location: 'bottom center',
offset: 2
},
btn: {
density: 'default'
},
icon: {
color: 'indigo'
}
}
</script>
<template>
<div class="ma-4">
<CopyBtn
label="Copier le numéro de dossier"
:text-to-copy="() => 'example-1'"
/>
<CopyBtn
label="Copier le numéro de dossier"
text-to-copy="example-2"
/>
<CopyBtn
label="Copier le numéro de patient"
text-to-copy="example-3"
hide-tooltip
/>
<CopyBtn
:tooltip-duration="5000"
label="Copier le numéro de patient"
text-to-copy="example-4"
/>
<CopyBtn
label="Copier le numéro de ticket"
text-to-copy="example-6"
>
<template #icon>
<VIcon>
{{ mdiContentDuplicate }}
</VIcon>
</template>
<template #tooltip>
Le …
```
> ✨ Add CopyBtn component

- packages/synapse-bridge/src/elements/PageContainer/PageContainer.vue
- packages/synapse-bridge/src/elements/PageContainer/SizeEnum.ts
- packages/synapse-bridge/src/elements/PageContainer/index.ts
- packages/synapse-bridge/src/helpers/propValidator/index.ts
Add PageContainer component
<details>
```vue
<template>
<VCard class="pa-8">
Contenu de la page.
</VCard>
</template>
import PageContainer from '../src/elements/PageContainer'
</script>
```
</details>
- Refactoring
> PageContainer component

- packages/synapse-bridge/babel.config.cjs
- packages/synapse-bridge/dev/exemples/BackBtn.vue
- packages/synapse-bridge/dev/exemples/CopyBtn.vue
- packages/synapse-bridge/dev/exemples/PageContainer.vue
- packages/synapse-bridge/jest.config.ts
- packages/synapse-bridge/src/elements/BackBtn/index.ts
- packages/synapse-bridge/src/elements/BackBtn/tests/BackBtn.spec.ts
- packages/synapse-bridge/src/elements/BackBtn/tests/__snapshots__/BackBtn.spec.ts.snap
- packages/synapse-bridge/src/elements/CopyBtn/CopyBtn.vue
- packages/synapse-bridge/src/elements/CopyBtn/index.ts
- packages/synapse-bridge/src/elements/PageContainer/index.ts
- packages/synapse-bridge/src/elements/PageContainer/tests/PageContainer.spec.ts
- packages/synapse-bridge/src/helpers/propValidator/tests/propValidator.spec.ts
- packages/synapse-bridge/src/shims-vue.d.ts
- packages/synapse-bridge/tsconfig.json
Add missing tests
- Refactoring
> Add missing tests + change jest config

- packages/synapse-bridge/dev/exemples/BackBtn.vue
- packages/synapse-bridge/dev/exemples/BackToTopBtn.vue
- packages/synapse-bridge/dev/exemples/CopyBtn.vue
- packages/synapse-bridge/dev/exemples/PageContainer.vue
- packages/synapse-bridge/jest.config.ts
- packages/synapse-bridge/package.json
- packages/synapse-bridge/src/elements/BackToTopBtn/BackToTopBtn.vue
- packages/synapse-bridge/src/elements/BackToTopBtn/config.ts
- packages/synapse-bridge/src/elements/BackToTopBtn/index.ts
- packages/synapse-bridge/src/elements/BackToTopBtn/locales.ts
- packages/synapse-bridge/src/elements/BackToTopBtn/tests/BackToTopBtn.spec.ts
- packages/synapse-bridge/src/helpers/convertToUnit/index.ts
- packages/synapse-bridge/src/helpers/convertToUnit/test/convertToUnit.spec.ts
- packages/synapse-bridge/tsconfig.json
- packages/synapse-bridge/vite.config.ts
- packages/synapse-bridge/yarn.lock
> add BackToTop component + update examples

- packages/eslint-config-vue/package.json
- yarn.lock
> ⬇️ Revert dependency @vue/eslint-config-typescript update to v12

- packages/docs/src/data/api/alert-wrapper.ts
- packages/vue-dot/src/patterns/AlertWrapper/AlertWrapper.vue
> 🐛 vue-dot: Fix missing icon slot in AlertWrapper

- packages/vue-dot/src/elements/FileList/config.ts
- packages/vue-dot/src/elements/FileList/tests/__snapshots__/FileList.spec.ts.snap
- packages/vue-dot/src/patterns/FileUpload/FileUpload.vue
- packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
- packages/vue-dot/src/patterns/UploadWorkflow/tests/__snapshots__/UploadWorkflow.spec.ts.snap
> 🐛 vue-dot: Fix backgroud color of UploadWorkflow

- packages/vue-dot/src/patterns/AlertWrapper/AlertWrapper.vue
> 🐛 vue-dot: Fix mobile breakpoint in AlertWrapper

- packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
> 🐛 vue-dot: Fix mobile breakpoint in HeaderBar

- packages/docs/src/data/examples/back-btn/dark.vue
- packages/docs/src/data/examples/custom-icon/label.vue
> 📝 docs: Remove unseless script tags in examples

- packages/synapse-bridge/dev/main.ts
- packages/synapse-bridge/package.json
- packages/synapse-bridge/src/elements/BackBtn/tests/BackBtn.spec.ts
- packages/synapse-bridge/src/elements/BackToTopBtn/BackToTopBtn.vue
- packages/synapse-bridge/src/elements/BackToTopBtn/tests/BackToTopBtn.spec.ts
- packages/synapse-bridge/src/elements/CopyBtn/CopyBtn.vue
- packages/synapse-bridge/src/elements/CopyBtn/tests/CopyBtn.spec.ts
- packages/synapse-bridge/src/elements/PageContainer/PageContainer.vue
- packages/synapse-bridge/src/elements/PageContainer/tests/PageContainer.spec.ts
- packages/synapse-bridge/src/elements/index.ts
- packages/synapse-bridge/src/main.ts
- packages/synapse-bridge/src/mixins/customizable/types.d.ts
- packages/synapse-bridge/src/types.d.ts
- packages/synapse-bridge/src/vite-env.d.ts
- packages/synapse-bridge/tsconfig.json
- packages/synapse-bridge/tsconfig.node.json
- packages/synapse-bridge/vite.config.ts
- packages/synapse-bridge/vitest.config.ts
- pnpm-lock.yaml
- tsconfig.json
- Configuration du build
- Séparation de la configuration de Vitest dans un fichier dédié
- Ajout de la commande `analyze`
- Complétion du `package.json`
- Ajout des alias `@` et `@tests`
- Ajout d'un `tsconfig.json` à la racine
> 🔧 Setup packaging

- packages/synapse-bridge/src/styles/settings.scss
> 💄 Configure Vuetify variables

- packages/vue-dot/src/mixins/filterable/index.ts
- packages/vue-dot/src/patterns/FiltersInline/FiltersInline.vue
Add emits events on component
<details>
```vue
<template>
<FiltersInline
v-model="filters"
@update:value="handleFilterUpdate"
>
<template #name="{ on, attrs }">
<VTextField
v-bind="attrs"
label="Nom"
outlined
hide-details
v-on="on"
/>
</template>
<template #folder="{ on, attrs }">
<p class="text--secondary">
Vous pouvez filtrer entre les dossiers de type <b>Arrêt de Travail (AT)</b> et <b>Maladie Professionnelle (MP)</b> ou <b>Autre</b>.
</p>
<VSelect
v-bind="attrs"
:items="folderTypes"
label="Type de dossier"
multiple
outlined
return-object
hide-details
v-on="on"
/>
</template>
<template #period="{ on, attrs }">
<PeriodField
v-bind="attrs"
outlined
v-on="on"
/>
</template>
<template #profession="{ on, attrs }">
<SearchListField
v-bind="attrs"
:items="professionList"
v-on="on"
/> …
```
> FiltersInline Events

- packages/docs/src/content/composants/structure/header-bar.md
- packages/docs/src/content/fondamentaux/logo.md
Fix doc for HeaderBar and secondary logo use.
> 📝 vue-dot: Add information on slots in HeaderBar & Logo

- packages/vue-dot/src/elements/FileList/FileList.vue
- packages/vue-dot/src/elements/FileList/tests/__snapshots__/FileList.spec.ts.snap
- packages/vue-dot/src/styles/vuetify.scss
fix success color accessibility in FileList
> ♿️ vue-dot: Fix success icon color in FileList

- packages/docs/src/data/api/rating-picker.ts
Ajout d'une précision dans la partie api du composant sur l'usage du slot par défaut.
> 📝docs: Add note on default slot in RatingPicker

- packages/docs/src/data/api/file-list.ts
- packages/vue-dot/src/elements/FileList/FileList.vue
hide delete action if needed
<details>
```vue
<template>
<FileList
:files="fileList"
show-view-btn
hide-delete-btn
/>
</template>
import { FileItem } from '@cnamts/vue-dot/src/elements/FileList/types';
@Component
export default class FileListStates extends Vue {
fileList: FileItem[] = [
{
title: 'RIB',
name: 'rib.pdf',
state: 'success'
},
{
title: 'Carte d’identité recto / verso',
name: 'carte-identite.jpg',
state: 'success'
},
{
title: 'Passport',
name: 'passport.jpg',
state: 'error'
}
];
}
</script>
```
</details>
- Refactoring
- Maintenance
> ✨ vue-dot: Add hide-delete-btn in FileList

- packages/docs/src/content/composants/navigation/contextual-menu.md
Documenter la confuguration de vue-router necessaire pour faire fonctiooner le scroll vers les ancres.
> 📝 docs: Add note on router config in ContextualMenu

- packages/docs/src/data/api/chip-list.ts
Mettre à jour le type 'ChipItem'
> 📝 docs: Fix ChipItem type

- packages/docs/src/data/api/file-list.ts
Corriger dans la documentation le type des valeurs retournés par les evenements du composant FileList et ajout de l'évenement `upload` manquant.
> 📝 docs: Fix FileList events params

- packages/docs/src/data/api/header-bar.ts
Indiquer quand un slot est écrasé par un autre slot.
Préciser le type de la props `homeLink`
> 📝 docs: Add more details on slots in HeaderBar

- packages/docs/src/data/api/shared/mixins/filterable.ts
- packages/vue-dot/src/mixins/filterable/index.ts
- packages/vue-dot/src/mixins/filterable/types.d.ts
Complète le type 'FilterItem' dans l'interface et la documentation avec la propriété 'title' tel qu'utilisé.
Amélioration des typages dans la mixin "filterable" avec les dernières possibilité de typescript
</details>
- Maintenance
> 🐛 vue-dot: Fix FilterItem type in filterable mixin

- packages/docs/src/data/api/file-list.ts
- packages/docs/src/data/api/upload-workflow.ts
- packages/vue-dot/src/elements/FileList/FileList.vue
- packages/vue-dot/src/patterns/FileUpload/FileUpload.vue
- packages/vue-dot/src/patterns/FileUpload/locales.ts
- packages/vue-dot/src/patterns/FileUpload/tests/FileUpload.spec.ts
- packages/vue-dot/src/patterns/FileUpload/tests/__snapshots__/FileUpload.spec.ts.snap
- packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
- packages/vue-dot/src/patterns/UploadWorkflow/mixins/tests/uploadWorkflowCore.spec.ts
- packages/vue-dot/src/patterns/UploadWorkflow/mixins/uploadWorkflowCore.ts
- packages/vue-dot/src/patterns/UploadWorkflow/tests/UploadWorkflow.spec.ts
- packages/vue-dot/src/patterns/UploadWorkflow/tests/__snapshots__/UploadWorkflow.spec.ts.snap
Fixes #3353 
<details>
```vue
<template>
<div>
v-model="files"
multiple
/>
v-model="selectedFiles"
:file-list-items="fileListItems"
/>
v-model="selectedFile"
:file-list-items="singleFileListItem"
/>
<UploadWorkflow v-model="retrocompatibility" />
</div>
</template>
import { FileListItem, SelectedFile } from '@cnamts/vue-dot/src/patterns/UploadWorkflow/types';
@Component
files: File[] = [];
selectedFiles: SelectedFile[] = [];
fileListItems: FileListItem[] = [
{
id: 'rib',
title: 'RIB'
},
{
id: 'idCard',
title: 'Carte d’identité recto / verso'
},
{
id: 'passport',
title: 'Passeport'
}
];
selectedFile: …
```
> 🐛 vue-dot: Fix unrestricted mode in UploadWorkflow

- packages/vue-dot/src/patterns/AlertWrapper/AlertWrapper.vue
Fix AlertWrapper alert icon + icon slot display
<details>
```vue
<template>
<div>
<AlertWrapper
v-model="alert"
dismissible
outlined
type="warning"
class="mb-0"
>
Il semble qu’une date de naissance erronée a été saisie, renseignez-vous auprès du centre qui vous a vacciné.
</AlertWrapper>
<VBtn
v-if="!alert"
@click="alert = true"
>
Réinitialiser
</VBtn>
<AlertWrapper
v-model="alert"
dismissible
outlined
type="warning"
class="mb-0"
>
<template #icon>
{{ timerOffIcon }}
</template>
Il semble qu’une date de naissance erronée a été saisie, renseignez-vous auprès du centre qui vous a vacciné.
</AlertWrapper>
</div>
</template>
import { mdiTimerOffOutline } from '@mdi/js';
@Component
export …
```
> 🐛 vue-dot: Fix alert icon & icon slot in AlertWrapper

- packages/docs/src/content/composants/formulaires/upload-workflow.md
- packages/docs/src/data/api/upload-workflow.ts
- packages/docs/src/data/examples/upload-workflow/view-file.vue
- packages/vue-dot/src/patterns/DatePicker/mixins/tests/dateLogic.spec.ts
- packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
- packages/vue-dot/src/patterns/UploadWorkflow/config.ts
- packages/vue-dot/src/patterns/UploadWorkflow/mixins/tests/uploadWorkflowCore.spec.ts
- packages/vue-dot/src/patterns/UploadWorkflow/mixins/uploadWorkflowCore.ts
- packages/vue-dot/src/patterns/UploadWorkflow/tests/__snapshots__/UploadWorkflow.spec.ts.snap
Fixes #3367
<details>
```vue
<template>
<div>
v-model="selectedFiles"
:file-list-items="fileListItems"
@view-file="showFileInfo"
/>
<DialogBox
v-if="displayedFile"
:title="displayedFile.title"
>
<template #default>
Vous avez sélectionné le fichier <b>{{ displayedFile.name }}</b>.
</template>
<template #actions>
<VBtn
@click="dialog = false"
>
Retour
</VBtn>
</template>
</DialogBox>
<VDivider />
v-model="selectedFiles"
:file-list-items="fileListItems"
show-view-btn
@view-file="showFileInfo"
/>
</div>
</template>
import { FileListItem, SelectedFile } from '@cnamts/vue-dot/src/patterns/UploadWorkflow/types'; …
```
> ✨ vue-dot: Add show-view-btn prop to UploadWorkflow

- packages/synapse-bridge/vite.config.ts
Fix component import in SK Bridge
> 🐛 Fix Vuetify component import

- packages/synapse-bridge/src/elements/BackToTopBtn/BackToTopBtn.vue
- packages/synapse-bridge/src/elements/PageContainer/PageContainer.vue
- packages/synapse-bridge/src/patterns/CookieBanner/CookieBanner.vue
- packages/synapse-bridge/src/templates/ErrorPage/ErrorPage.vue
Changer l'utilisation de useDisplay pour que cela soit fonctionnel dans le SK. (correction de la perte de réactivité des ref retournées par un composable lors de leurs utilisations avec l'option api)
> Fix useDisplay use in components

- packages/synapse-bridge/src/elements/HeaderLoading/HeaderLoading.vue
- packages/synapse-bridge/src/patterns/SubHeader/SubHeader.vue
> Fix Skeleton build

- packages/synapse-bridge/src/types.d.ts
> Bridge: fix build errors

- packages/docs/src/data/api/select-btn-field.ts
- packages/vue-dot/src/patterns/SelectBtnField/SelectBtnField.vue
Ajout de la props readonly au composant SelectBtnField
<details>
```vue
@Component
export default class RatingPickerEmotion extends Vue {
rating = -1;
sended = false;
field = {
title: 'Comment avez-vous connu ce service ?',
items: [
{
text: 'Via une recherche internet',
value: 'internet'
},
{
text: 'Via un professionnel de santé',
value: 'professional'
},
{
text: 'Via un ami',
value: 'friend'
}
],
value: null,
type: 'choiceButton',
label: 'Le moyen par lequel vous avez connu ce service',
outlined: true,
readonly: false
}
}; // satisfies Field; // TS 4.9
sendRating(): void { …
```
> ✨ vue-dot: Add readonly prop in SelectBtnField

- packages/vue-dot/src/patterns/NirField/NirField.vue
- packages/vue-dot/src/patterns/NirField/locales.ts
- packages/vue-dot/src/patterns/NirField/tests/NirField.spec.ts
- packages/vue-dot/src/patterns/NirField/tests/__snapshots__/NirField.spec.ts.snap
Change l'affichage des erreurs pour la clé de validation
Supprime les icones
<details>
```vue
<template>
<NirField
v-model="nir"
:required="true"
outlined
/>
<br>
<NirField
v-model="nir"
:required="true"
/>
<br>
<NirField
v-model="nir"
:required="false"
outlined
/>
<br>
<NirField
v-model="nir"
:required="true"
outlined
/>
<br>
<NirField
v-model="nir"
:required="false"
tooltip="Tooltip"
/>
<br>
{{ nir }}
</template>
@Component({
components: {}
})
export default class FilePreviewUsage extends Vue {
log = (e: string): void => {
console.log(e);
};
nir = '';
tooltip = 'Tooltip';
}
</script>
```
</details>
> ♻️ vue-dot: Refactor error messages in NirField

- packages/synapse-bridge/package.json
- packages/synapse-bridge/src/patterns/PhoneField/PhoneField.vue
- packages/synapse-bridge/src/patterns/PhoneField/config.ts
- packages/synapse-bridge/src/patterns/PhoneField/index.ts
- packages/synapse-bridge/src/patterns/PhoneField/locales.ts
- packages/synapse-bridge/src/patterns/PhoneField/tests/PhoneField.spec.ts
- packages/synapse-bridge/src/patterns/PhoneField/tests/__snapshots__/PhoneField.spec.ts.snap
- packages/synapse-bridge/src/rules/exactLength/index.ts
- packages/synapse-bridge/src/rules/exactLength/locales.ts
- packages/synapse-bridge/src/rules/exactLength/tests/exactLength.spec.ts
- packages/synapse-bridge/src/types.d.ts
PhoneField
```vue
<template>
<PhoneField
v-model="phone1"
required
@update:modelValue="handleInputChange1"
/>
<br />
<PhoneField
v-model="phone2"
outlined
@update:modelValue="handleInputChange2"
/>
</template>
import PhoneField from "@/patterns/PhoneField/PhoneField.vue";
components: {
PhoneField,
PageContainer,
},
data() {
return {
phone1: undefined as string | undefined,
phone2: undefined as string | undefined,
};
},
methods: {
handleInputChange1() {
if (this.phone1) {
console.log(this.phone1);
}
},
handleInputChange2() {
if (this.phone2) {
console.log(this.phone2);
}
}
}
});
</script>
```
> PhoneField v3

- CHANGELOG.md
> Changelog 2.16.1

- packages/docs/src/content/composants/structure/header-bar.md
- packages/docs/src/data/api/header-bar.ts
- packages/docs/src/data/api/logo.ts
- packages/docs/src/data/examples/header-bar/ally.vue
- packages/vue-dot/src/elements/Logo/Logo.vue
- packages/vue-dot/src/elements/LogoBrandSection/LogoBrandSection.vue
- packages/vue-dot/src/elements/LogoBrandSection/locales.ts
- packages/vue-dot/src/elements/LogoBrandSection/tests/__snapshots__/LogoBrandSection.spec.ts.snap
- packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
Supprimer le bug d'affiuchage d'un attribut href sur une div et utilisation d'un seul aria-label sur un lien en accord avec cette documentation : https://www.accede-web.com/notices/html-et-css/images-et-icones/gerer-lalternative-des-svg-images-vectorielles/#ancre-04.
Ajout d'une props permettant de personnaliser la aria-label.
<details>
```vue
<template>
<VApp>
<HeaderBar
theme="compte-ameli"
home-href="https://duckduckgo.com/"
link-label="Accueil - DuckDuckGo"
/>
<HeaderBar
home-href="https://duckduckgo.com/"
/>
<HeaderBar
theme="compte-ameli"
to="home"
/>
</VApp>
</template>
import PageContainer from '../src/elements/PageContainer/PageContainer.vue';
import HeaderBar from …
```
> ♿️vue-dot: Add accessibility feature to header bar and logo

- packages/docs/src/data/examples/footer-bar/content-slots.vue
- packages/docs/src/data/examples/footer-bar/slots.vue
- packages/vue-dot/src/patterns/FooterBar/FooterBar.vue
- packages/vue-dot/src/patterns/FooterBar/SocialMediaLinks/SocialMediaLinks.vue
- packages/vue-dot/src/patterns/FooterBar/SocialMediaLinks/tests/__snapshots__/SocialMediaLinks.spec.ts.snap
- packages/vue-dot/src/patterns/FooterBar/tests/__snapshots__/FooterBar.spec.ts.snap
Utiliser des listes pour améliorer l'accessibilité
<details>
```vue
<template>
<VApp>
<FooterBar v-bind="docProps" />
<br><br>
<FooterBar v-bind="docProps">
<p class="text--secondary mb-0">
Contenu supplémentaire.
</p>
</FooterBar>
<br><br>
<FooterBar
v-bind="docProps"
hide-sitemap-link
>
<p class="text--secondary mb-0">
Contenu supplémentaire.
</p>
</FooterBar>
<br><br>
<FooterBar
v-bind="docProps"
class="theme--dark"
>
<VRow class="max-width-none">
<VCol
cols="12"
sm="6"
>
<CollapsibleList
:items="remboursementItems"
list-title="Remboursement"
class="theme--dark"
/>
</VCol>
<VCol
cols="12"
sm="6"
>
<CollapsibleList
:items="healthItems"
list-title="Santé"
class="theme--dark"
/>
</VCol>
</VRow>
</FooterBar>
</VApp>
</template>
import { …
```
> ♿️vue-dot: Refactor footer links to use unordered list

- packages/vue-dot/src/elements/LogoBrandSection/secondaryLogoMapping.ts
<details>
```vue
<template>
<HeaderBar
theme="compte-ameli"
inner-width="600px"
/>
</template>
@Component
export default class HeaderBarInnerWidth extends Vue {
{
},
{
},
{
}
];
}
</script>
```
</details>
- Refactoring
- Maintenance
> fix compte ameli logo alternative

- packages/docs/src/data/api/rating-picker.ts
- packages/vue-dot/src/patterns/RatingPicker/EmotionPicker/EmotionPicker.vue
- packages/vue-dot/src/patterns/RatingPicker/NumberPicker/NumberPicker.vue
- packages/vue-dot/src/patterns/RatingPicker/RatingMixin.ts
- packages/vue-dot/src/patterns/RatingPicker/RatingPicker.vue
- packages/vue-dot/src/patterns/RatingPicker/StarsPicker/StarsPicker.vue
Afin de permettre plus de personnalisation au niveau du label du ratingPicker, ajout d'un slot pour afficher cd label avec des balises HTML.
<details>
```vue
<template>
<div>
<RatingPicker
v-model="rating"
type="stars"
>
<template #label>
<h3 class="mb-0">
Êtes-vous satisfait de ce service ?
</h3>
</template>
<FormField
v-model="field"
class="mb-4"
/>
<div class="d-flex">
<VSpacer />
<VBtn
right
>
Terminé
</VBtn>
</div>
</RatingPicker>
<br>
<RatingPicker
v-model="rating2"
type="number"
>
<template #label>
<h3
style="all: inherit"
class="mb-0"
>
Êtes-vous satisfait de ce service ?
</h3>
</template>
<FormField
v-model="field"
class="mb-4"
/>
<div class="d-flex">
<VSpacer />
<VBtn
right
>
Terminé
</VBtn>
</div>
</RatingPicker>
<br>
<RatingPicker …
```
> ✨vue-dot: Add label slots in RatingPicker components

- packages/synapse-bridge/src/functions/formatNir/index.ts
- packages/synapse-bridge/src/functions/formatNir/tests/formatNir.spec.ts
- packages/synapse-bridge/src/patterns/NirField/NirField.vue
- packages/synapse-bridge/src/patterns/NirField/config.ts
- packages/synapse-bridge/src/patterns/NirField/index.ts
- packages/synapse-bridge/src/patterns/NirField/locales.ts
- packages/synapse-bridge/src/patterns/NirField/tests/NirField.spec.ts
- packages/synapse-bridge/src/patterns/NirField/tests/__snapshots__/NirField.spec.ts.snap
- packages/synapse-bridge/src/patterns/SelectBtnField/tests/__snapshots__/SelectBtnField.spec.ts.snap
- packages/synapse-bridge/src/styles/settings.scss
- packages/synapse-bridge/tsconfig.json
NirField
```vue
<template>
<v-row>
<v-col cols="6">
<NirField
outlined
required
tooltip="Tooltip infos"
/>
<NirField
required
tooltip="Tooltip infos"
/>
<NirField
tooltip="Tooltip infos"
/>
<NirField
@update:model-value="getValue"
/>
Value: {{ value }}
</v-col>
<v-col cols="6">
<NirField
required
tooltip="Tooltip infos"
outlined
/>
<NirField
required
tooltip="Tooltip infos"
/>
<NirField
tooltip="Tooltip infos"
/>
<NirField @update:model-value="getValue" />
<p>Value:{{ value }}</p>
</v-col>
</v-row>
</template>
import NirField from "@/patterns/NirField/NirField.vue";
import PageContainer from …
```
> NirField v3

- CHANGELOG.md
> Changelog 2.16.2

- packages/synapse-bridge/package.json
- packages/synapse-bridge/src/constants/index.ts
- packages/synapse-bridge/src/elements/DownloadBtn/ContentHeadersEnum.ts
- packages/synapse-bridge/src/elements/DownloadBtn/DownloadBtn.vue
- packages/synapse-bridge/src/elements/DownloadBtn/config.ts
- packages/synapse-bridge/src/elements/DownloadBtn/index.ts
- packages/synapse-bridge/src/elements/DownloadBtn/locales.ts
- packages/synapse-bridge/src/elements/DownloadBtn/tests/DownloadBtn.spec.ts
- packages/synapse-bridge/src/elements/DownloadBtn/tests/__snapshots__/DownloadBtn.spec.ts.snap
- packages/synapse-bridge/src/elements/DownloadBtn/tests/data/filePromise.ts
- packages/synapse-bridge/src/elements/DownloadBtn/types.d.ts
- packages/synapse-bridge/src/elements/index.ts
- packages/synapse-bridge/src/functions/downloadFile/index.ts
- packages/synapse-bridge/src/functions/downloadFile/tests/downloadFile.spec.ts
- packages/synapse-bridge/src/functions/downloadFile/types.d.ts
- packages/synapse-bridge/src/functions/formatDate/index.ts
- packages/synapse-bridge/src/functions/formatDate/tests/formatDate.spec.ts
- packages/synapse-bridge/src/patterns/FooterBar/SocialMediaLinks/tests/__snapshots__/SocialMediaLinks.spec.ts.snap
- packages/synapse-bridge/src/plugins/axios.ts
- packages/synapse-bridge/tests/unit/setup.ts
Add DownloadBtn component
```vue
<template>
<DownloadBtn
notification="Super !"
:file-promise="getFileFromApi"
:fallback-filename="fallbackFilename"
>
Télécharger mon attestation
</DownloadBtn>
<DownloadBtn
:file-promise="getFileFromApi"
:outlined="false"
tile
color="white"
width="396px"
class="text-primary"
>
<VIcon
color="grey"
class="flex-shrink-0 mr-2"
:class="{ 'd-none': $vuetify.display.smAndDown }"
>
{{ fileIcon }}
</VIcon>
justificatif.txt
<VSpacer class="ml-2" />
<VIcon
class="flex-shrink-0"
>
{{ downloadIcon }}
</VIcon>
</DownloadBtn>
<NotificationBar />
</template>
import DownloadBtn from "@/elements/DownloadBtn";
import NotificationBar from "@/patterns/NotificationBar"; …
```
> DownloadBtn v3

- packages/synapse-bridge/src/patterns/PasswordField/PasswordField.vue
- packages/synapse-bridge/src/patterns/PasswordField/config.ts
- packages/synapse-bridge/src/patterns/PasswordField/index.ts
- packages/synapse-bridge/src/patterns/PasswordField/locales.ts
- packages/synapse-bridge/src/patterns/PasswordField/tests/PasswordField.spec.ts
- packages/synapse-bridge/src/patterns/PasswordField/tests/__snapshots__/PasswordField.spec.ts.snap
PasswordField
```vue
<template>
<PasswordField
v-model="password"
@update:model-value="getValue($event)"
/>
<PasswordField
v-model="password"
required
outlined
@update:model-value="getValue($event)"
/>
</template>
import PasswordField from "@/patterns/PasswordField/PasswordField.vue";
components: {
PageContainer,
PasswordField,
},
data() {
return {
password: null as string | null
};
},
methods: {
getValue(value: string): void {
console.log(value);
}
}
});
</script>
```
> PasswordField v3

- packages/synapse-bridge/src/patterns/HeaderBar/HeaderBar.vue
- packages/synapse-bridge/src/patterns/HeaderBar/HeaderMenuBtn/config.ts
- packages/synapse-bridge/src/patterns/HeaderBar/config.ts
mettre la couleur du boutton en noir (supprimer la classe 'text-transparent'
<details>
```vue
<template>
<HeaderBar
service-title="Design System"
service-sub-title="Documentation du Design System"
mobile-version
/>
</template>
import HeaderBar from '../src/patterns/HeaderBar';
export default {
emits:['change'],
components: {
HeaderBar
},
data() {
return {
navigationItems: [
{
label: 'Error Page'
},
{
},
{
}
],
}
},
};
</script>
```
</details>
> mettre la couleur du boutton en noir

- packages/docs/src/components/global/DocMarkup.vue
- packages/docs/src/components/global/DocMigrationFaq.vue
- packages/docs/src/content/migration-bridge.md
- packages/docs/src/data/drawerItems.ts
guide de migration a destination des produits
</details>
> Documentation de migration

- packages/synapse-bridge/src/elements/CopyBtn/CopyBtn.vue
- packages/synapse-bridge/src/elements/CopyBtn/tests/__snapshots__/CopyBtn.spec.ts.snap
- packages/synapse-bridge/src/styles/settings.scss
Fix des transitions
<details>
```vue
<template>
<div>
<CopyBtn
label="Copier le numéro de patient"
text-to-copy="1970756541"
>
<VBtn>
btn
</VBtn>
</div>
</template>
<script>
import { defineComponent } from 'vue'
import CopyBtn from '../src/elements/CopyBtn'
name: 'Playground',
components: {
CopyBtn
}
})
</script>
```
</details>
> fix les transitions

- packages/synapse-bridge/src/patterns/NirField/NirField.vue
<details>
```vue
<template>
<v-row>
<v-col cols="6">
<NirField
outlined
required
tooltip="Tooltip infos"
/>
</v-col>
<v-col cols="6">
<NirField
required
tooltip="Tooltip infos"
outlined
/>
</v-col>
</v-row>
</template>
import NirField from "@/patterns/NirField/NirField.vue";
components: {
NirField,
PageContainer,
},
data() {
return {
value: "",
};
},
methods: {
getValue(event: string) {
this.value = event;
},
},
});
</script>
```
</details>
- Refactoring
- Maintenance
- Ce changement nécessite une …
> fix hasOwnProperty error

- packages/synapse-bridge/package.json
<details>
```vue
```
</details>
- Refactoring
- Maintenance
> add forgotten rules exports

- packages/docs/src/components/global/DocRoadmap.vue
- packages/docs/src/content/composants/formulaires/date-picker.md
- packages/docs/src/content/composants/formulaires/period-field.md
- packages/docs/src/data/api/date-picker-bridge.ts
- packages/docs/src/data/api/period-field-bridge.ts
> Bridge doc

- CHANGELOG.md
> Changelog 2.16.5

- packages/synapse-bridge/src/constants/index.ts
- packages/synapse-bridge/src/functions/validation/isDateAfter/index.ts
- packages/synapse-bridge/src/functions/validation/isDateBefore/index.ts
- packages/synapse-bridge/src/rules/notAfterToday/index.ts
- packages/synapse-bridge/src/rules/notBeforeDate/index.ts
- packages/synapse-bridge/src/rules/notBeforeToday/index.ts
<details>
```vue
```
</details>
- Refactoring
- Maintenance
> test export

- packages/synapse-bridge/src/elements/LogoBrandSection/secondaryLogoMapping.ts
<details>
```vue
```
</details>
- Refactoring
- Maintenance
> fix link to images

- packages/synapse-bridge/src/patterns/HeaderBar/HeaderBar.vue
<details>
```vue
```
</details>
- Refactoring
- Maintenance
> fix theme error on header

- packages/synapse-bridge/src/patterns/PasswordField/PasswordField.vue
- packages/synapse-bridge/src/patterns/PasswordField/tests/__snapshots__/PasswordField.spec.ts.snap
<details>
```vue
<template>
<PasswordField
v-model="password"
@update:model-value="getValue($event)"
/>
<PasswordField
v-model="password"
required
outlined
@update:model-value="getValue($event)"
/>
</template>
import PasswordField from "@/patterns/PasswordField/PasswordField.vue";
components: {
PageContainer,
PasswordField,
},
data() {
return {
password: null as string | null
};
},
methods: {
getValue(value: string): void {
console.log(value);
}
}
});
</script>
```
</details>
- Refactoring
- Maintenance
- Ce …
> fix icon with outlined props

- packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue
- packages/synapse-bridge/src/patterns/DatePicker/tests/DatePicker.spec.ts
<details>
```vue
```
</details>
- Refactoring
- Maintenance
> fix error on bad date

- packages/design-tokens/scripts/build/generateJsonFile.ts
- packages/design-tokens/scripts/build/generateScssFile.ts
- packages/design-tokens/scripts/build/index.ts
- packages/design-tokens/src/colors.ts
- packages/design-tokens/src/tokens.ts
- packages/design-tokens/src/types.d.ts
- packages/design-tokens/tests/tokens.spec.ts
> Add bootstrap tokens on build

- CHANGELOG.md
> Update changelog v2.16.6

- packages/synapse-bridge/src/patterns/NirField/NirField.vue
- packages/synapse-bridge/src/patterns/NirField/tests/NirField.spec.ts
- pnpm-lock.yaml
Fix de l'emit du nir field pour qu'il ai toujours lieu après le processing de maska
<details>
```vue
<template>
<div>
<NirField v-model="nirValue" @update:model-value='newValue'/>
{{ nirValue }}
<NirField v-model="nirValue2" @update:model-value='newValue' :nir-length='13'/>
{{ nirValue2 }}
</div>
</template>
const nirValue = ref('');
const nirValue2 = ref('');
nirValue.value = '12345678901234k';
nirValue2.value = '1234567890123';
}, 1000);
function newValue(value: string) {
console.log('newValue', value);
}
</script>
```
</details>
> Update NirField component to emit correct model value

- packages/synapse-bridge/src/patterns/FooterBar/FooterBar.vue
Fix dark theme
<details>
```vue
<template>
<VApp>
<FooterBar
:link-items="linkItems"
dark
/>
</VApp>
</template>
import PageContainer from '@/elements/PageContainer/PageContainer.vue';
import FooterBar from '@/patterns/FooterBar/FooterBar.vue';
components: {
PageContainer,
FooterBar
},
data () {
return {
linkItems: [
{
text: 'Accueil',
to: '/'
},
{
text: 'Conditions générales d’utilisation',
to: '/'
},
{
text: 'Mentions légales',
to: '/'
},
{
text: 'Gestion des cookies',
to: '/'
},
{
text: 'Accessibilité : non conforme',
to: '/'
},
{
text: 'Plan du site',
to: '/',
ariaLabel: 'Plan du site'
},
{
text: 'Aide',
href: 'https://www.ameli.fr/assure/aide',
ariaLabel: 'Aide …
```
> fix dark theme + style

- packages/synapse-bridge/src/patterns/NirField/NirField.vue
Description
Quand on saisit dans le NirField après une erreur de validation, pas de mise a jour avant de blur le champ
Comment reproduire
Dans un NirField en required :
Entrer la valeur "1"
quitter le champ
Message d'erreur s'affiche
Reselectionner le champ et ajouter "234567891011" pour faire 13 chiffres
Le message d'erreur est encore présent
<details>
```vue
<template>
<div>
<NirField v-model="nirValue" @update:model-value='newValue'/>
{{ nirValue }}
<NirField v-model="nirValue2" @update:model-value='newValue' :nir-length='13'/>
{{ nirValue2 }}
</div>
</template>
const nirValue = ref('');
const nirValue2 = ref('');
nirValue.value = '12345678901234k';
nirValue2.value = …
```
> fix issue 3540

- packages/synapse-bridge/src/patterns/FilterModule/FilterManager/FilterManager.vue
- packages/synapse-bridge/src/patterns/FilterModule/FilterManager/config.ts
- packages/synapse-bridge/src/patterns/FilterModule/FilterManager/index.ts
- packages/synapse-bridge/src/patterns/FilterModule/FilterManager/locales.ts
- packages/synapse-bridge/src/patterns/FilterModule/FilterManager/tests/FilterManager.spec.ts
- packages/synapse-bridge/src/patterns/FilterModule/FilterManager/tests/__snapshots__/FilterManager.spec.ts.snap
- packages/synapse-bridge/src/patterns/FilterModule/FilterManager/types.d.ts
- packages/synapse-bridge/src/patterns/FilterModule/FilterModule.vue
- packages/synapse-bridge/src/patterns/FilterModule/FilterSelector/FilterSelector.vue
- packages/synapse-bridge/src/patterns/FilterModule/FilterSelector/config.ts
- packages/synapse-bridge/src/patterns/FilterModule/FilterSelector/index.ts
- packages/synapse-bridge/src/patterns/FilterModule/FilterSelector/locales.ts
- packages/synapse-bridge/src/patterns/FilterModule/FilterSelector/tests/FilterSelector.spec.ts
- packages/synapse-bridge/src/patterns/FilterModule/FilterSelector/tests/__snapshots__/FilterSelector.spec.ts.snap
- packages/synapse-bridge/src/patterns/FilterModule/config.ts
- packages/synapse-bridge/src/patterns/FilterModule/index.ts
- packages/synapse-bridge/src/patterns/FilterModule/locales.ts
- packages/synapse-bridge/src/patterns/FilterModule/tests/FilterModule.spec.ts
- packages/synapse-bridge/src/patterns/FilterModule/tests/__snapshots__/FilterModule.spec.ts.snap
Ajout du filter module dans le bridge
<details>
```vue
<template>
<VDataTable
:headers="headers"
:items="filteredItem"
:search="search"
hide-default-footer
>
<template #top>
<TableToolbar
v-model="search"
:nb-total="items.length"
>
<template #search-left>
<FilterModule
:filters="filters"
class="mr-4"
@filter-list="displayFilters"
/>
</template>
</TableToolbar>
</template>
</VDataTable>
<FilterModule :filters="filters2"/>
</template>
import { Field } from '@/form-builder/FormField/types';
import { DataTableHeaders } from '@/patterns/PaginatedTable/types';
import {ref} from 'vue'
import TableToolbar from '@/patterns/TableToolbar/TableToolbar.vue';
import FilterModule from '@/patterns/FilterModule/FilterModule.vue';
interface TableItem {
[key: string]: string; …
```
> migrate filter module

- packages/design-tokens/src/colors.ts
-Fix color.ts types
<details>
```vue
```
</details>
- Refactoring
- Maintenance
> wip improve types errors

- packages/synapse-bridge/src/patterns/HeaderBar/HeaderBar.vue
Fix sticky header quand inclu dans un PageContainer
<details>
```vue
<template>
<HeaderBar
sticky
/>
<p>
{{ generateFakeWords(4000) }}
</p>
</template>
import HeaderBar from '@/patterns/HeaderBar/HeaderBar.vue'
import PageContainer from '@/elements/PageContainer/PageContainer.vue'
export default {
components: {
HeaderBar,
PageContainer,
},
data() {
return {
navigationItems: [
{
label: 'Accueil',
to: '/home',
}
],
}
},
methods: {
generateFakeWords(count: number) {
return Array.from({length: count}, () => Array.from({length: Math.floor(Math.random() * 3) + 1}, () => ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'][Math.floor(Math.random() * 21)] + …
```
> fix sticky header

- packages/synapse-bridge/src/patterns/PeriodField/PeriodField.vue
PeriodField : append icon bleu
<details>
```vue
<template>
<h1>Basique</h1>
<PeriodField v-model="date"/>
<p>Date saisie : {{ date }}</p>
<PeriodField v-model="date" no-prepend-icon />
<p>Date saisie : {{ date }}</p
>		<PeriodField v-model="date" append-icon />
<p>Date saisie : {{ date }}</p>
<h1>Outlined</h1>
<PeriodField v-model="date" outlined/>
<p>Date saisie : {{ date }}</p>
<h1>Label</h1>
<PeriodField v-model="date" label="Periode"/>
<p>Date saisie : {{ date }}</p>
<h1>Disabled</h1>
<PeriodField v-model="date" disabled/>
<p>Date saisie : {{ date }}</p>
<PeriodField v-model="date2"/>
<p>Date saisie : {{ date2 }}</p>
<h1>Change event</h1>
<PeriodField v-model="date3" @change="onChange"/>
<p>Date saisie : {{ date3 }}</p>
<h1>Change Format DD/MM/YYYY to YYYY/MM/DD</h1> …
```
> fix append icon color

- packages/synapse-bridge/src/patterns/AlertWrapper/AlertWrapper.vue
<details>
```vue
<template>
<HeaderBar theme="risque-pro" />
<br>
<AlertWrapper type="info">
Il semble qu’une date de naissance erronée a été saisie,
renseignez-vous auprès du centre qui vous a vacciné.
</AlertWrapper>
<br>
<AlertWrapper>
Il semble qu’une date de naissance erronée a été saisie,
renseignez-vous auprès du centre qui vous a vacciné.
</AlertWrapper>
<br />
<AlertWrapper type="info" outlined>
Il semble qu’une date de naissance erronée a été saisie,
renseignez-vous auprès du centre qui vous a vacciné.
</AlertWrapper>
<br />
<AlertWrapper type="success">
Il semble qu’une date de naissance erronée a été saisie,
renseignez-vous auprès du centre qui vous a vacciné.
</AlertWrapper>
<br />
<AlertWrapper type="success" outlined>
Il semble qu’une date de naissance …
```
> fix alertWrapper type

- packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue
<details>
```vue
<template>
<DatePicker outlined />
</template>
import PageContainer from "../src/elements/PageContainer";
import DatePicker from "@/patterns/DatePicker/DatePicker.vue";
components: {
DatePicker,
PageContainer,
},
data() {
return {
alert: true,
};
},
});
</script>
```
</details>
- Refactoring
- Maintenance
> fix outlined style

- .github/run-tests.yml
<details>
```vue
```
</details>
- Refactoring
- Maintenance
> improve github worflows

- packages/synapse-bridge/src/constants/index.ts
<details>
```vue
```
</details>
- Refactoring
- Maintenance
> add forgotten type for paginatedTable

- packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue
<details>
```vue
```
</details>
- Refactoring
- Maintenance
> fix notch on date picker

- packages/synapse-bridge/src/form-builder/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/synapse-bridge/src/form-builder/FormField/FormField.vue
- packages/synapse-bridge/src/form-builder/FormField/fields/ChoiceSliderField.vue
- packages/synapse-bridge/src/form-builder/FormField/fields/tests/__snapshots__/ChoiceSliderField.spec.ts.snap
- packages/synapse-bridge/src/form-builder/FormFieldList/FormFieldList.vue
- packages/synapse-bridge/src/form-builder/FormFieldList/tests/__snapshots__/FormFieldList.spec.ts.snap
- packages/synapse-bridge/src/patterns/SelectBtnField/SelectBtnField.vue
Fix padding + style in the formbuilder
<details>
```vue
<template>
<h2>FormBuilder</h2>
<FormBuilder v-model="form" />
{{ form }}
<br/><br/><br/>
<h2>FormFieldList</h2>
<FormFieldList
v-model="fields"
list-title="Votre état de santé"
description="Vos symptômes et leur date d’apparition."
/>
{{ fields }}
<br/><br/><br/>
<h2>FormField</h2>
{{ field }}
</template>
import {defineComponent} from "vue";
import {
FormBuilder,
FormFieldList,
FormField
} from "@/main";
import { Form } from '@/form-builder/FormBuilder/types';
import { Fields } from '@/form-builder/FormFieldList/types';
import { Field } from '@/form-builder/FormField/types';
components: {
FormBuilder,
FormFieldList,
FormField
},
data() {
return {
form: …
```
> fix form builder style

- packages/synapse-bridge/src/form-builder/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue
- packages/synapse-bridge/src/patterns/DatePicker/tests/DatePicker.spec.ts
Rendre les icônes inaccessibles a la navigation clavier
<details>
```vue
<template>
<v-row>
<v-col cols="12" md="6">
Date:	{{ date }}
Date pre definie: {{ dateDefinie }}
<h3>Basique Outlined</h3>
<date-picker v-model="date1" label="Date" :hint="defaultHint" outlined clearable />
<h3>Basique with change event</h3>
<date-picker v-model="date" label="Date" :hint="defaultHint"  @change="handleDateChange"/>
<h3>Basique</h3>
<date-picker v-model="date" label="Date" :hint="defaultHint" clearable />
<h3>Clearable</h3>
<date-picker v-model="date" label="Date" :hint="defaultHint" clearable outlined append-icon/>
<date-picker v-model="date" label="Date" :hint="defaultHint" clearable />
<h3>Required</h3>
<date-picker v-model="date" label="Date" :hint="defaultHint" …
```
> date picker iso v2

- .github/workflows/ci.yml
- .github/workflows/npm-publish.yml
- eslint.config.js
- package.json
<details>
```vue
```
</details>
- Refactoring
- Maintenance
> add npm publish test

- CHANGELOG.md
> update changelog to 2.16.7

- packages/docs/src/content/demarrer/introduction.md
- packages/docs/src/content/demarrer/notes-de-version.md
> add changelog link on Doc

- packages/synapse-bridge/src/patterns/NirField/NirField.vue
- packages/synapse-bridge/src/styles/settings.scss
```vue
<template>
<v-row class="mx-12 my-12">
<v-col cols="6">
<NirField
outlined
required
tooltip="Tooltip infos"
/>
<NirField
required
tooltip="Tooltip infos"
/>
<NirField
tooltip="Tooltip infos"
/>
<NirField
@update:model-value="getValue"
/>
Value: {{ value }}
</v-col>
<v-col cols="6">
<NirField
required
tooltip="Tooltip infos"
outlined
/>
<NirField
required
tooltip="Tooltip infos"
/>
<NirField
tooltip="Tooltip infos"
/>
<NirField @update:model-value="getValue" />
<p>Value:{{ value }}</p>
</v-col>
</v-row>
</template>
import {defineComponent} from "vue";
import NirField from "@/patterns/NirField/NirField.vue";
components: {
NirField,
},
data() {
return {
value: "",
} …
```
> Bridge : fix tooltip color

- packages/vue-dot/src/templates/ErrorPage/ErrorPage.vue
- packages/vue-dot/src/templates/ErrorPage/tests/__snapshots__/ErrorPage.spec.ts.snap
<details>
```vue
<template>
<NotFoundPage />
</template>
import NotFoundPage from '../src/templates/NotFoundPage';
components: {
NotFoundPage
},
data() {
return {
// data
};
}
});
</script>
```
</details>
> set the font-weight of the error code to 200

- packages/synapse-bridge/src/templates/ErrorPage/ErrorPage.vue
- packages/synapse-bridge/src/templates/ErrorPage/tests/__snapshots__/ErrorPage.spec.ts.snap
- packages/synapse-bridge/src/templates/NotFoundPage/tests/__snapshots__/NotFoundPage.spec.ts.snap
…ates
<details>
```vue
<template>
<NotFoundPage />
</template>
import NotFoundPage from '../src/templates/NotFoundPage';
components: {
NotFoundPage
},
data() {
return {
// data
};
}
});
</script>
```
</details>
> set the font-weight of the error code to 200 (bridge)

- packages/synapse-bridge/src/mixins/filterable/index.ts
- packages/synapse-bridge/src/patterns/FiltersInline/FiltersInline.vue
Filter inline to handle DatePicker
<details>
```vue
<template>
<VApp>
{{ filters }}
<FiltersInline v-model="filters">
<template #birth="{ attrs }">
<p>Votre date de naissance</p>
<p>default date : <strong>{{ Object.keys(attrs) }}</strong>: {{ attrs.modelValue }}</p>
<DatePicker
v-bind="attrs"
label="Date"
variant="outlined"
hide-details
/>
</template>
<template #name="{ attrs }">
<p>default date : <strong>{{ {attrs} }}</strong></p>
<VTextField
v-bind="attrs"
label="Nom"
variant="outlined"
hide-details
/>
</template>
<template #folder="{ attrs }">
<p>default date : <strong>{{ {attrs} }}</strong></p>
<p class="text-secondary mb-4">
Vous pouvez filtrer entre les dossiers de type
<b>Arrêt de Travail (AT)</b> et
<b>Maladie Professionnelle …
```
> Fix filter inline

- packages/synapse-bridge/CHANGELOG.md
> changelog 1.4.10

- CHANGELOG.md
> Changelog 2.16.8

- packages/docs/src/content/composants/filtres/filters-inline.md
- packages/docs/src/content/composants/filtres/filters-side-bar.md
FiltersInline component documentation for VueJs 3 and Bridge
>  FiltersInline component documentation for VueJs 3 and Bridge

- packages/synapse-bridge/src/patterns/NirField/NirField.vue
<details>
```vue
<template>
<NirField v-model="value1" number-label="Coucou" key-label="Toto" />
{{ value1 }}
<NirField v-model="value2" number-label="Coucou" :nirLength="13" />
{{ value2 }}
</template>
import NirField from '@/patterns/NirField/NirField.vue'
import { defineComponent } from 'vue'
import { vMaska } from 'maska'
import type { MaskInputOptions } from 'maska'
components: {
NirField,
},
directives: { maska: vMaska },
data() {
return {
toto: '1234',
value: {} as any,
value1: '4545' as string | undefined,
value2: '',
maskaNumberValue: {} as any,
options: {
mask: '## ## ## ##-##',
} satisfies MaskInputOptions,
}
},
mounted() {
this.value1 = '012345678912345'
}, 1000)
// setTimeout(() => {
// 	this.value1 = …
```
> NirField: add labels props

- packages/vue-dot/src/elements/DialogBox/DialogBox.vue
DialogBox doit retenir le focus tout en gérant la modification des éléments qui le compose
<details>
```vue
<template>
<div>
<VBtn
>
</VBtn>
<DialogBox
cancel-btn-text="Retour"
confirm-btn-text="Enregistrer"
:vuetify-options="options"
@confirm="confirm"
>
<VTextField
v-model="textField"
:rules="rules"
validate-on-blur
/>
</DialogBox>
</div>
</template>
@Component
export default class DialogBoxBtnText extends Vue {
textField = '';
rules= [
(value: string): string|true => (value.length >= 10 ? true : '10 caractères …
```
> fix focus on DialogBox

- packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
- packages/vue-dot/src/patterns/DatePicker/tests/__snapshots__/DatePicker.spec.ts.snap
> Add persistent hint for accessibility in DatePicker component

- packages/vue-dot/src/elements/DialogBox/DialogBox.vue
- packages/vue-dot/src/elements/DialogBox/tests/__snapshots__/DialogBox.spec.ts.snap
<details>
```vue
<template>
<div>
<VBtn
>
</VBtn>
<DialogBox
:width="dialogWidth"
@confirm="dialog = false"
>
</DialogBox>
</div>
</template>
import { tokens } from '@cnamts/design-tokens';
@Component
export default class DialogBoxWidth extends Vue {
dialogWidth = tokens.dialogWidth.dialogSmall;
}
</script>
```
</details>
- Maintenance
> DialogBox : add aria description 

- packages/docs/src/data/api/nir-field.ts
- packages/vue-dot/src/patterns/NirField/NirField.vue
add labels props on NirField
<details>
```vue
<template>
<div>
<NirField
v-model="value1"
number-label="Coucou"
key-label="Toto"
/>
</div>
</template>
@Component
export default class DatePickerFormat extends Vue {
value1: string | undefined = '4545';
}
</script>
```
</details>
> VueDot : nirField : add labels props 

- packages/synapse-bridge/package.json
- packages/synapse-bridge/src/form-builder/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/synapse-bridge/src/form-builder/FormField/fields/tests/__snapshots__/ChoiceField.spec.ts.snap
- packages/synapse-bridge/src/form-builder/FormField/fields/tests/__snapshots__/ChoiceSliderField.spec.ts.snap
- packages/synapse-bridge/src/form-builder/FormField/fields/tests/__snapshots__/TextArea.spec.ts.snap
- packages/synapse-bridge/src/form-builder/FormFieldList/tests/__snapshots__/FormFieldList.spec.ts.snap
- packages/synapse-bridge/src/patterns/NirField/NirField.vue
- packages/synapse-bridge/src/patterns/NirField/tests/NirField.spec.ts
- packages/synapse-bridge/src/patterns/NirField/tests/__snapshots__/NirField.spec.ts.snap
- packages/synapse-bridge/src/patterns/PasswordField/tests/__snapshots__/PasswordField.spec.ts.snap
- packages/synapse-bridge/src/patterns/PhoneField/tests/__snapshots__/PhoneField.spec.ts.snap
- packages/synapse-bridge/src/templates/CookiesPage/CookiesInformation/tests/__snapshots__/CookiesInformation.spec.ts.snap
- packages/synapse-bridge/src/templates/CookiesPage/tests/__snapshots__/CookiesPage.spec.ts.snap
- pnpm-lock.yaml
Le NirField doit executer ses règles de validation quand le VForm parent est submit
<details>
```vue
import NirField from '@/patterns/NirField'
import { VForm, VApp } from 'vuetify/components'
</script>
<template>
<v-app>
<VForm>
<NirField required />
<NirField required :nirLength="13" />
<button>Submit</button>
</VForm>
</v-app>
</template>
```
</details>
> Fix NirField validation when VForm submit

- packages/synapse-bridge/src/form-builder/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap
- packages/synapse-bridge/src/form-builder/FormField/fields/tests/__snapshots__/ChoiceField.spec.ts.snap
- packages/synapse-bridge/src/patterns/SelectBtnField/SelectBtnField.vue
- packages/synapse-bridge/src/patterns/SelectBtnField/tests/SelectBtnField.spec.ts
- packages/synapse-bridge/src/patterns/SelectBtnField/tests/__snapshots__/SelectBtnField.spec.ts.snap
Portage des fix relatifs a l'accessibilité par demande du P1 vers le bridge pour le composant SelectBtnField
<details>
```vue
import SelectBtnField from '@/patterns/SelectBtnField/SelectBtnField.vue';
const value = ref(null);
const items =  [
{
text: 'Email',
value: 'email'
},
{
value: 'courrier'
},
{
text: 'SMS',
value: 'sms'
}
]
</script>
<template>
<SelectBtnField
v-model="value"
:items="items"
label="Moyen de contact"
/>
</template>
<style lang="scss" scoped></style>
```
</details>
> fix: a11y port from v2

- packages/synapse-bridge/CHANGELOG.md
- packages/synapse-bridge/src/elements/DialogBox/DialogBox.vue
- packages/synapse-bridge/src/elements/DialogBox/tests/DialogBox.spec.ts
- packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue
- packages/synapse-bridge/src/patterns/SelectBtnField/SelectBtnField.vue
> add changelog

- packages/synapse-bridge/src/elements/LogoBrandSection/LogoBrandSection.vue
NuxtLink ne fonctionne pas
<details>
```vue
<template>
<VApp>
<HeaderBar
service-title="Design System"
service-sub-title="Documentation du Design System"
/>
</VApp>
</template>
import HeaderBar from "@/patterns/HeaderBar";
components: {
HeaderBar,
},
data() {
return {
};
},
});
</script>
```
</details>
> LogoBrandSection: fix nuxtlink

- packages/synapse-bridge/package.json
- packages/synapse-bridge/src/patterns/NirField/NirField.vue
- packages/synapse-bridge/src/patterns/NirField/tests/__snapshots__/NirField.spec.ts.snap
- pnpm-lock.yaml
Portage v2
<details>
```vue
<template>
<NirField
v-model="nir"
required
outlined
:nir-length="15"
>
<template #number-append-icon>
<VIcon color="success">
{{ mdiCheck }}
</VIcon>
</template>
<template #key-append-icon>
<VIcon color="success">
{{ mdiCheck }}
</VIcon>
</template>
</NirField>
</template>
import NirField from "@/patterns/NirField";
import { mdiCheck } from '@mdi/js';
components: {
NirField,
},
data() {
return {
nir: null,
mdiCheck
};
},
});
</script>
```
</details>
> NirField: add icon slots

- packages/synapse-bridge/package.json
- packages/synapse-bridge/src/patterns/PasswordField/PasswordField.vue
- packages/synapse-bridge/src/patterns/PasswordField/tests/PasswordField.spec.ts
- pnpm-lock.yaml
Gestion de l'appui sur la touche Entrée : Nous avons également remarqué que le composant ne gère pas l'appui sur la touche Entrée pour soumettre le formulaire. Est-ce un choix de conception délibéré ou est-ce un comportement qui devrait être implémenté ?
ajout de submit
<details>
```vue
<template>
<v-col cols="3">
<PasswordField v-model="password" @submit="handleSubmit"></PasswordField>
<PasswordField v-model="password" outlined @submit="handleSubmit"></PasswordField>
<PhoneField />
<v-btn @click="handleSubmit">Submit</v-btn>
</v-col>
</template>
import PasswordField from "@/patterns/PasswordField/PasswordField.vue"
import PhoneField from "@/patterns/PhoneField/PhoneField.vue"
components: { …
```
> add pressing enter management on passwordField

- CHANGELOG.md
> update changelog 2.16.10

- packages/synapse-bridge/package.json
<details>
```vue
```
</details>
- Refactoring
- Maintenance
> remove pnpm from package.json engines

- packages/vue-dot/src/patterns/NotificationBar/NotificationBar.vue
<details>
```vue
<template>
<div>
<NotificationBar v-show="showNotificationBar" />
<VBtn
@click="notifyUser"
>
Envoyer une notification
</VBtn>
</div>
</template>
import { mapActions, mapState } from 'vuex';
const EXAMPLE_REF = 'usage-example';
@Component({
computed: mapState('notification', ['notification']),
methods: mapActions('notification', ['addNotification'])
})
export default class NotificationBarUsage extends Vue {
get showNotificationBar(): boolean {
return this.notification?.ref === EXAMPLE_REF;
}
notifyUser(): void {
this.addNotification({
ref: EXAMPLE_REF,
type: 'error',
message: 'Exemple de notification.'
});
}
}
</script>
```
</details>
- …
> fix color of success type notificationBar

- packages/docs/src/data/api/date-picker-bridge.ts
- packages/docs/src/data/api/period-field-bridge.ts
Mise a jour de la documentation du DatePicker et PeriodeField sur le bridge
> Update bridge documentation DatePicker et PeriodeField

- packages/synapse-bridge/CHANGELOG.md
> Changelog 3.0.3

- packages/synapse-bridge/CHANGELOG.md
- pnpm-lock.yaml
> changelog 3.0.4

- packages/synapse-bridge/src/elements/DialogBox/DialogBox.vue
> DialogBox: add aria

- CHANGELOG.md
Update changelog to 2.16.11
- Maintenance
> Update changelog to 2.16.11

- packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue
<details>
```vue
import { notAfterDate, notBeforeDate, required } from '@/main';
import DatePicker from '@/patterns/DatePicker/DatePicker.vue';
import { reactive } from 'vue';
const piece = reactive({
dateRedaction: '',
dateReception: '',
});
const date = ref('')
</script>
<template>
<DatePicker
v-model="piece.dateRedaction"
label="Date de rédaction (optionnel)"
bg-color="white"
outlined
:rules="[
notAfterDate(piece.dateReception || ''),
]"
/>
<br>
<DatePicker
v-model="piece.dateReception"
label="Date de réception"
bg-color="white"
outlined
:rules="[
required,
notBeforeDate(piece.dateRedaction || ''),
]"
/>
<DatePicker
v-model="date"
label="Date "
outlined
:rules="[
required,
notBeforeDate(piece.dateRedaction || ''),
]"
/>
</template> …
```
> fix value edition

- packages/synapse-bridge/CHANGELOG.md
> add changelog 3.0.5
