packages/vue-dot/playground/examples/PaginatedTableEx.vue, packages/vue-dot/src/patterns/PaginatedTable/PaginatedTable.vue
Use sync modifier to avoid typing `options = $event` and rename the event `pagination:updated` to `update:options`.
=> ♻️ vue-dot: Use sync modifier for options props in PaginatedTable

packages/vue-dot/package.json, packages/vue-dot/src/patterns/DatePicker/tests/__snapshots__/DatePicker.spec.ts.snap, packages/vue-dot/src/patterns/DatePicker/tests/birthdate.spec.ts, packages/vue-dot/src/patterns/DatePicker/tests/dateLogic.spec.ts, packages/vue-dot/src/patterns/UploadWorkflow/tests/UploadWorkflow.spec.ts, yarn.lock
Vue test utils version 1.0.0-bata.30 introduced [breaking changes](https://github.com/vuejs/vue-test-utils/blob/dev/CHANGELOG.md#100-beta30-2019-11-28) so we needed to update our tests!
=> ⬆️ vue-dot: Upgrade vue-test-utils

packages/vue-dot/src/elements/DataList/DataList.vue, packages/vue-dot/src/elements/DataList/types.d.ts, packages/vue-dot/src/mixins/warningRules/index.ts, packages/vue-dot/src/patterns/FileList/FileList.vue, packages/vue-dot/src/patterns/FileUpload/FileUpload.vue, packages/vue-dot/src/patterns/LangBtn/LangBtn.vue, packages/vue-dot/src/patterns/LangBtn/types.d.ts, packages/vue-dot/src/patterns/PaginatedTable/PaginatedTable.vue, packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
Use [tip from vue-typescript-cookbook](https://github.com/ffxsam/vue-typescript-cookbook#when-i-use-an-array-prop-type-my-components-properties-data-computed-properties-etc-are-shown-as-type-errors) to make prop types stronger
=> 🏷️ vue-dot: Make prop types stronger

packages/vue-dot/playground/Playground.vue, packages/vue-dot/playground/plugins/vue-dot.ts, packages/vue-dot/src/patterns/PaginatedTable/PaginatedTable.vue, packages/vue-dot/types/index.d.ts
Use LocalStorageUtility in PaginatedTable to have proper cache management.
- The `prefix` property on `PaginatedTable` was renamed to `suffix`
To configure the instance, pass the object `localStorageControl` in Vue Dot options as following:
```ts
export const LOCAL_STORAGE_CONTROL = {
version: 1
};
Vue.use(VueDot, {
localStorageControl: LOCAL_STORAGE_CONTROL
});
```
All parameters of `LocalStorageUtility` are supported (`version`, `expiration` and `prefix`).
=> ♻️ vue-dot: Refactor PaginatedTable to use LocalStorageUtility

packages/vue-dot/src/elements/CopyBtn/CopyBtn.vue, packages/vue-dot/src/elements/CopyBtn/config.ts, packages/vue-dot/src/elements/CopyBtn/tests/__snapshots__/CopyBtn.spec.ts.snap, packages/vue-dot/src/styles/global.scss
Refactor CopyBtn by using a menu instead of a tooltip. This fits better our need because the tooltip is designed to display information on hover, but we need to display it on click.
This change fixes the hide/show bug, the component is now more stable and we finally can make have multiple instances on one page.
=> ♻️ vue-dot: Refactor CopyBtn

packages/vue-dot/src/elements/CopyBtn/CopyBtn.vue, packages/vue-dot/src/elements/CustomIcon/CustomIcon.vue, packages/vue-dot/src/elements/DataList/DataList.vue, packages/vue-dot/src/mixins/eventable/index.ts, packages/vue-dot/src/mixins/warningRules/index.ts, packages/vue-dot/src/patterns/DatePicker/mixins/birthdate.ts, packages/vue-dot/src/patterns/DatePicker/mixins/dateLogic.ts, packages/vue-dot/src/patterns/DatePicker/mixins/errorProp.ts, packages/vue-dot/src/patterns/DatePicker/mixins/maskValue.ts, packages/vue-dot/src/patterns/DatePicker/mixins/pickerDate.ts, packages/vue-dot/src/patterns/FileList/FileList.vue, packages/vue-dot/src/patterns/FileUpload/FileUpload.vue, packages/vue-dot/src/patterns/LangBtn/LangBtn.vue, packages/vue-dot/src/patterns/NotificationBar/NotificationBar.vue, packages/vue-dot/src/patterns/PageCard/PageCard.vue, packages/vue-dot/src/patterns/PaginatedTable/PaginatedTable.vue, packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
Refactor mixins declaration by introducing a new way to declare their usage using [vue-class-component mixin helper](https://github.com/vuejs/vue-class-component#using-mixins).
It looks like this:
```ts
import Component, { mixins } from 'vue-class-component';
import MixinA from '...';
import MixinA from '...';
const Props = Vue.extend({});
const MixinsDeclaration = mixins(Props, MixinA, MixinB);
class MyComponent extends MixinsDeclaration {}
```
- Should we apply this also when we're just using one mixin (eg. components that `extends Props`)?
This will be more standard and make it easier to create a component, but this requires more boilerplate -> Yes
- Is the name `MixinsDeclaration` right? We're not really declarating them, we're using them -> If we find something …
=> ♻️ vue-dot: Refactor mixins declaration

packages/vue-dot/playground/examples/FormFieldEx.vue, packages/vue-dot/src/functions/getFormValues/tests/data/forms.ts, packages/vue-dot/src/functions/setFormErrors/tests/__snapshots__/setFormErrors.spec.ts.snap, packages/vue-dot/src/functions/setFormErrors/tests/data/formErrors.ts, packages/vue-dot/src/patterns/FormBuilder/mixins/tests/formBuilderCore.spec.ts, packages/vue-dot/src/patterns/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/vue-dot/src/patterns/FormBuilder/tests/data/addressForm.ts, packages/vue-dot/src/patterns/FormBuilder/tests/data/questionForm.ts, packages/vue-dot/src/patterns/FormField/mixins/fieldMap.ts, packages/vue-dot/src/patterns/FormField/mixins/tests/__snapshots__/fieldMap.spec.ts.snap, packages/vue-dot/src/patterns/FormField/mixins/tests/fieldComponent.spec.ts, packages/vue-dot/src/patterns/FormField/mixins/tests/fieldMap.spec.ts, packages/vue-dot/src/patterns/FormField/tests/FormField.spec.ts, packages/vue-dot/src/patterns/FormLayout/mixins/tests/layoutComponent.spec.ts, packages/vue-dot/src/patterns/FormLayout/tests/FormLayout.spec.ts
QUE 83
rename field type  'string' to 'text'
=> Vue-dot: rename field type 'string' to 'text'

packages/vue-cli-plugin-vue-dash/generator/template/tests/unit/index.ts, packages/vue-dot/package.json, packages/vue-dot/tests/index.ts, yarn.lock
In version 1.0.0-beta.31, @vue/test-utils removed default export, so we needed to upgrade Vue Dot tests and Vue Dash template
=> ⬆️ Upgrade @vue/test-utils

packages/vue-dot/playground/examples/SubHeaderEx.vue, packages/vue-dot/src/elements/HeaderLoading/HeaderLoading.vue, packages/vue-dot/src/elements/HeaderLoading/index.ts, packages/vue-dot/src/elements/HeaderLoading/tests/HeaderLoading.spec.ts, packages/vue-dot/src/elements/HeaderLoading/tests/__snapshots__/HeaderLoading.spec.ts.snap, packages/vue-dot/src/elements/index.ts, packages/vue-dot/src/patterns/SubHeader/SubHeader.vue, packages/vue-dot/src/patterns/SubHeader/config.ts, packages/vue-dot/src/patterns/SubHeader/loading/DataListLoading.vue, packages/vue-dot/src/patterns/SubHeader/tests/__snapshots__/SubHeader.spec.ts.snap, packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap, packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap, packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Ajout d'un état de chargement pour le `SubHeader` en utilisant le [`VSkeletonLoader` de Vuetify](https://vuetifyjs.com/en/components/skeleton-loaders) :
(J'ai dû créer un nouveau composant `HeaderLoading` pour avoir un élément de chargement que je pouvais redimensionner en hauteur)
Et mise à jour du style en accord avec les UX/UI
=> ♻️ vue-dot: Add SubHeader loading state

packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppFooter.vue, packages/vue-cli-plugin-vue-dash/generator/template/vue.config.js, packages/vue-dot/playground/Playground.vue, packages/vue-dot/vue.config.js
Use a proper env var instead of importing version from `package.json` (which included the full file in the client bundle)
=> ♻️ global: Don't import package.json in client code

.travis.yml
Build library after tests because some cases cannot be catched by lint or tests (eg. library size)
=> 🔧 Add build stage to CI setup

packages/vue-dot/src/directives/debounce/index.ts, packages/vue-dot/src/directives/debounce/tests/debounce.spec.ts, packages/vue-dot/src/functions/debounce/index.ts
Refonte de la directive `v-debounce`.
Si aucun délai n'était précisé, la directive n'utilisait pas la valeur par défaut la fonction `debounce`.
(Ici : `parseInt(value, 10)`, `value` pouvait être `undefined` ou une fonction, ce qui renvoyait `NaN`)
Il y avait également deux APIs en une :
- `v-debounce="1000"` pour les inputs classiques
- `v-debounce.1000="e => value = e"` pour les composants personnalisés (ex : `VTextField`)
Afin de corriger ce bug et de n'avoir qu'une seule API, le délai est maintenant toujours spécifié en tant que modificateur :
- `v-debounce.1000`
- `v-debounce.1000="e => value = e"`
=> ♻️ vue-dot: Refactor debounce directive

packages/vue-dot/src/patterns/FileUpload/FileUpload.vue, packages/vue-dot/src/patterns/LangBtn/LangBtn.vue
Inversion des propriétés booléennes avec comme valeur par défaut `true`
Avoir des propriétés avec comme valeur par défaut `true` est une mauvaise pratique car cela oblige l'utilisateur à écrire, par exemple `:ripple="false"` ; il est plus simple d'écrire `no-ripple`
=> ♻️ vue-dot: Invert boolean props with default true

packages/vue-dot/playground/examples/DatePickerEx.vue, packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
Forçage du type du `VDatePicker` en `date` comme on ne supporte pas le mode `month`
Et correction de l'alignement des icônes dans le `DatePicker` ; jusqu'à présent on déplaçait vers le bas toutes les icônes pour que nos boutons s'affichent correctement, mais cela affectait les boutons Vuetify qui sont plus petits, ils n'étaient plus centrés
Maintenant on déplace vers le haut uniquement nos boutons et tout est bien aligné :
=> ♻️ vue-dot: Force type to date & fix icon alignment in DatePicker

packages/vue-dot/src/patterns/DatePicker/mixins/dateLogic.ts, packages/vue-dot/src/patterns/DatePicker/tests/birthdate.spec.ts, packages/vue-dot/src/patterns/DatePicker/tests/dateLogic.spec.ts
Lorsqu'un autre format que celui utilisé pour le `v-model` était utilisé, le composant affichait `Invalid Date` dans le champ de texte
Pour corriger cela, lorsque la date est invalide on retourne une chaîne
Cela entraîne un changement de comportement plus général : maintenant lorsqu'il y a une erreur, le composant émet un événement `change` avec une valeur vide
J'ai aussi supprimé un appel à `this.saveFromTextField();` lorsque le `v-model` est mis à jour car on l'appelle déjà lors du `blur`
=> 🐛 vue-dot: Fix "Invalid Date" when wrong format used in DatePicker

packages/vue-dot/src/elements/DialogBox/DialogBox.vue
Lors de l'utilisation de la version actuelle de Vue Dot dans une appli créée avec Vue Dash, il y a une erreur :
```
warning  in ./node_modules/@cnamts/vue-dot/src/elements/DialogBox/DialogBox.vue?vue&type=script&lang=ts&
"export 'default' (imported as 'tokens') was not found in '../../tokens'
```
à priori ça serait lié à Babel (https://github.com/webpack/webpack/issues/4817)
En attendant de trouver la solution je retire l'import
=> 🔥 vue-dot: Remove tokens import in DialogBox

packages/vue-dot/src/elements/PageCard/PageCard.vue
`no-shadow` peut ne pas fonctionner lors du build à cause de l'ordre des styles, il faudrait ajouter `!important`, mais on peut simplement faire `:elevation="0"` comme c'est une `VCard`
=> 🔥 vue-dot: Delete no-shadow prop on PageCard

CHANGELOG.md
[Fichier rendu](https://github.com/assurance-maladie-digital/design-system/blob/feat/changelog/CHANGELOG.md)
Il faudra maintenant mettre à jour le changelog le plus souvent possible, idéalement à chaque PR puisque ça prend du temps de rattraper les commits
Aussi pour les dépendances, lorsqu'une est mise à jour plus d'une fois dans la version, on prend la dernière pour éviter de polluer le changelog avec toutes les versions (sauf exception, par exemple dans la section "Non publié" il y a deux fois `vuetify` puisque dans la première PR il y a la migration)
=> 📝 Add CHANGELOG

packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
Demande de l'équipe ATMP pour détecter quand l'utilisateur commence à taper dans le champ
La valeur de l'événement est la valeur **masquée** du `VTextField`
=> ✨ vue-dot: Expose input event in DatePicker

packages/vue-cli-plugin-vue-dash/generator/template/src/theme/styles/utility.scss, packages/vue-cli-plugin-vue-dash/generator/template/src/theme/styles/vuetify.scss
- La classe `sr-only` est maintenant dans Vuetify sous le nom `d-sr-only`
- Le fait de spécifier les champs obligatoires n'est pas conseillé dans le Design System, il est préférable de spécifier les champs optionnels quand la plupart sont obligatoires, le cas contraire n'arrive que très rarement (suppression de `.required`)
- La classe `form-input` est remplacée par celle déjà présente dans Vue Dot `vd-form-input` qui utilise les Design Tokens
- La classe `no-flex` est remplacée par les nouvelles classes d'aide de Vuetify (l'équivalent devrait être `flex-grow-0`)
Il faudra aussi analyser le reset inclut dans Vuetify, il est possible qu'on puisse supprimer le notre !
=> 🔥 vue-dash: Remove unnecessary styles

packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js, packages/vue-cli-plugin-vue-dash/package.json
Il manquait la dépendance `@cnamts/vue-dot` dans le template de Vue Dash
=> 🐛 vue-dash: Fix missing Design Tokens dependency in template

packages/vue-cli-plugin-vue-dash/generator/template/src/theme/styles/vuetify.scss
On ne peut pas faire un `@extend` d'une classe qui n'est pas importée, et en regardant le code source de Vuetify j'ai trouvé la mixin `visually-hidden` qui fait exactement ce dont on a besoin ici !
=> 🐛 vue-dash: Fix wrong @extend in default theme

packages/vue-cli-plugin-vue-dash/generator/functions/getFooterDate.js, packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppHeader.vue, packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppToolbar.vue
Correction :
- des composants `AppHeader` et `AppToolbar` qui prenaient trop de hauteur car la classe `no-flex` n'existe plus dans les styles par défaut (il faut utiliser `flex-grow-0` [de Vuetify](https://vuetifyjs.com/en/styles/flex/#flex-grow-and-shrink) à la place)
- du mois dans `AppFooter` qui était précédé de `– ` (reliquat de l'ancien footer)
- des attributs `wrap` et `align-center` qui ne sont pas des attributs de `VAppBar` (mais de `VLayout`, ce sont aussi des reliquats de l'ancien template)
- de la couleur de fond du `VAppBar` appliqué via une classe au lieu d'utiliser l'attribut dédié `color`
- du tag `section` appliqué à la place de `nav` (ce dernier fait plus de sens car c'est une liste de liens de navigation) (d'ailleurs il faudrait peut-être renommer `AppToolbar` en …
=> 🐛 vue-dash: Fix template styles

packages/vue-dot/src/elements/DataList/DataList.vue, packages/vue-dot/src/elements/DataList/DataListItem/DataListItem.vue, packages/vue-dot/src/elements/DataList/types.d.ts
Issue à l'origine de la PR :
https://github.com/assurance-maladie-digital/design-system/issues/469
**Problématique** :   
Les DataListItem ne prenaient que des valeurs de types string, si on lui passait un nombre le composant rencontrait une erreur.
J'ai modifié la prop `value` du DataListIem pour qu'elle retourne systématiquement un string et j'ai modifié DataListItem et IDataList pour qu'il accepte des valeurs string ou number.
=> 🐛 vue-dot: Fix error with number value in DataListItem

packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js, packages/vue-cli-plugin-vue-dash/generator/template/src/main.ts
Comme remonté et corrigé par @DamienRenaud, le package `vue-input-facade` ne fonctionne pas sous IE, il nécessite un polyfill pour `new CustomEvent`
=> 🐛 vue-dash: Fix missing polyfill for vue-input-facade on IE

packages/form-builder/src/components/FormBuilder/tests/data/questionForm.ts, packages/form-builder/src/components/FormField/FormField.vue
Update UX field tooltip to accept word wrap or tabulation and white space.
Solution 
Use \<pre> instead of <span> to keep word wrap, whitespace or tabulation.
=> ✨ form-builder: Allow line breaks in FormField tooltip

packages/vue-dot/src/patterns/UploadWorkflow/mixins/uploadWorkflowCore.ts
On notifie une modification du v-model lorsque le reset d'un fichier a été demandé, sinon la fonction change du composant UploadWorkflow n'est pas appelée.
Pour la définition du composant suivante
```xml
v-if="!genok"
v-model="files"
@change="valueUpdated"
@error="showError"
>
```
la fonction `valueUpdated` n'était donc jamais appelée lors d'un clic sur l'icone 'corbeille' du composant
- [ X] Correction de bug
=> 🐛 vue-dot: Fix change event not fired on resetFile in UploadWorkflow

packages/vue-dot/src/patterns/UploadWorkflow/FileList/FileList.vue, packages/vue-dot/src/patterns/UploadWorkflow/mixins/tests/uploadWorkflowCore.spec.ts, packages/vue-dot/src/patterns/UploadWorkflow/mixins/uploadWorkflowCore.ts
Lorsqu'un fichier erroné puis un fichier valide étaient sélectionnés, l'état final de la ligne dans la liste était `error` au lieu de `success`
L'affichage des erreurs a également été modifié, maintenant un fichier en erreur est affiché dans la liste (avec en plus le bouton "supprimer" pour réinitialiser)
Les événements `change` et `error` sont maintenant émis dans `$nextTick`
=> 🐛 vue-dot: Fix error display in UploadWorkflow

packages/vue-cli-plugin-vue-dash/generator/template/src/global.d.ts, packages/vue-cli-plugin-vue-dash/generator/template/vue.config.js
Il manquait la dépendance `vue-input-facade` dans `transpileDependencies` dans le template par défaut
=> 🐛 vue-dash: Fix missing vue-input-facade in transpileDependencies

CHANGELOG.md, packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/form-builder/src/components/FormField/fields/TextareaField.vue
Réduction de largeur sur le champ textarea en mettant la classe 'vd-form-input-xl' sur le champ 'TextereaField' pour avoir un max-width plus grand.
Avant: 
Après:
=> 🐛 form-builder: Fix textarea width

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/generator/template/src/main.ts, packages/vue-cli-plugin-vue-dash/generator/template/tests/unit/index.ts
Suppression d'imports des composants globaux toujours présents, ce qui générait des erreurs
=> 🔥 vue-dash: Remove global component imports in template

CHANGELOG.md, packages/vue-dot/playground/examples/DataListEx.vue, packages/vue-dot/src/elements/DataList/DataList.vue, packages/vue-dot/src/elements/DataList/tests/data/dataList.ts, packages/vue-dot/src/elements/DataList/types.d.ts, packages/vue-dot/src/patterns/SubHeader/tests/data/subHeader.ts, packages/vue-dot/src/patterns/SubHeader/types.d.ts
Renommage de l'interface `IDataList` en `DataList`. Elle était nommée comme ça pour éviter un conflit avec `class DataList`, mais en fait on peut renommer l'interface lors de l'import pour ne pas avoir le préfixe dans le code client
- Refactoring
=> ♻️ vue-dot: Rename IDataList interface to DataList

CHANGELOG.md, packages/form-builder/.eslintrc.js, packages/form-builder/src/components/FormBuilder/mixins/tests/formBuilderCore.spec.ts, packages/form-builder/src/components/FormField/mixins/tests/choiceComponent.spec.ts, packages/form-builder/src/components/FormField/mixins/tests/fieldComponent.spec.ts, packages/form-builder/src/components/FormField/mixins/tests/fieldMap.spec.ts, packages/vue-dot/.eslintrc.js
Suite à la mise à jour du plugin ESLint Vue on peut réactiver la règle `vue/custom-event-name-casing` et modifier la configuration de la règle `vue/valid-v-slot`
- Maintenance
=> 🚨 Update lint config

CHANGELOG.md, packages/vue-dot/playground/examples/DataListEx.vue, packages/vue-dot/playground/examples/ErrorPageEx.vue, packages/vue-dot/src/templates/ErrorPage/ErrorPage.vue, packages/vue-dot/src/templates/ErrorPage/locales.ts, packages/vue-dot/src/templates/ErrorPage/tests/ErrorPage.spec.ts, packages/vue-dot/src/templates/ErrorPage/tests/__snapshots__/ErrorPage.spec.ts.snap
Modification des props du template `ErrorPage`, maintenant on met une valeur par défaut dans `btnText` (anciennement `cta`), mais cela empêche la désactivation du bouton donc on ajoute la prop `noBtn`
- Refactoring
=> ♻️ vue-dot: Refactor ErrorPage

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/generator/template/src/App.vue, packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/AppToolbar.vue, packages/vue-cli-plugin-vue-dash/generator/template/src/components/layout/HeaderMenu.vue, packages/vue-cli-plugin-vue-dash/generator/template/src/views/About.vue, packages/vue-cli-plugin-vue-dash/generator/template/src/views/Home.vue, packages/vue-cli-plugin-vue-dash/generator/template/src/views/NotFound.vue
Correction des attributs `data-cy` manquants et suppression des attributs en trop
Aussi on n'ajoute les attributs que si l'option `cypress` est sélectionnée
=> 🐛 vue-dash: Fix missing data-cy attributes

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/vueDotLoader.js
Ajout des descriptions JSDoc manquantes dans `vueDotLoader`.
- Maintenance
=> 🚨 vue-dash: Add missing JSDoc in vueDotLoader

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/generator/functions/extendPackage.js
Mise à jour de Jest vers la `v26` dans le SK
La version était bloquée par Vue CLI, on la débloque car éprouvé par le Design System, maintenant tout le monde est aligné
- Maintenance
=> ⬆️ vue-dash: Update jest to v26

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/generator/getResourcesToDelete.js
Suppression des fichiers JS par défaut pour ensuite désactiver le renommage des fichiers JS en TS qui pose problème avec le fichier `matomo.js`.
- Refactoring
=> ♻️ vue-dash: Update resources to delete

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/generator/template/public/css/base.css
Ajout d'une transition par défaut sur les liens (elle avait été supprimée suite au refactoring des styles, mais on en a besoin sur le logo du `AppHeader` par exemple)
- Refactoring
=> 💄 vue-dash: Add default transition on links

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/vueDotLoader.js
Correction de la variable `VUE_APP_VERSION` déclarée dans `vueDotLoader.js`, cela est dû à un mauvais copier/coller et à pour conséquence d'afficher la version de Vue Dot dans le footer de l'application
=> 🐛 vue-dash: Fix VUE_APP_VERSION declared in vueDotLoader

CHANGELOG.md, packages/cli-helpers/jest.config.ts, packages/design-tokens/jest.config.ts, packages/form-builder/jest.config.ts, packages/vue-dot/jest.config.ts
Utilisation de TypeScript pour la configuration de Jest
Il faut utiliser node.js 12 lors du dev sur le DS à cause de cette erreur https://github.com/jsdom/jsdom/issues/2961
(on peut mettre à jour sans soucis, on va devoir le faire sur les envs également)
- Maintenance
=> 🔧 Use TypeScript for Jest configuration

CHANGELOG.md, packages/vue-dot/playground/examples/PaginatedTableEx.vue, packages/vue-dot/src/patterns/PaginatedTable/PaginatedTable.vue
L'événement `update:options` est émis deux fois sur la `PaginatedTable` car on a `v-on="$listeners"` sur la `VDataTable` mais qu'on émet également le même événement dans le setter `optionsCalc`
Lorsque l'on écoute l'événement `<PaginatedTable @update:options="fetchData" />`, il est émis sur la `VDataTable` et la `PaginatedTable`, la méthode `fetchData` est donc appelée deux fois
=> 🐛 vue-dot: Fix update:options event fired twice in PaginatedTable

CHANGELOG.md, packages/vue-dot/src/rules/notAfterToday/locales.ts, packages/vue-dot/src/rules/notBeforeToday/locales.ts
Correction des messages d'erreur des règles de validation `notAfterToday` et `notBeforeToday`
=> 🐛 vue-dot: Fix notAfterToday & notBeforeToday locales

CHANGELOG.md, packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/form-builder/src/components/FormField/fields/ChoiceButtonField.vue
La largeur du champ `ChoiceFieldButton` était fixe, ce qui forçait le retour à la ligne au bout d'une certaine longueur
=> 🐛 form-builder: Fix ChoiceFieldButton width when inline

CHANGELOG.md, packages/form-builder/src/components/FormField/fields/ChoiceField.vue
Pas de raison d'utiliser une méthode au lieu d'une propriété calculée pour `isOtherActive` dans `ChoiceField`, on bénéficiera de la mise en cache
- Refactoring
=> ♻️ form-builder: Use computed property for isOtherActive in ChoiceField

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/generator/template/src/App.vue
Suppression de la classe `main-ctn` non utilisée dans le composant `App`
- Refactoring
=> 🔥 vue-dash: Remove unused main-ctn class in App component

CHANGELOG.md, packages/vue-dot/src/elements/DataList/DataList.vue, packages/vue-dot/src/elements/DataList/tests/DataList.spec.ts, packages/vue-dot/src/elements/DataList/tests/__snapshots__/DataList.spec.ts.snap, packages/vue-dot/src/elements/DataList/tests/data/dataList.ts, packages/vue-dot/src/elements/DataList/types.d.ts
Ajout de l'attribut `class` dans les items de la `DataList`, cela permet d'identifier les items, par exemple pour mettre certains labels en gras on peut ajouter une classe `bold-label` :
```
items: DataListItem[] = [
{
key: 'Civility',
value: 'Mr',
class: 'bold-label'
}
];
```
avec ces styles :
```scss
.vd-data-list-item.bold-label .vd-data-list-item-label {
font-weight: 700;
}
```
J'ai également modifié les tests car la liste utilisée était modifiée dans les tests, en utilisant une fonction elle n'est plus modifiée
Fixes #470 
=> ✨ vue-dot: Add class attribute on DataList items

CHANGELOG.md, packages/vue-dot/playground/examples/NotificationEx.vue, packages/vue-dot/src/modules/notification/index.ts, packages/vue-dot/src/modules/notification/notify.ts, packages/vue-dot/src/modules/notification/tests/notification.spec.ts, packages/vue-dot/src/modules/notification/tests/notify.spec.ts, packages/vue-dot/src/modules/notification/types.d.ts, packages/vue-dot/src/patterns/NotificationBar/NotificationBar.vue, packages/vue-dot/src/patterns/NotificationBar/tests/NotificationBar.spec.ts
- Mise à jour de l'API du module `notification` et gestion de l'affichage de deux notifications consécutives
- Ajout d'une propriété optionnelle `ref` sur l'objet notification (pour la documentation et afficher plusieurs fois le composant `NotificationBar` sur une même page
- Types de notification plus strictes sur l'interface
- Export de la variable `state` pour utiliser le module avec Nuxt
- Refactoring
=> ♻️ vue-dot: Update notification module API & behavior

CHANGELOG.md, packages/vue-dot/src/patterns/FooterWrapper/FooterBtn/FooterBtn.vue
Correction de la couleur du bouton écrasée par Vuetify avec la prop `inert`.
Parfois, les styles de Vuetify sont intégrés avant ceux du `FooterBtn`, et comme le sélecteur de Vuetify qui applique la couleur a la même spécificité que celui du composant `FooterBtn`, c'est celui-ci qui est appliqué :
Le style appliqué par Vuetify :
```css
.theme--light.v-btn.v-btn--disabled {
color: rgba(0, 0, 0, .26) !important;
}
```
Le style appliqué par le composant `FooterBtn` :
```css
.vd-footer-btn.v-btn[data-v-60a6e493] {
color: #424242 !important;
}
```
Les deux sélecteurs ont une spécificité de `030`, en ajoutant `.theme--light` au sélecteur du composant `FooterBtn`, la spécificité de celui-ci devient `040` et notre sélecteur sera toujours apploqué.
=> 🐛 vue-dot: Fix inert FooterBtn color overwritten by Vuetify

CHANGELOG.md, package.json, yarn.lock
Mise à jour de la dépendance `@types/node` vers la `v14`, cela permet de corriger les erreurs de build sur la PR #927 
- Maintenance
=> ⬆️ Update dependency @types/node to v14

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/generator/template/_eslintignore, packages/vue-cli-plugin-vue-dash/generator/template/_eslintrc.js
Suppression du fichier `.eslintignore` dans le template
Cela permet de n'avoir qu'un seul fichier de configuration pour ESLint
- Maintenance
=> 🔥 vue-dash: Remove .eslintignore file

CHANGELOG.md, packages/vue-dot/src/elements/DataList/DataList.vue, packages/vue-dot/src/elements/DataList/DataListLoading/DataListLoading.vue, packages/vue-dot/src/elements/DataList/DataListLoading/tests/__snapshots__/DataListLoading.spec.ts.snap, packages/vue-dot/src/elements/DataList/tests/__snapshots__/DataList.spec.ts.snap, packages/vue-dot/src/patterns/SubHeader/tests/__snapshots__/SubHeader.spec.ts.snap
Utilisation de la mixin `widthable` sur le composant `DataList`
Comme nous allons ajouter le composant `DataListGroup`, l'item ne porte plus la largeur, c'est directement la `DataList` que l'on dimensionne
Le guide de migration sera ajouté avec le composant `DataListGroup`
- Refactoring
=> ♻️ vue-dot: Use widthable mixin in DataList

CHANGELOG.md, packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue
Utilisation de la prop `modal-title` au lieu du slot dans le `SubHeader`
- Refactoring
=> ♻️ vue-dot: Use modal-title prop instead of slot in UploadWorkflow

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/vueDotLoader.js
Ajout des composants `DataListGroup` et `PageContainer` pour le tree-shaking de VueDot
=> ✨ vue-dash: Add DataListGroup & PageContainer in VueDotLoader

.circleci/config.yml, CHANGELOG.md
Utilisation de l'image `cimg/node` à la place de `circle/node`.
(Voir https://github.com/codecov/codecov-circleci-orb/issues/77#issuecomment-820897313)
- Maintenance
=> 🔧 Use cimg/node instead of circleci/node in CircleCI config

CHANGELOG.md, packages/vue-dot/src/patterns/LangBtn/LangBtn.vue
Correction de l'espacement lorsque la prop `hide-down-arrow` est présente :
=> 🐛 vue-dot: Fix spacing with hide-down-arrow prop in LangBtn

CHANGELOG.md, packages/vue-dot/src/elements/DataList/DataList.vue, packages/vue-dot/src/elements/DataList/DataListLoading/DataListLoading.vue, packages/vue-dot/src/elements/DataList/DataListLoading/tests/__snapshots__/DataListLoading.spec.ts.snap, packages/vue-dot/src/elements/DataList/tests/__snapshots__/DataList.spec.ts.snap
Correction d'un espace en trop sur le dernier item de la liste en mode chargement et simplification du correctif en mode normal.
=> 🐛 vue-dot: Fix spacing on last item in DataList

CHANGELOG.md, packages/vue-dot/src/elements/DownloadBtn/DownloadBtn.vue, packages/vue-dot/src/elements/DownloadBtn/tests/data/filePromise.ts
Correction du type de la prop `file-promise` et du téléchargement du fichier.
=> 🐛 vue-dot: Fix filePromise type & file download in DownloadBtn

CHANGELOG.md, packages/vue-dot/src/patterns/DatePicker/mixins/birthdate.ts, packages/vue-dot/src/patterns/DatePicker/mixins/dateLogic.ts
Correction du calcul de la date maximale en mode `birthdate`.
On utilisait `new Date().toISOString()` pour calculer la date maximale, sauf que cette méthode ne prend pas en compte le fuseau horaire (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString).
=> 🐛 vue-dot: Fix max date in birthdate mode in DatePicker

CHANGELOG.md, packages/vue-dot/src/elements/DownloadBtn/ContentHeadersEnum.ts, packages/vue-dot/src/elements/DownloadBtn/DownloadBtn.vue, packages/vue-dot/src/elements/DownloadBtn/tests/data/filePromise.ts
Correction du nom des headers dans le composant `DownloadBtn`.
Les headers sont case insensitive et sont transformés en minuscules par axios.
J'en ai profité pour extraire ces valeurs dans une enum `ContentHeadersEnum`.
=> 🐛 vue-dot: Fix headers name in DownloadBtn

packages/vue-dot/src/templates/ErrorPage/ErrorPage.vue, packages/vue-dot/src/templates/ErrorPage/tests/ErrorPage.spec.ts, packages/vue-dot/src/templates/ErrorPage/tests/__snapshots__/ErrorPage.spec.ts.snap
Utilisation du composant `PageContainer` dans le template `ErrorPage`.
J'ai aussi supprimé l'utilisation du composant `VLayout` car il est déprécié.
- Refactoring
=> ♻️ vue-dot: Use PageContainer in ErrorPage

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/generator/template/src/views/About.vue
Correction de la fermeture de la balise `VCard` dans le fichier `About.vue` dans le Starter Kit.
=> 🐛 vue-dash: Fix missing closing tag in About.vue

CHANGELOG.md, packages/vue-dot/src/elements/DataList/DataListItem/DataListItem.vue, packages/vue-dot/src/elements/DataList/DataListItem/config.ts, packages/vue-dot/src/elements/DataList/DataListItem/tests/__snapshots__/DataListItem.spec.ts.snap, packages/vue-dot/src/elements/DataList/tests/__snapshots__/DataList.spec.ts.snap
Suppression de l'utilisation du composant `VLayout` déprécié dans le composant `DataListItem`.
<details>
```vue
<template>
<div>
<DataList
:items="items"
:icons="icons"
/>
</div>
</template>
import { mdiAlert } from '@mdi/js';
@Component
items = [
{
key: 'Civility',
value: ''
},
{
key: 'Name',
value: 'Dupont',
icon: 'alert'
},
{
key: 'First name',
value: 'Paul'
}
];
icons = {
alert: mdiAlert
};
}
</script>
```
</details>
- Refactoring
=> ♻️ vue-dot: Remove deprecated VLayout usage in DataListItem

CHANGELOG.md, packages/vue-dot/src/patterns/UploadWorkflow/FileList/FileList.vue, packages/vue-dot/src/patterns/UploadWorkflow/FileList/config.ts, packages/vue-dot/src/patterns/UploadWorkflow/FileList/tests/__snapshots__/FileList.spec.ts.snap
Suppression de l'utilisation du composant `VLayout` déprécié dans le composant `FileList`.
<details>
```vue
<template>
<div>
v-model="files"
/>
</div>
</template>
@Component
files = [
{
id: 'rib',
title: 'RIB'
},
{
id: 'idCard',
title: 'Carte d\'identité recto / verso'
},
{
id: 'passport',
title: 'Passeport'
}
];
vuetifyOptions = {
fileList: {
showViewBtn: true
}
};
}
</script>
```
</details>
- Refactoring
=> ♻️ vue-dot: Remove deprecated VLayout usage in FileList

CHANGELOG.md, packages/vue-dot/src/patterns/SubHeader/SubHeader.vue, packages/vue-dot/src/patterns/SubHeader/config.ts, packages/vue-dot/src/patterns/SubHeader/tests/__snapshots__/SubHeader.spec.ts.snap
Suppression des options `layout` inutiles dans le composant `SubHeeader`.
<details>
```vue
<template>
<div>
<SubHeader :data-list-group-items="dataLists" />
</div>
</template>
@Component
dataLists = [
{
title: 'Informations patient',
items: [
{
key: 'Date de naissance',
value: '24/09/1970'
}
]
},
{
title: 'Médecin traitant',
items: [
{
key: 'Nom du praticien',
value: 'Gérard Leblanc'
}
]
},
{
title: 'Autres informations',
items: [
{
key: 'Dernière modification',
value: '04/06/2020'
}
]
}
];
}
</script>
```
</details>
- Refactoring
=> 🔥 vue-dot: Remove useless layout options in SubHeader

CHANGELOG.md, packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/form-builder/src/components/FormField/fields/PeriodField.vue
Suppression de l'utilisation du composant `VLayout` déprécié dans le composant `PeriodField`.
<details>
```vue
<template>
<div>
</div>
</template>
@Component
field = {
type: 'period',
value: {
from: null,
to: null
},
from: {
label: 'Début',
outlined: true
},
to: {
label: 'Fin',
outlined: true
}
}
};
}
</script>
```
</details>
- Refactoring
=> ♻️ form-builder: Remove deprecated VLayout usage in PeriodField

CHANGELOG.md, packages/vue-dot/src/helpers/deepCopy/index.ts, packages/vue-dot/src/helpers/deepCopy/tests/deepCopy.spec.ts
Correction de la copie des valeurs fausses dans la fonction `deepCopy`.
Fixes #1137 
=> 🐛 vue-dot: Fix deepCopy not copying falsy values

CHANGELOG.md, package.json, yarn.lock
Épinglage de la dépendance `sass` à la `v1.32.13`, voir https://github.com/vuetifyjs/vuetify/issues/13694.
- Maintenance
=> 📌 Pin dependency sass to 1.32.13

CHANGELOG.md, packages/vue-dot/src/helpers/registerComponents/index.ts, packages/vue-dot/src/mixins/widthable/index.ts
Utilisation de l'interface `IndexedObject` au lieu de types personnalisés
- Refactoring
=> 🎨 vue-dot: Use IndexObject instead of custom types

CHANGELOG.md, packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/form-builder/src/components/FormField/fields/ChoiceSliderField.vue
Refonte du composant `ChoiceSliderField`.
<details>
```vue
<template>
</template>
import { Field } from '../src/components/FormField/types';
@Component
items: [
{
text: 'Email',
value: 'email'
},
{
value: 'mail'
},
{
text: 'SMS',
value: 'sms'
}
],
value: null,
type: 'choiceSlider',
label: 'Moyen de contact',
outlined: true
}
};
}
</script>
```
</details>
- Refactoring
=> ♻️ form-builder: Refactor ChoiceSliderField

CHANGELOG.md, packages/form-builder/src/components/FormField/fields/ChoiceSliderField.vue
Correction des styles pour l'affichage des étiquettes dans `ChoiceSliderField`.
<details>
```vue
<template>
</template>
import { Field } from '../src/components/FormField/types';
@Component
items: [
{
text: 'Email',
value: 'email'
},
{
value: 'mail'
},
{
text: 'SMS',
value: 'sms'
}
],
value: null,
type: 'choiceSlider',
label: 'Moyen de contact',
outlined: true
}
};
}
</script>
```
</details>
=> 🐛 form-builder: Fix tick styles in ChoiceSliderField

CHANGELOG.md, packages/form-builder/src/components/FormField/fields/ChoiceSliderField.vue
Correction de la valeur à `null` par défaut dans le champ `ChoiceSliderField`.
<details>
```vue
<template>
</template>
@Component
export default class FormFieldSlider extends Vue {
items: [
{
text: '1 an',
value: 1
},
{
text: '2 ans',
value: 2
},
{
text: '3 ans',
value: 3
},
{
text: '4 ans',
value: 4
}
],
value: null,
type: 'choiceSlider',
label: 'Durée',
hideDetails: true
}
};
}
</script>
```
</details>
=> 🐛 form-builder: Fix null default value in ChoiceSliderField

CHANGELOG.md, packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/form-builder/src/components/FormField/fields/PeriodField.vue
Correction de la largeur des champs dans le composant `PeriodField`.
<details>
```vue
<template>
</template>
@Component
export default class FormFieldPeriod extends Vue {
type: 'period',
value: {
from: null,
to: null
},
from: {
label: 'Début',
outlined: true
},
to: {
label: 'Fin',
outlined: true
}
}
};
}
</script>
```
</details>
=> 🐛 form-builder: Fix input width in PeriodField

CHANGELOG.md, packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/form-builder/src/components/FormField/fields/ChoiceButtonField.vue, packages/form-builder/src/components/FormField/fields/tests/__snapshots__/ChoiceField.spec.ts.snap
Correction de l'espacement interne dans le composant `ChoiceButtonField`.
<details>
```vue
<template>
</template>
@Component
export default class FormFieldSelectButton extends Vue {
items: [
{
text: 'Email',
value: 'email'
},
{
value: 'mail'
},
{
text: 'SMS',
value: 'sms'
}
],
value: null,
type: 'choiceButton',
label: 'Moyen de contact',
outlined: true
}
};
}
</script>
```
</details>
=> 🐛 form-builder: Fix inner spacing in ChoiceButtonField

CHANGELOG.md, packages/vue-dot/src/styles/vuetify.scss
Correction de la position du curseur de redimensionnement dans les champs de formulaires.
Avant :
Après :
<details>
```vue
<template>
</template>
@Component
export default class FormFieldTextarea extends Vue {
type: 'textarea',
value: null,
label: 'Vos symptômes',
outlined: true
}
};
}
</script>
```
</details>
=> 🐛 vue-dot: Fix resize cursor position in textarea fields

CHANGELOG.md, packages/vue-dot/src/patterns/TableToolbar/config.ts, packages/vue-dot/src/patterns/TableToolbar/tests/__snapshots__/TableToolbar.spec.ts.snap
Correction de l'espacement du bouton *Ajouter* dans le composant `TableToolbar`.
<details>
```vue
<template>
<TableToolbar
v-model="search"
:nb-total="items.length"
/>
</template>
import { DataTableHeader } from 'vuetify';
@Component
export default class TableToolbarAddBtn extends Vue {
search: string | null = null;
}
</script>
```
</details>
=> 🐛 vue-dot: Fix add button spacing in TableToolbar

CHANGELOG.md, packages/vue-dot/src/patterns/TableToolbar/config.ts, packages/vue-dot/src/patterns/TableToolbar/tests/__snapshots__/TableToolbar.spec.ts.snap
Correction de l'espacement de l'icône du bouton *Ajouter* dans le composant `TableToolbar`.
=> 🐛 vue-dot: Fix add button icon spacing in TableToolbar

CHANGELOG.md, packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue, packages/vue-dot/src/elements/ExternalLinks/config.ts, packages/vue-dot/src/elements/ExternalLinks/tests/__snapshots__/ExternalLinks.spec.ts.snap
Correction de la valeur de la propriété `z-index` du bouton dans le composant `ExternalLinks`.
Le `z-index` était trop élevé par rapport à celui du composant `VAppBar`.
=> 🐛 vue-dot: Fix z-index value in ExternalLinks

CHANGELOG.md, packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue, packages/vue-dot/src/elements/ExternalLinks/config.ts, packages/vue-dot/src/elements/ExternalLinks/tests/__snapshots__/ExternalLinks.spec.ts.snap
Correction de l'arrondi lorsqu'il n'y a pas de données dans le composant `ExternalLinks`.
On utilise `VSheet` plutôt que `VCard` pour corriger le bug car c'est plus adapté à notre utilisation.
=> ♻️ vue-dot: Fix border radius when no data in ExternalLinks

CHANGELOG.md, packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue, packages/vue-dot/src/elements/FranceConnectBtn/tests/FranceConnectBtn.spec.ts
Suppression de la valeur par défaut de la prop `href` dans le composant `FranceConnectBtn`.
- Refactoring
=> ♻️ vue-dot: Remove href prop default value in FranceConnectBtn

CHANGELOG.md, packages/docs/package.json, packages/docs/src/content/guides/authentification-token.md, packages/docs/src/pages/_.vue
Ajout de l'option `--fail-on-error` à la commande `yarn generate`.
- Maintenance
=> 🔧 docs: Add --fail-on-error to generate command

CHANGELOG.md, packages/vue-dot/src/patterns/TableToolbar/TableToolbar.vue, packages/vue-dot/src/patterns/TableToolbar/config.ts, packages/vue-dot/src/patterns/TableToolbar/tests/__snapshots__/TableToolbar.spec.ts.snap
Correction de l'affichage du composant `TableToolbar` en mobile.
Fixes #1320 
<details>
```vue
<template>
<VDataTable
:headers="headers"
:items="items"
:search="search"
hide-default-footer
>
<template #top>
<TableToolbar
v-model="search"
:nb-total="items.length"
show-add-btn
/>
</template>
</VDataTable>
</template>
import { DataTableHeader } from 'vuetify';
@Component
search: string | null = null;
headers: DataTableHeader[] = [
{
text: 'Nom',
value: 'lastname'
},
{
text: 'Prénom',
value: 'firstname'
},
{
text: 'Email',
value: 'email'
}
];
items = [
{
firstname: 'Virginie',
lastname: 'Beauchesne',
email: 'virginie.beauchesne@example.com'
},
{
firstname: …
```
=> 🐛 vue-dot: Fix TableToolbar display on mobile

CHANGELOG.md, packages/cli-helpers/package.json
Correction de la dépendance `@types/figlet` manquante dans le package CLI Helpers.
=> 🐛 cli-helpers: Fix missing @types/figlet dependency

CHANGELOG.md, packages/docs/src/components/global/DocUsage.vue, packages/docs/src/content/examples/copy-btn/usage.vue, packages/docs/src/functions/toCamelCase.ts
Ajout d'une validation sur le format des propriétés dans le composant `DocUsage`.
Lors de l'utilisation de ce composant, les propriétés doivent être écrites en camelCase afin d'assurer le bon fonctionnement du composant.
Exemple de message d'erreur : `Wrong format for the "hide-tooltip" property in "options" object. Expected "hideTooltip".`
=> ✨ docs: Add property validation in DocUsage

CHANGELOG.md, packages/vue-dot/src/patterns/DatePicker/DatePicker.vue, packages/vue-dot/src/patterns/DatePicker/mixins/dateLogic.ts, packages/vue-dot/src/patterns/DatePicker/mixins/tests/dateLogic.spec.ts
Ajout de la gestion de l'appui sur touche la *Entrée* dans le composant `DatePicker`.
<details>
```vue
<template>
<DatePicker v-model="date" />
</template>
@Component
date = null;
}
</script>
```
</details>
=> ✨ vue-dot: Handle enter key press in DatePicker

CHANGELOG.md, packages/docs/src/content/composants/date-picker.md, packages/docs/src/content/examples/date-picker/events.vue, packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
Transmission des écouteurs d'événements dans le composant `DatePicker`.
<details>
```vue
<template>
<DatePicker
v-model="date"
clearable
@click:clear="date = null"
/>
</template>
@Component
date: string | null = null;
}
</script>
```
</details>
=> ✨ vue-dot: Pass down event listeners in DatePicker

CHANGELOG.md, packages/docs/src/content/composants/footer-bar.md, packages/docs/src/content/composants/footer-wrapper.md, packages/docs/src/content/examples/footer-bar/options.vue, packages/docs/src/content/examples/footer-bar/slots.vue, packages/docs/src/content/examples/footer-bar/usage.vue, packages/docs/src/data/api/footer-bar.ts, packages/docs/src/data/drawerItems.ts, packages/vue-dot/src/patterns/FooterBar/A11yComplianceEnum.ts, packages/vue-dot/src/patterns/FooterBar/FooterBar.vue, packages/vue-dot/src/patterns/FooterBar/config.ts, packages/vue-dot/src/patterns/FooterBar/index.ts, packages/vue-dot/src/patterns/FooterBar/locales.ts, packages/vue-dot/src/patterns/FooterBar/tests/FooterBar.spec.ts, packages/vue-dot/src/patterns/FooterBar/tests/__snapshots__/FooterBar.spec.ts.snap, packages/vue-dot/src/patterns/FooterWrapper/FooterBtn/FooterBtn.vue, packages/vue-dot/src/patterns/FooterWrapper/FooterWrapper.vue, packages/vue-dot/src/patterns/index.ts, packages/vue-dot/tests/integration/__snapshots__/libTheme.spec.ts.snap, packages/vue-dot/tests/integration/__snapshots__/plugin.spec.ts.snap, packages/vue-dot/tests/integration/__snapshots__/registerAllComponents.spec.ts.snap
Ajout du nouveau composant `FooterBar`.
Ce composant remplace les composants `FooterWrapper` et `FooterBtn` qui comportaient des problèmes d'accessibilité et d'utilisation.
<details>
```vue
<template>
<FooterBar version="1.2.0" />
</template>
@Component
</script>
```
</details>
=> ✨ vue-dot: Add FooterBar pattern

CHANGELOG.md, packages/docs/src/content/composants/dialog-box.md, packages/docs/src/content/examples/dialog-box/hide-actions.vue, packages/docs/src/content/examples/dialog-box/usage.vue, packages/docs/src/data/api/dialog-box.ts, packages/vue-dot/src/elements/DialogBox/DialogBox.vue, packages/vue-dot/src/patterns/FooterWrapper/FooterWrapper.vue
Ajout de la prop `hide-actions` dans le composant `DialogBox`.
<details>
```vue
<template>
<div>
<VBtn
>
</VBtn>
<DialogBox
hide-actions
>
<p class="mb-0">
Souhaitez-vous procéder à l’enregistrement ?
</p>
</DialogBox>
</div>
</template>
@Component
}
</script>
```
</details>
=> ✨ vue-dot: Add hide-actions prop in DialogBox

CHANGELOG.md, packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/HeaderBrandSection.vue
Ajout des attributs ARIA sur le séparateur vertical du composant `HeaderBrandSection`.
=> ♿️ vue-dot: Add ARIA attributes to svg element in HeaderBrandSection

CHANGELOG.md, packages/docs/src/components/global/DocMaterialLoader.vue, packages/docs/src/content/explorer/public/css/loader.css.md, packages/vue-cli-plugin-vue-dash/generator/template/public/index.html
Ajout des attributs ARIA sur l'icône de chargement dans le Starter Kit.
=> ♿️ vue-dash: Add ARIA attributes to loader in template

CHANGELOG.md, packages/docs/src/data/api/notification-bar.ts, packages/vue-dot/dev/main.ts, packages/vue-dot/src/patterns/NotificationBar/NotificationBar.vue, packages/vue-dot/src/patterns/NotificationBar/tests/__snapshots__/NotificationBar.spec.ts.snap
Correction de l'affichage du composant `NotificationBar` sur les écrans mobiles.
Avant :
Après :
<details>
```vue
<template>
<div>
<NotificationBar />
<VBtn
@click="notifyUser"
>
Envoyer une notification
</VBtn>
</div>
</template>
import { mapActions, mapState } from 'vuex';
@Component({
computed: mapState('notification', ['notification']),
methods: mapActions('notification', ['addNotification'])
})
notifyUser(): void {
this.addNotification({
type: 'error',
message: 'L’application est en maintenance, veuillez nous excuser pour la gêne occasionnée.'
});
}
}
</script>
```
</details>
- Ce changement nécessite une mise à jour …
=> 🐛 vue-dot: Fix NotificationBar display on mobile

CHANGELOG.md, packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
Correction de l'affichage du menu avec la prop `text-field-activator`.
Actuellement, avec la prop `text-field-activator`, seul la zone bleue de gauche affiche le menu.
Avec ce correctif, toute la zone bleue et la zone verte affichent maintenant le menu.
<details>
```vue
<template>
<DatePicker
outlined
text-field-activator
text-field-class="vd-form-input"
/>
</template>
@Component
</script>
```
</details>
=> 🐛 vue-dot: Fix menu display with text-field-activator in DatePicker

CHANGELOG.md, packages/form-builder/src/components/FormField/fields/RangeField.vue
Correction de l'affichage sur les écrans mobiles et suppression du `VForm` à l'intérieur du champ `RangeField`.
<details>
```vue
<template>
<div>
<FormField v-model="rangeField" />
</div>
</template>
import { Field } from '../src/components/FormField/types';
@Component
rangeField: Field = {
type: 'range',
min: 0,
max: 100,
value: null,
outlined: true
}
};
}
</script>
```
</details>
=> 🐛 form-builder: Fix RangeField display on mobile & remove VForm

CHANGELOG.md, packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/form-builder/src/components/FormField/fields/PeriodField.vue
Correction de l'affichage du composant `PeriodField` sur les écrans mobiles.
<details>
```vue
<template>
<div>
<FormField v-model="periodField" />
</div>
</template>
import { Field } from '../src/components/FormField/types';
@Component
periodField: Field = {
type: 'period',
value: {
from: null,
to: null
},
from: {
label: 'Début',
outlined: true
},
to: {
label: 'Fin',
outlined: true
}
}
};
}
</script>
```
</details>
=> 🐛 form-builder: Fix PeriodField display on mobile

CHANGELOG.md, packages/docs/src/components/global/DocHomePageHeader.vue, packages/docs/src/content/demarrer/introduction.md
Suppression du titre secondaire dans la page d'introduction de la documentation.
- Refactoring
=> 🔥 docs: Remove secondary title in introduction page

CHANGELOG.md, packages/docs/src/components/DocHeader.vue, packages/docs/src/pages/_.vue, packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationBar/HeaderNavigationBar.vue, packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationBar/config.ts, packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationBar/locales.ts
Refonte du bouton pour activer le menu sur les écrans mobiles dans le composant `HeaderNavigationBar`.
<details>
```vue
<template>
<HeaderBar :navigation-items="navigationItems" />
</template>
@Component
{
},
{
},
{
}
];
}
</script>
```
</details>
- Refactoring
=> ♻️ vue-dot: Refactor menu button on mobile in HeaderNavigationBar

CHANGELOG.md, packages/vue-dot/src/patterns/FooterBar/FooterBar.vue, packages/vue-dot/src/patterns/HeaderBar/HeaderMenuBtn/HeaderMenuBtn.vue
Ajout de l'attribut `inheritAttrs` manquant dans les composants `FooterBar` et `HeaderBarMenuBtn`.
=> 🐛 vue-dot: Fix missing inheritAttrs in FooterBar & HeaderBarMenuBtn

CHANGELOG.md, packages/vue-dot/src/mixins/getThemeIcon/index.ts
Correction d'une faute d'orthographe dans un commentaire de la mixin `getThemeIcon`.
- Maintenance
=> ✏️ vue-dot: Fix typo in getThemeIcon mixin comment

CHANGELOG.md, packages/docs/src/components/global/DocTabs.vue
Correction de la largeur des onglets verticaux dans la documentation.
=> 🐛 docs: Fix vertical tabs width in DocTabs

CHANGELOG.md, packages/form-builder/src/components/FormField/fields/RangeField.vue
Renommage de la propriété interne `isMobile` en `mobileVersion` dans le composant `RangeField`.
- Refactoring
=> ♻️ form-builder: Rename internal prop isMobile in RangeField

CHANGELOG.md, packages/docs/src/content/regles-validation/not-after-today.md, packages/docs/src/data/api/rules/not-after-today.ts, packages/vue-dot/src/rules/notAfterToday/locales.ts
Correction du message d'erreur par défaut de la règle de validation `notAfterToday`.
<details>
```vue
<template>
<DatePicker
v-model="date"
:rules="rules"
/>
</template>
import { notAfterToday } from '../src/rules/notAfterToday';
@Component
date: string | null = null;
rules = [
notAfterToday
];
}
</script>
```
</details>
=> 🐛 vue-dot: Fix notAfterToday rule default error message

CHANGELOG.md, packages/docs/src/components/global/DocApiTable.vue
Suppression de la couleur de fond au survol des lignes dans le composant `DocApiTable`.
- Refactoring
- Maintenance
=> ♻️ docs: Remove background color on row hover in DocApiTable

CHANGELOG.md, packages/docs/src/content/demarrer/contribuer.md, packages/docs/src/content/explorer/_browserslistrc.md, packages/docs/src/content/explorer/public/robots.txt.md, packages/docs/src/content/guides/authentification-token.md, packages/docs/src/content/guides/nouvelle-page.md
Utilisation de `text` à la place du langage `bash` pour représenter du texte dans la documentation.
=> 📝 docs: Use text instead of bash language

CHANGELOG.md, packages/docs/src/data/api/france-connect-btn.ts, packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
Renommage de la prop `icon-text` en `label` dans le composant `FranceConnectBtn`.
- Refactoring
=> ♻️ vue-dot: Rename icont-text prop to label in FranceConnectBtn

CHANGELOG.md, packages/vue-dot/src/styles/vuetify.scss
Correction de la hauteur de ligne dans les champs select de Vuetify avec notre police.
=> 🐛 vue-dot: Fix VSelect line-height in Vuetify

CHANGELOG.md, packages/vue-dot/src/modules/notification/types.d.ts
Ajout de l'interface `NotificationModule` au types du module `notification`.
=> ✨ vue-dot: Add NotificationModule interface in notification module

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/generator/template/src/global.d.ts, packages/vue-cli-plugin-vue-dash/generator/template/src/store/types.d.ts
Utilisation de l'interface `NotificationModule` dans le template du Starter Kit.
- Refactoring
=> ♻️ vue-dash: Use NotificationModule interface

CHANGELOG.md, packages/vue-dot/src/elements/FranceConnectBtn/FranceConnectBtn.vue
Ajout d'une transition sur la couleur de fond du composant `FranceConnectBtn`.
=> ✨ vue-dot: Add fill transition in FranceConnectBtn

CHANGELOG.md, packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/config.ts
Correction de l'affichage du menu avec la prop `mobile-version` sur les écrans desktop dans le composant `HeaderBar`.
=> 🐛 vue-dot: Fix menu display with mobile-version prop in HeaderBar

CHANGELOG.md, packages/docs/src/content/regles-validation/max-length.md, packages/docs/src/data/api/rules/max-length.ts, packages/vue-dot/src/rules/maxLength/index.ts, packages/vue-dot/src/rules/maxLength/tests/maxLength.spec.ts, packages/vue-dot/src/rules/minLength/tests/minLength.spec.ts
Ajout de l'option `ignoreSpaces` à la règle de validation `maxLength`.
=> ✨ vue-dot: Add ignoreSpaces option to maxLength rule

CHANGELOG.md, packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/form-builder/src/components/FormField/fields/ChoiceButtonField.vue
Correction du paragraphe `v-messages` affiché même sans texte informatif dans le composant `ChoiceButtonField`.
=> 🐛 form-builder: Fix v-messages display when no hint

CHANGELOG.md, packages/vue-dot/src/functions/isDateAfterValue/index.ts, packages/vue-dot/src/functions/validation/isDateAfter/index.ts, packages/vue-dot/src/functions/validation/isDateAfter/tests/isDateAfter.spec.ts, packages/vue-dot/src/rules/notAfterDate/index.ts, packages/vue-dot/src/rules/notAfterToday/index.ts
Renommage de la function `isDateAfterValue` en `isDateAfter`.
- Refactoring
=> ♻️ vue-dot: Rename isDateAfterValue function to isDateAfter

CHANGELOG.md, packages/vue-dot/src/functions/isDateBeforeValue/index.ts, packages/vue-dot/src/functions/validation/isDateBefore/index.ts, packages/vue-dot/src/functions/validation/isDateBefore/tests/isDateBefore.spec.ts, packages/vue-dot/src/rules/notBeforeDate/index.ts, packages/vue-dot/src/rules/notBeforeToday/index.ts
Renommage de la function `isDateBeforeValue` en `isDateBefore`.
- Refactoring
=> ♻️ vue-dot: Rename isDateBeforeValue function to isDateBefore

CHANGELOG.md, packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue
Correction de l'affichage des menus dans le composant `HeaderBar`.
<details>
```vue
<template>
<HeaderBar>
<UserMenuBtn full-name="Édith Cartier">
<VListItem
v-for="(item, index) in items"
:key="index"
>
<VListItemTitle>{{ item }}</VListItemTitle>
</VListItem>
</UserMenuBtn>
</HeaderBar>
</template>
@Component
export default class HeaderBarDefaultSlot extends Vue {
items = [
'Profil',
'Paramètres',
'Administration'
];
}
</script>
```
</details>
=> 🐛 vue-dot: Fix menus display in HeaderBar

CHANGELOG.md, packages/vue-dot/src/elements/DataList/DataListLoading/DataListLoading.vue, packages/vue-dot/src/elements/DataList/DataListLoading/tests/__snapshots__/DataListLoading.spec.ts.snap
Utilisation de l'attribut `aria-hidden` à la place des autres attributs ARIA dans le composant `DataListLoading`.
Voir https://adrianroselli.com/2020/11/more-accessible-skeletons.html
=> ♿️ vue-dot: Use aria-hidden in DataListLoading

CHANGELOG.md, packages/vue-dot/src/elements/DataList/DataList.vue, packages/vue-dot/src/elements/DataList/locales.ts, packages/vue-dot/src/elements/DataList/tests/__snapshots__/DataList.spec.ts.snap
Ajout de l'attribut `aria-label` en mode chargement dans le composant `DataList`.
Voir https://adrianroselli.com/2020/11/more-accessible-skeletons.html
=> ♿️ vue-dot: Add aria-label on loading mode in DataList

CHANGELOG.md, packages/docs/src/data/api/data-list.ts, packages/vue-dot/src/elements/DataList/DataList.vue, packages/vue-dot/src/elements/DataList/locales.ts
Suppression de la valeur par défaut inutile de la prop `placeholder` dans le composant `DataList`.
- Refactoring
=> 🔥 vue-dot: Remove unnecessary placeholder prop default value in DataList

CHANGELOG.md, packages/docs/src/content/examples/external-links/btn-text.vue, packages/docs/src/content/examples/external-links/usage.vue, packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue, packages/vue-dot/src/elements/ExternalLinks/tests/__snapshots__/ExternalLinks.spec.ts.snap, packages/vue-dot/src/elements/ExternalLinks/types.d.ts
Correction de l'affichage du menu dans le composant `ExternalLinks` :
En utilisant la prop `attach` sans argument, le contenu du menu est positionné au niveau du composant dans le DOM (contrairement à la fin de la page par défaut).
Cela permet de résoudre le problème de positionnement et améliore également l'accessibilité.
<details>
```vue
<template>
<ExternalLinks
:items="items"
position="top left"
/>
</template>
import { ExternalLink } from '@cnamts/vue-dot/src/elements/ExternalLinks/types';
@Component
items: ExternalLink[] = [
{
href: 'https://ameli.fr/',
text: 'Ameli'
},
{
href: 'https://espacepro.ameli.fr/',
text: 'Ameli Pro'
}
];
}
</script>
``` …
=> 🐛 vue-dot: Fix menu display in ExternalLinks

.circleci/config.yml, CHANGELOG.md, packages/vue-dot/src/elements/DialogBox/DialogBox.vue, packages/vue-dot/src/elements/DialogBox/locales.ts, packages/vue-dot/src/elements/DialogBox/tests/__snapshots__/DialogBox.spec.ts.snap
Ajout de l'attribut `aria-label` sur le bouton fermer dans le composant `DialogBox`.
=> ♿️ vue-dot: Add aria-label on close button in DialogBox

CHANGELOG.md, packages/docs/src/components/global/DocTabItem.vue
Ajout de la prop `eager` sur le composant `DocTabItem` dans la documentation pour le crawler Algolia.
- Refactoring
=> ♻️ docs: Add eager prop to DocTabItem

CHANGELOG.md, package.json, packages/vue-dot/package.json, packages/vue-dot/src/elements/DownloadBtn/DownloadBtn.vue, packages/vue-dot/tsconfig.json
Remplacement de la dépendance `content-disposition` par `content-disposition-header` car `content-disposition` qui est une refonte de `content-disposition` avec le support navigateur.
- Maintenance
=> ⬆️ vue-dot: Replace content-disposition with content-disposition-header

CHANGELOG.md, packages/docs/src/content/examples/footer-bar/usage.vue, packages/docs/src/data/api/footer-bar.ts, packages/vue-dot/src/patterns/FooterBar/FooterBar.vue, packages/vue-dot/src/patterns/FooterBar/locales.ts, packages/vue-dot/src/patterns/FooterBar/tests/__snapshots__/FooterBar.spec.ts.snap, yarn.lock
Ajout du lien *Plan du site* dans le composant `FooterBar`.
=> ✨ vue-dot: Add sitemap link in FooterBar

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/fixEnvFile.js, packages/vue-cli-plugin-vue-dash/generator/functions/fixPackageIndentation.js, packages/vue-cli-plugin-vue-dash/package.json, packages/vue-cli-plugin-vue-dash/utils.js
Utilisation de `consola` à la place de `@cnamts/cli-helpers`  dans Vue Dash.
- Refactoring
=> ♻️ vue-dash: Use consola instead of @cnamts/cli-helpers

CHANGELOG.md, packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/HeaderBrandSection.vue, packages/vue-dot/src/patterns/HeaderBar/HeaderBrandSection/locales.ts
Ajout d'un lien vers la page d'accueil sur le logo secondaire dans le composant `HeaderBar`.
<details>
```vue
<template>
<HeaderBar
service-title="Design System"
theme="ameli-pro"
/>
</template>
@Component
</script>
```
</details>
=> ✨ vue-dot: Add link to secondary logo in HeaderBar

CHANGELOG.md, packages/docs/src/components/global/DocAlert.vue
Correction de l'espacement du dernier paragraphe du composant DocAlert dans la documentation.
=> 🐛 docs: Fix last paragraph spacing in DocAlert

CHANGELOG.md, packages/docs/src/data/api/dialog-box.ts, packages/docs/src/data/examples/dialog-box/usage.vue, packages/vue-dot/src/elements/DialogBox/DialogBox.vue
Correction de l'affichage du bouton *Fermer* en mode persistant dans le composant `DialogBox`.
<details>
```vue
<template>
<div>
<VBtn
>
</VBtn>
<DialogBox
persistent
@confirm="dialog = false"
>
</DialogBox>
</div>
</template>
@Component
}
</script>
```
</details>
=> 🐛 vue-dot: Hide close button on persistent mode in DialogBox

CHANGELOG.md, packages/docs/src/components/global/DocA11yCriteria.vue
Correction du nom de la classe de l'élément principal du composant `DocA11yCriteria`.
=> 🐛 docs: Fix root element class name in DocA11yCriteria

CHANGELOG.md, packages/docs/src/data/examples/date-picker/usage.vue, packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
Correction de l'état désactivé du composant `DatePicker`.
Fixes #2333
<details>
```vue
<template>
<div>
<DatePicker
outlined
disabled
/>
</div>
</template>
@Component
</script>
```
</details>
=> 🐛 vue-dot: Fix disabled state in DatePicker

CHANGELOG.md, packages/vue-dot/src/templates/ErrorPage/ErrorPage.vue
Suppression police serif sur le code affiché dans le composant ErrorPAge
=> ✨ vue-dot: Remove serif font family on ErrorPage code

CHANGELOG.md, packages/vue-cli-plugin-vue-dash/generator/template/lint-staged.config.js
Correction du hook de qualité ne bloquant pas les warnings dans le Starter Kit.
=> 🐛 vue-dash: Fix lint hook not blocking warnings

CHANGELOG.md, packages/vue-dot/src/patterns/FooterBar/FooterBar.vue, packages/vue-dot/src/patterns/FooterBar/tests/__snapshots__/FooterBar.spec.ts.snap
Correction de l'espacement vertical dans le composant `FooterBar`.
<details>
```vue
<template>
<div class="d-flex flex-column justify-end h-100">
<FooterBar />
</div>
</template>
@Component
</script>
```
</details>
=> 🐛 vue-dot: Fix vertical spacing in FooterBar

CHANGELOG.md, packages/docs/src/components/global/DocTabs.vue
Suppression de l'utilisation du composant `ClientOnly` dans `DocTabs` dans la documentation.
- Refactoring
=> ♻️ docs: Remove ClientOnly component in DocTabs

packages/docs/src/data/api/footer-bar.ts, packages/docs/src/data/examples/footer-bar/default-slot.vue, packages/docs/src/data/examples/footer-bar/hide-social-media-links.vue, packages/docs/src/data/examples/footer-bar/options.vue, packages/docs/src/data/examples/footer-bar/slots.vue, packages/docs/src/data/examples/footer-bar/socialMediaLinks.vue, packages/docs/src/data/examples/footer-bar/usage.vue, packages/vue-dot/src/patterns/FooterBar/FooterBar.vue, packages/vue-dot/src/patterns/FooterBar/locales.ts, packages/vue-dot/src/patterns/FooterBar/tests/__snapshots__/FooterBar.spec.ts.snap
Ajouter un lien interne vers la page des cookies dans les 2 versions (simple et large) du footer
<details>
```vue
<template>
<FooterBar />
</template>
@Component
</script>
```
</details>
- Maintenance
=> Feat/#2483 Footer: lien cookie

packages/docs/src/content/composants/structure/footer-bar.md, packages/docs/src/data/api/footer-bar.ts, packages/docs/src/data/examples/footer-bar/externalsLinks.vue, packages/vue-dot/src/patterns/FooterBar/FooterBar.vue, packages/vue-dot/src/patterns/FooterBar/FooterLink/FooterLink.vue, packages/vue-dot/src/patterns/FooterBar/FooterLink/index.ts, packages/vue-dot/src/patterns/FooterBar/FooterLink/tests/FooterLink.spec.ts, packages/vue-dot/src/patterns/FooterBar/FooterLink/tests/__snapshots__/FooterLink.spec.ts.snap, packages/vue-dot/src/patterns/FooterBar/tests/FooterBar.spec.ts, packages/vue-dot/src/patterns/FooterBar/tests/__snapshots__/FooterBar.spec.ts.snap
Ajouter la possibilité de mettre des liens externes dans le footer
<details>
```vue
<template>
<FooterBar
sitemap-external-link="https://www.ameli.fr/assure/plan-du-site"
cgu-external-link="https://www.ameli.fr/assure/mentions-legales-cgu"
legal-notice-external-link="https://www.ameli.fr/assure/mentions-legales-cgu"
a11y-statement-external-link="https://www.ameli.fr/rhone/assure/accessibilite"
/>
</template>
@Component
</script>
```
</details>
=> Fix #2504 : Component > FooterBar : liens externes

packages/docs/src/vuetify.options.ts, packages/vue-dot/dev/vuetify.ts, packages/vue-dot/src/patterns/NotificationBar/NotificationBar.vue
Adapter le composant NotificationBar aux maquettes
- Maintenance
=> Fix #2502 : Component > NotificationBar : fix warning styles

packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationBar/HeaderNavigationBar.vue, packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationBar/tests/__snapshots__/HeaderNavigationBar.spec.ts.snap, packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/HeaderNavigationDrawer.vue, packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/tests/HeaderNavigationDrawer.spec.ts, packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/tests/__snapshots__/HeaderNavigationDrawer.spec.ts.snap
Bug : Lorsque j'utilise le composant HeaderBar et que j'accède à une page différente de celles qui sont listées dans navigation-items, la barre en dessous du bouton reste présente (active).
<details>
```vue
<template>
<HeaderBar :navigation-items="navigationItems">
<UserMenuBtn full-name="Édith Cartier">
<VListItem
v-for="(item, index) in items"
:key="index"
>
<VListItemTitle>
<router-link to="test">
{{ item }}
</router-link>
</VListItemTitle>
</VListItem>
</UserMenuBtn>
</HeaderBar>
</template>
@Component
export default class HeaderBarNavigationBar extends Vue {
items = [
'Profil'
];
{ …
```
=> 🐛 vue-dot: Fix tab active state in HeaderBar

packages/docs/src/content/composants/structure/footer-bar.md, packages/docs/src/data/api/footer-bar.ts, packages/docs/src/data/examples/footer-bar/dark.vue, packages/vue-dot/src/patterns/FooterBar/FooterBar.vue
Add dark grey mode on Footer
Fixes #2544
<details>
```vue
<template>
<FooterBar dark />
</template>
@Component
</script>
```
</details>
=> ✨ vue-dot: Add dark mode to FooterBar

packages/docs/src/content/composants/structure/sub-header.md, packages/docs/src/data/api/sub-header.ts, packages/docs/src/data/examples/sub-header/options.vue, packages/vue-dot/src/patterns/SubHeader/SubHeader.vue, packages/vue-dot/src/patterns/SubHeader/config.ts, packages/vue-dot/src/patterns/SubHeader/tests/__snapshots__/SubHeader.spec.ts.snap
Ajouter une option pour changer la couleur de fond du composant.
<details>
```vue
<template>
<SubHeader
title-text="Paul Dupont"
sub-title-text="1 69 08 75 125 456 75"
/>
</template>
@Component
export default class SubHeaderOptions extends Vue {
vuetifyOptions = {
background: {
color: 'primary'
}
};
}
</script>
```
</details>
=> ✨ vue-dot: Add vuetify-options to SubHeader

packages/vue-dot/src/styles/vuetify.scss
Fixes #2528 
<details>
```vue
<template>
<VTextField outlined />
</template>
@Component
</script>
```
</details>
=> 🐛 vue-dot: Fix VTextField border color

packages/docs/nuxt.config.js, packages/docs/src/assets/styles/variables.scss
Le fichier `variables.scss` de Vue Dot n'étais pas importé dans la documentation.
=> 🐛 docs: Fix missing custom Vuetify variables

packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/HeaderNavigationDrawer.vue, packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/tests/__snapshots__/HeaderNavigationDrawer.spec.ts.snap
Le composant HeaderNavigationDrawer est présent dans le DOM de la page en mobile lorsque le composant HeaderBar est utilisé sans éléments de navigation.
<details>
```vue
<template>
<HeaderBar :navigation-items="navigationItems" />
</template>
@Component
export default class HeaderBarNavigationBar extends Vue {
{
},
{
},
{
}
];
}
</script>
```
</details>
=> 🐛 vue-dot: Fix HeaderBar drawer rendered on mobile without items

packages/vue-dot/src/patterns/AccessibilityBanner/AccessibilityBanner.vue
Pouvoir faire disparaitre l'AccessibilityBanner à la perte de focus
<details>
```vue
<template>
<div class="d-flex flex-wrap align-center justify-center">
<AccessibilityBanner
v-if="active"
accessibility-route="#section/utilisation"
@accept="active = false; removeTabKey()"
/>
<VBtn
v-if="!active"
@click="active = true; info = true; checkTabKey()"
>
Réinitialiser
</VBtn>
<div v-if="info">
Cliquez sur la touche Tab
</div>
</div>
</template>
import AccessibilityBanner from '@cnamts/vue-dot/src/patterns/AccessibilityBanner';
@Component({
inheritAttrs: false,
components: {
AccessibilityBanner
}
})
export default class AccessibilityBannerUsage extends Vue {
active = true;
info = true; …
```
=> 🐛 vue-dot: Fix AccessibilityBanner remaining visible on focus out

packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/HeaderNavigationDrawer.vue, packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationDrawer/config.ts
Suppression de la propriété `navigationDrawer` dans les options Vuetify du composant `HeaderNavigationDrawer` pour éviter la redondance :
```ts
vuetifyOptions = {
navigationDrawer: {
navigationDrawer: {
hideOverlay: Boolean(this.$attrs.sticky && this.$attrs.mobileVersion)
}
}
};
```
<details>
```vue
<template>
<HeaderBar
/>
</template>
@Component
vuetifyOptions = {
navigationDrawer: {
hideOverlay: true
}
};
{
},
{
},
{
label: 'Mes …
```
=> ♻️ vue-dot: Bind vuetify-options directly in HeaderNavigationDrawer

packages/docs/src/data/examples/header-bar/usage.vue
Correction de l'exemple d'utilisation du composant `HeaderBar` avec les props `sticky` et `mobile-version`.
=> 🐛 docs: Fix HeaderBar sticky mobile usage example

packages/vue-dot/src/elements/LogoBrandSection/LogoBrandSection.vue
Actuellement la prop `theme` requiert une valeur alors que celle-ci est documentée comme ayant la valeur par défaut `default`.
<details>
```vue
<template>
<LogoBrandSection />
</template>
@Component
</script>
```
</details>
=> 🐛 vue-dot: Fix theme prop default value in LogoBrandSection

packages/docs/src/data/examples/logo-brand-section/usage.vue, packages/vue-dot/src/elements/LogoBrandSection/LogoBrandSection.vue
La bordure `outline` lors du focus n'est pas visible à cause du `overflow: hidden`
<details>
```vue
<template>
<LogoBrandSection theme="default" />
</template>
@Component
</script>
```
</details>
=> 🐛 vue-dot: Fix link outline in LogoBrandSection

packages/vue-dot/src/patterns/FooterBar/FooterBar.vue, packages/vue-dot/src/patterns/FooterBar/tests/__snapshots__/FooterBar.spec.ts.snap
Ajouter le rôle "contentinfo" sur le composant FooterBar #2740
<details>
```vue
<template>
<FooterBar />
</template>
@Component
</script>
```
</details>
- Maintenance
=> ♿️ vue-dot: Add contentinfo role on FooterBar

packages/vue-dot/src/patterns/HeaderBar/HeaderBar.vue, packages/vue-dot/src/patterns/HeaderBar/tests/__snapshots__/HeaderBar.spec.ts.snap
Ajouter le rôle "banner" sur le composant HeaderBar #2742
<details>
```vue
<template>
<HeaderBar :navigation-items="navigationItems" />
</template>
@Component
export default class HeaderBarNavigationBar extends Vue {
{
},
{
},
{
}
];
}
</script>
```
</details>
- Maintenance
=> ♿️ vue-dot: Add banner role to HeaderBar

packages/vue-dot/src/patterns/FooterBar/FooterBar.vue, packages/vue-dot/src/patterns/FooterBar/defaultSocialMediaLinks.ts
Suite de #2749. L'erreur est causée par un conflit de nom de fichier sur certains OS car la seule différence est sur la casse. Le mieux est renommer un des fichiers pour éviter tout problème.
Dans la v3 on lancera les tests sur plusieurs OS pour détecter ce genre de problèmes.
=> 🐛 vue-dot: Fix defaultSocialMediaLinks import in FooterBar

packages/vue-dot/src/styles/vuetify.scss
Il y a un margin négatif sur le composant `VRow`, on ne doit donc pas appliquer `max-width: 100%;` dessus.
=> 🐛 vue-dot: Fix VRow max-width

packages/vue-dot/src/elements/LogoBrandSection/LogoBrandSection.vue
Nuxt n'est pas une dépendance de Vue Dot, l'import générait donc une erreur dans les projets et le code est plus lisible de cette manière.
=> 🐛 vue-dot: Fix Nuxt import in LogoBrandSection

packages/docs/src/content/composants/boutons/back-btn.md, packages/docs/src/data/api/back-btn.ts, packages/docs/src/data/examples/back-btn/dark.vue, packages/docs/src/data/examples/back-btn/usage.vue, packages/vue-dot/src/elements/BackBtn/BackBtn.vue, packages/vue-dot/src/elements/BackBtn/tests/__snapshots__/BackBtn.spec.ts.snap
Ajouter la prop dark au composant BackBtn#2775](https://github.com/assurance-maladie-digital/design-system/issues/2775)
Improve display
<details>
```vue
<template>
<VSheet
class="pa-4"
>
<BackBtn
dark
/>
</VSheet>
<VSheet class="pa-4">
<BackBtn />
</VSheet>
</template>
@Component
</script>
```
</details>
- Maintenance
=> ✨ vue-dot: Add dark prop to BackBtn

packages/vue-dot/src/patterns/ContextualMenu/ContextualMenu.vue, packages/vue-dot/src/patterns/ContextualMenu/tests/__snapshots__/ContextualMenu.spec.ts.snap
Le composant ContextualMenu ne gère pas les longs titres
<details>
```vue
<template>
<VSheet
width="400"
elevation="1"
class="ma-4 py-4"
rounded
>
<ContextualMenu
v-model="current"
:items="items"
/>
<br />
<ContextualMenu
v-model="current"
:items="items2"
/>
</VSheet>
</template>
import { MenuItem } from '@cnamts/vue-dot/src/patterns/ContextualMenu/types';
@Component
export default class ContextualMenuUsage extends Vue {
current: string | null = null;
items: MenuItem[] = [
{
text: 'Lorem ipsum dolor.',
hash: '#doc-example-1'
},
{
text: 'Lorem ipsum dolor.',
hash: '#doc-example-2'
},
{
text: 'Lorem ipsum dolor.',
hash: '#doc-example-3'
}
];
items2: MenuItem[] = [
{
text: 'Lorem ipsum dolor sit amet, …
```
=> 🐛 vue-dot: Fix item overflow in ContextualMenu

packages/form-builder/src/components/FormField/FormField.vue
Je dois mettre en place un traitement pour gérer les sauts de ligne lors de l'affichage des données dans les questionnaire.
Je suggère de traiter le texte du titre comme du html.
<details>
```vue
<span
v-html="field.title"
/>
```
</details>
- Refactoring
=> ♻️ vue-dot: Use v-html for title in FormField

packages/vue-dot/src/patterns/RatingPicker/RatingPicker.vue
Il manquait la variable `hasAnswered` pour afficher le contenu secondaire.
=> 🐛 vue-dot Fix secondary content display in RatingPicker

packages/vue-dot/src/styles/vuetify.scss
Update : la regression vient de l'utilisation de v-overlay au sein d'un composant plus précisément. On affiche un overlay blanc au chargement. Sinon, il se basait sur le fait que cela soit transparent par défaut. Or, le changement de valeur par défaut, fait que l'overlay s'affiche même si le composant n'est pas affiché
<details>
```vue
<template>
<VBtn
color="error"
@click="overlay = !overlay"
>
Show Overlay
</VBtn>
<VOverlay :value="overlay" />
</template>
@Component
overlay = false;
}
</script>
```
</details>
=> 🐛 vue-dot: Fix VOverlay color when not active

packages/vue-dot/src/elements/LogoBrandSection/LogoBrandSection.vue
Show divider when secondaryLogo on LogoBrandSection.
<details>
```vue
<template>
<HeaderBar theme="compte-ameli" />
</template>
@Component
</script>
```
</details>
=> 🐛 vue-dot: Fix divider display in LogoBrandSection

packages/vue-dot/src/elements/DialogBox/DialogBox.vue
Evite les cassure de mots dans le titre des composant DialogBox
<details>
```vue
<template>
<DialogBox v-model="open"
title="Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eum sapientegfdsgsdfhgshs quod temporibus aliquam laboriosam.
">
Lorem ipsum dolor sit amet, consectetur adipisicing elit.
</DialogBox>
</template>
@Component({
components: {}
})
export default class FilePreviewUsage extends Vue {
log = (e: string): void => {
console.log(e);
};
open = true;
}
</script>
```
</details>
=> 🐛 vue-dot: Fix word wrap in DialogBox

packages/vue-dot/src/patterns/UploadWorkflow/UploadWorkflow.vue, packages/vue-dot/src/patterns/UploadWorkflow/tests/__snapshots__/UploadWorkflow.spec.ts.snap
https://github.com/assurance-maladie-digital/design-system/issues/3287
<details>
```vue
<template>
<div>
v-model="selectedFiles"
:file-list-items="fileListItems"
/>
</div>
</template>
import { FileListItem, SelectedFile } from '@cnamts/vue-dot/src/patterns/UploadWorkflow/types';
@Component
export default class UploadWorkflowUsage extends Vue {
selectedFiles: SelectedFile[] = [];
fileListItems: FileListItem[] = [
{
id: 'rib',
title: 'RIB'
},
{
id: 'idCard',
title: 'Carte d’identité recto / verso'
},
{
id: 'passport',
title: 'Passeport'
}
];
}
</script>
```
</details>
=> 🐛 vue-dot: Hide upload area when all files uploaded in UploadWorkFlow

packages/vue-dot/src/templates/ErrorPage/ErrorPage.vue
La props 'btnHref' est toujours overide par la valeur par défaut de la props 'btnRoute'. Cette PR a pour but de prendre en compte cette props quand elle est renseigné.
<details>
```vue
<template>
<ErrorPage
page-title="Error page"
code="418"
message="Something went wrong"
btn-text="href link"
btn-href="http://www.google.com"
/>
</template>
import ErrorPage from '../src/templates/ErrorPage/index';
@Component({
components: {
ErrorPage
}
})
</script>
```
</details>
=> 🐛 vue-dot: Fix btn-href prop not working in ErrorPage

packages/vue-dot/src/patterns/RangeField/RangeField.vue, packages/vue-dot/src/patterns/RangeField/tests/__snapshots__/RangeField.spec.ts.snap
Fix de l'issue https://github.com/assurance-maladie-digital/design-system/issues/3273
Fix des problème de typage, du bug en cas d'utilisation de caractère non numérique dans les champs et du problème de modification de champs min quand la valeure minimal est définie sur un chiffre suppérieur à 0.
<details>
```vue
<template>
<RangeField
v-model="rangeValue"
:min="20"
:max="100"
/>
</template>
@Component({
watch: {
rangeValue: {
handler: 'testUpdate',
deep: true
}
}
})
rangeValue = [50, 80];
testUpdate(e: unknown): void {
console.log(e);
}
}
</script>
```
</details>
=> 🐛 vue-dot: Fix field types in RangeField

packages/vue-dot/dev/App.vue, packages/vue-dot/src/styles/variables.scss, packages/vue-dot/src/styles/vuetify.scss
Utilisation de la font en taille 18px '1.125rem' pour les Alertes pour coller avec la charte figma
<details>
```vue
<template>
<AlertWrapper>
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores inventore, reiciendis obcaecati voluptates repellat ut cumque dolor dolore possimus alias mollitia ex iusto sit cupiditate delectus quis ipsum fuga quibusdam?
</AlertWrapper>
</template>
components: {
}
});
</script>
```
</details>
- Maintenance
=> 💄vue-dot: Fix VAlert font size

packages/docs/src/data/api/rating-picker.ts, packages/docs/src/data/examples/rating-picker/usage.vue, packages/vue-dot/src/patterns/RatingPicker/RatingPicker.vue
Ajout d'une props permettant de ne pas afficher l'alert après la validation du champs.
<details>
```vue
<template>
<vForm class="d-flex flex-column align-center">
<RatingPicker
v-model="rating"
label="Etes vous satifait de ce service ?"
type="emotion"
two-emotions
hide-alert
class="d-flex flex-column align-center"
>
<FormField
v-model="field"
class="mb-4 mt-8"
/>
<vTextarea
v-if="showTextArea"
outlined
name="user-feedback"
label="Pouvez-vous préciser ?"
counter="250"
class="w-100"
:disabled="sended"
/>
</RatingPicker>
<vBtn
v-if="!sended"
class="mt-4"
@click="validate"
>
Transmettre mon avis
</vBtn>
<AlertWrapper
v-if="sended"
type="success"
icon="$success"
outlined
class="mt-4"
>
Merci pour votre avis !
</AlertWrapper>
</vForm>
</template>
<script …
```
=> ✨ vue-dot: Add hide-alert prop in RatingPicker

packages/vue-dot/src/styles/variables.scss
La taille de la font des bouttons était plus petit que pour les bouttons de tailles medium.
Passage des bouton de taille large à 1rem pour être au même niveau que les bouttons de tailles medium
<details>
```vue
<template>
<v-row
align="center"
justify="space-around"
>
<v-btn
x-small
>Extra small button</v-btn>
<v-btn
small
>Small button</v-btn>
<v-btn
medium
>Regular button</v-btn>
<v-btn
large
>Large button</v-btn>
<v-btn
x-large
>X-large button</v-btn>
</v-row>
</template>
```
</details>
=> 🔧 vue-dot: Fix VBtn large font-size

packages/vue-dot/src/mixins/filterable/index.ts, packages/vue-dot/src/patterns/DatePicker/mixins/dateLogic.ts, packages/vue-dot/src/patterns/DatePicker/mixins/tests/dateLogic.spec.ts
Fixes #3233
<details>
```vue
<template>
<div>
<FiltersSideBar
v-model="filters"
@update:value="updateFilters"
>
<template #birthdate="{ on, attrs }">
<DatePicker
v-bind="attrs"
birthdate
outlined
date-format="DD/MM/YYYY"
hint="Format JJ/MM/AAAA"
date-format-return="YYYY MM DD"
v-on="on"
/>
</template>
<template #studiesdate="{ on, attrs }">
<DatePicker
v-bind="attrs"
outlined
date-format="DD/MM/YYYY"
hint="Format JJ/MM/AAAA"
date-format-return="YYYY MM DD"
v-on="on"
/>
</template>
</FiltersSideBar>
<DatePicker
outlined
date-format="DD/MM/YYYY"
hint="Format JJ/MM/AAAA"
date-format-return="YYYY MM DD"
@input="log($event)"
/>
</div>
</template>
@Component …
```
=> 🐛 vue-dot: Fix input event order in DatePicker

packages/vue-dot/src/elements/ExternalLinks/ExternalLinks.vue, packages/vue-dot/src/elements/ExternalLinks/config.ts
Permettre l'ajout de textes longs
<details>
```vue
<template>
<VCard
min-height="274px"
class="mx-auto overflow-hidden"
>
<VAppBar :color="appBarColor">
<VToolbarTitle>
ExternalLinks
</VToolbarTitle>
</VAppBar>
<ExternalLinks
:items="links"
btn-text="Afficher un texte super long super long super long mega long long"
nudge-top="80px"
position="top left"
/>
</VCard>
</template>
import { tokens } from '@cnamts/design-tokens';
import { ExternalLink } from '@cnamts/vue-dot/src/elements/ExternalLinks/types';
@Component
export default class ExternalLinksNudgeTop extends Vue {
appBarColor = tokens.colors.amBlue.lighten97;
links: ExternalLink[] = [
{
href: 'https://ameli.fr/',
text: 'Ameli'
},
{
href: …
```
=> 🐛 vue-dot: Fix text overflow in ExernalLinks

packages/vue-dot/src/patterns/PeriodField/PeriodField.vue
Un problème de réactivité empêchait l'erreur de s'afficher quand la date de fin est ultérieur à la date de début.
Lien vers la documentation sur laquelle je me suis basé pour cette PR :
https://v2.vuejs.org/v2/guide/reactivity#For-Objects
<details>
```vue
<template>
<div>
<PeriodField />
</div>
</template>
@Component
}
</script>
```
</details>
=> 🐛 vue-dot: Fix reactivity issue in PeriodField

packages/vue-dot/src/elements/UserMenuBtn/UserMenuBtn.vue
https://github.com/assurance-maladie-digital/design-system/issues/3391
<details>
```vue
<template>
<UserMenuBtn
additional-information="Information supplémentaire"
full-name="Virginie Beauchesne"
/>
</template>
@Component
export default class UploadWorkflowUsage extends Vue {
}
</script>
```
</details>
=> 🐛 vue-dot: Fix additional info color in UserMenuBtn

packages/docs/src/data/api/nir-field.ts, packages/vue-dot/src/patterns/NirField/NirField.vue
Fixes #3410
<details>
```vue
<template>
<NirField
v-model="nir"
required
outlined
/>
<VBtn @click="nir = ''">
reset
</VBtn>
{{ nir }}
</template>
@Component
nir = '';
}
</script>
```
</details>
=> 🐛 vue-dot: Use input event instead of change for v-model in NirField

packages/vue-dot/src/patterns/NirField/locales.ts, packages/vue-dot/src/patterns/NirField/tests/__snapshots__/NirField.spec.ts.snap
Fix d'une typo
<details>
```vue
<template>
<VApp>
<NirField />
</VApp>
</template>
import PageContainer from '../src/elements/PageContainer/PageContainer.vue';
components: {
PageContainer,
NirField
},
data() {
return {
};
}
});
</script>
```
</details>
=> vue-dot: Fix typo in error message

packages/vue-dot/src/patterns/NirField/NirField.vue, packages/vue-dot/src/patterns/NirField/tests/__snapshots__/NirField.spec.ts.snap
Fix tooltip position on NireField
<details>
```vue
<template>
<NirField outlined tooltip="jjh" />
</template>
@Component
</script>
```
</details>
=> 🐛 vue-dot: Fix tooltip position in NirField

packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationBar/config.ts, packages/vue-dot/src/patterns/HeaderBar/HeaderNavigationBar/tests/__snapshots__/HeaderNavigationBar.spec.ts.snap
Suppression de l'utilisationde la propriété 'dense' qui n'existe pas sur le composant VSheet
<details>
```vue
<template>
<HeaderBar :navigation-items="navigationItems" />
</template>
@Component
export default class HeaderBarNavigationBar extends Vue {
{
},
{
},
{
}
];
}
</script>
```
</details>
=> vue-dot: Remove unused dense property from HeaderNavigationBar config

packages/docs/src/data/api/error-page.ts, packages/vue-dot/src/templates/ErrorPage/ErrorPage.vue, packages/vue-dot/src/templates/ErrorPage/locales.ts, packages/vue-dot/src/templates/ErrorPage/tests/__snapshots__/ErrorPage.spec.ts.snap, packages/vue-dot/src/templates/MaintenancePage/tests/__snapshots__/MaintenancePage.spec.ts.snap, packages/vue-dot/src/templates/NotFoundPage/tests/__snapshots__/NotFoundPage.spec.ts.snap
Rendre le code d'erreure visible pour les screens readers
<details>
```vue
<ErrorPage
code="500"
message="La page ne fonctionne pas correctement."
page-title="Erreur serveur"
codeErrorText="Error code : "
/>
```
</details>
=> ♿️vue-dot: make the error code visible for the screens readers

packages/synapse-bridge/vite.config.ts
Au build erreur qui survient lors de l'utilisation de Rollup pour empaqueter l'application. Rollup ne peut pas déterminer automatiquement le nom global pour le module externe "vuetify/lib/components/VForm/index.mjs"...
<details>
```vue
```
</details>
- Refactoring
- Maintenance
=> fix build warning

packages/vue-dot/src/patterns/UploadWorkflow/mixins/tests/uploadWorkflowCore.spec.ts, packages/vue-dot/src/patterns/UploadWorkflow/mixins/uploadWorkflowCore.ts
Quand un fichier etait en erreure, son status n'était pas réinitialisé lors de sa mis a jour.
<details>
```vue<template>
<div>
v-model="selectedFiles"
:file-list-items="fileListItems"
@change="valueUpdated"
@error="showError"
/>
<VSnackbar
v-model="snackbar"
:color="snackbarColor"
>
{{ snackbarText }}
<template #action="{ attrs }">
<VBtn
v-bind="attrs"
text
@click="snackbar = false"
>
Fermer
</VBtn>
</template>
</VSnackbar>
</div>
</template>
import { FileListItem, SelectedFile } from '@cnamts/vue-dot/src/patterns/UploadWorkflow/types';
import { ErrorEvent, ErrorCodesType } from '@cnamts/vue-dot/src/patterns/FileUpload/types';
@Component
export default …
```
=> vue-dot: fix UploadWorkflow state

.vscode/extensions.json
L'extension `Vue.vscode-typescript-vue-plugin` est [déprécié](https://www.reddit.com/r/vuejs/comments/1b66msi/vscode_message_the_typescript_vue_plugin_volar/) et n'est plus nécessaire. Cette PR la supprime de la liste des extensions reconnandé sur le bridge.
- Maintenance
=> ➖bridge: Remove deprecated vsc extensions

packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue, packages/synapse-bridge/src/patterns/DatePicker/tests/DatePicker.spec.ts
<details>
```vue
<template>
<h3 class="bg-red">Required date pre renseignee</h3>
<date-picker v-model="date" label="Date" hint="Date" :rules="validRules"/>
<h3 class="bg-red">Required date init a null</h3>
<date-picker v-model="date1" label="Date" hint="Date" :rules="validRules"/>
</template>
import DatePicker from "@/patterns/DatePicker/DatePicker.vue"
import { required } from "@/rules/required/index.ts";
import dayjs from 'dayjs';
export default {
emits:['change'],
components: {
DatePicker,
PageContainer
},
data() {
return {
date: dayjs().format('DD/MM/YYYY'),
date1: null,
validRules: [required],
}
},
};
</script>
```
</details>
- …
=> fix error DatePicker

packages/synapse-bridge/src/patterns/NirField/NirField.vue, packages/synapse-bridge/src/patterns/NirField/locales.ts
Description
Les caracteres autres que A et B sont possible sans erreur , et comme il est n'est pas possible de passer des rules custom c'est bloquant
Comment reproduire
Dans un NirField entrer : "1 23 44 7D 898 765"
Le champ se valide
Comportement attendu
Le champ devrait être en erreur
<details>
```vue
<template>
<div>
<NirField v-model="nirValue" @update:model-value='newValue'/>
{{ nirValue }}
<NirField v-model="nirValue2" @update:model-value='newValue' :nir-length='13'/>
{{ nirValue2 }}
</div>
</template>
const nirValue = ref('');
const nirValue2 = ref('');
nirValue.value = '12345678901234k';
nirValue2.value = '123456A222224';
}, 1000);
function newValue(value: …
```
=> fix nierfield for the Corsican departments

packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue
Selon la documentation de Vuetify, il faut utiliser error-messages pour personnaliser le message d'erreur, mais cela ne fonctionne pas. À la place, j'ai dû indiquer cette propriété 'textField': { 'errorMessages': '' }. (sans le tiret)
Solution proposee: Ajout d'une props customErrorMessages
<details>
```vue
<template>
<v-row>
<v-col cols="12" md="6">
<h3>Required</h3>
<date-picker
v-model="date"
label="Date"
:hint="defaultHint"
:rules="validRules"
:customErrorMessages="['Votre message d erreur personnalisé ici']"				/>
</v-col>
</v-row>
</template>
import DatePicker from "@/patterns/DatePicker/DatePicker.vue";
import { required } from "@/rules/required/index.ts"; …
```
=> add custom message on error

packages/vue-dot/src/patterns/NirField/NirField.vue
fix the issue when the user delete somme number in the first field when the second field is not empty
<details>
```vue
<template>
<NirField
v-model="value"
label="NIR"
placeholder="Enter your NIR"
/>
{{ value }}
</template>
name: 'ThePlayground',
components: {
NirField
},
data() {
return {
value: '',
value2: ''
};
},
mounted() {
this.value = '123456789012345';
}, 3000);
}
});
</script>
```
</details>
=> Improve handling of NirField values

packages/synapse-bridge/src/form-builder/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue, packages/synapse-bridge/src/patterns/PeriodField/PeriodField.vue, packages/synapse-bridge/src/patterns/PeriodField/tests/__snapshots__/PeriodField.spec.ts.snap
<details>
```vue
<template>
<h2>FormBuilder</h2>
<FormBuilder v-model="form" />
{{ form }}
<br/><br/><br/>
<h2>FormFieldList</h2>
<FormFieldList v-model="fields" />
{{ fields }}
<br/><br/><br/>
<h2>FormField</h2>
{{ field }}
</template>
import {defineComponent} from "vue";
import {
FormBuilder,
FormFieldList,
FormField
} from "@/form-builder";
import { Form } from '@/form-builder/FormBuilder/types';
import { Fields } from '@/form-builder/FormFieldList/types';
import { Field } from '@/form-builder/FormField/types';
components: {
FormBuilder,
FormFieldList,
FormField
},
data() {
return {
form: {
informations: {
title: 'Vos informations',
questions: {
nir: {
type: 'text',
value: null,
label: …
```
=> fix append icon color and width on periodField component

packages/synapse-bridge/src/mixins/filterable/index.ts, packages/synapse-bridge/src/patterns/FiltersInline/FiltersInline.vue, packages/synapse-bridge/src/patterns/FiltersInline/tests/FiltersInline.spec.ts
fix filter inline no firing event update:modelValue
<details>
```vue
<template>
{{ filters }}
<FiltersInline v-model="filters" @update:modelValue="console.log">
<template #name="{ attrs }">
<VTextField
v-bind="attrs"
label="Nom"
variant="outlined"
hide-details
/>
</template>
<template #folder="{ attrs }">
<p class="text-secondary mb-4">
Vous pouvez filtrer entre les dossiers de type
<b>Arrêt de Travail (AT)</b> et
<b>Maladie Professionnelle (MP)</b> ou <b>Autre</b>.
</p>
<VSelect
v-bind="attrs"
:items="folderTypes"
label="Type de dossier"
multiple
variant="outlined"
return-object
hide-details
/>
</template>
<template #checkbox="{ attrs }">
<v-radio-group v-bind="attrs">
<v-radio label="Option One" value="one" color="primary"></v-radio> …
```
=> fix filterable mixin and FiltersInline component

packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue, packages/synapse-bridge/src/patterns/PeriodField/PeriodField.vue
<details>
```vue
<template>
<v-row>
<v-col cols="12" md="6">
<PeriodField/>
Date:	{{ date }}
Date pre definie: {{ dateDefinie }}
<h3>Basique Outlined</h3>
<date-picker v-model="date1" label="Date" :hint="defaultHint" outlined clearable />
<h3>Basique with change event</h3>
<date-picker v-model="date" label="Date" :hint="defaultHint"  @change="handleDateChange"/>
<h3>Basique</h3>
<date-picker v-model="date" label="Date" :hint="defaultHint" clearable />
<h3>Clearable</h3>
<date-picker v-model="date" label="Date" :hint="defaultHint" clearable outlined append-icon/>
<date-picker v-model="date" label="Date" :hint="defaultHint" clearable />
<h3>Required</h3>
<date-picker v-model="date" label="Date" :hint="defaultHint" :rules="validRules"/>
<h3>Not After Today</h3>
<date-picker …
```
=> fix notchs and icons color on datePicker and PeriodField

packages/synapse-bridge/package.json, packages/synapse-bridge/src/constants/index.ts, packages/synapse-bridge/src/elements/DownloadBtn/DownloadBtn.vue, packages/synapse-bridge/src/elements/DownloadBtn/tests/DownloadBtn.spec.ts
<details>
```vue
```
</details>
- Refactoring
- Maintenance
=> export cookies enum and constant enum

packages/synapse-bridge/src/patterns/PasswordField/PasswordField.vue, packages/synapse-bridge/src/patterns/PasswordField/config.ts, packages/synapse-bridge/src/styles/settings.scss
Fix password display
```vue
<template>
<v-col cols="3">
<PasswordField v-model="password"></PasswordField>
<PasswordField v-model="password" outlined></PasswordField>
<PhoneField />
</v-col>
</template>
import PasswordField from "@/patterns/PasswordField/PasswordField.vue"
import PhoneField from "@/patterns/PhoneField/PhoneField.vue"
components: {
PasswordField,
PhoneField
},
data() {
return {
password: null as string | null
}
},
})
</script>
```
=> fix display password

packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/vue-dot/src/patterns/DatePicker/DatePicker.vue, packages/vue-dot/src/patterns/DatePicker/tests/__snapshots__/DatePicker.spec.ts.snap
Add hint in messages (accessibility)
<details>
```vue
<template>
<div>
<DatePicker
v-model="date"
date-format="DD-MM-YYYY"
hint="Format JJ-MM-AAAA"
date-format-return="DD/MM/YYYY"
outlined
/>
<p
v-if="date"
class="mt-4 mb-0"
>
Date saisie : {{ date }}
</p>
</div>
</template>
@Component
export default class DatePickerFormat extends Vue {
date: string | null = null;
}
</script>
```
</details>
=> datePicker : add persistent hint for accessibility

packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue, packages/synapse-bridge/src/rules/notAfterToday/index.ts, packages/synapse-bridge/src/rules/notBeforeToday/index.ts
Les règles autres que required ou isDateValid passées dans la prop rules deviennent des warning-rules et ne bloquent plus la validation.
Entrer dans la prop rules vos règles. Ces règles peuvent être l'une des règles mise à disposition par le DS ou une règle custom.
Si entrèes en même temps, la règle required fonctionnera normalement, les autres se transformant en warning-rules.
``` vue
import {DatePicker, notAfterToday, required, notBeforeToday} from '@/main'
import {SubmitEventPromise} from "vuetify";
import { ref } from 'vue'
const date = ref(undefined)
async function submitForm(event: SubmitEventPromise): Promise<void> {
const submitResult = await event
if (submitResult.valid) {
alert("valid")
}
}
</script>
<template>
<v-form
@submit.prevent="submitForm"
> …
```
=> blocking submit based on rules

packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue, packages/synapse-bridge/src/patterns/DatePicker/tests/DatePicker.spec.ts, packages/synapse-bridge/src/rules/notAfterToday/index.ts, packages/synapse-bridge/src/rules/notAfterToday/tests/notAfterToday.spec.ts, packages/synapse-bridge/src/rules/notBeforeToday/index.ts, packages/synapse-bridge/src/rules/notBeforeToday/tests/notBeforeToday.spec.ts
Si la date est invalide le message d'erreur s'affiche bien mais le submit n'est pas bloque
<code>
```vue
import {DatePicker, notAfterToday, required, notBeforeToday} from '@/main'
import {SubmitEventPromise} from "vuetify";
import { ref } from 'vue'
const date = ref(undefined)
async function submitForm(event: SubmitEventPromise): Promise<void> {
const submitResult = await event
if (submitResult.valid) {
alert("valid")
}
}
</script>
<template>
<v-form
@submit.prevent="submitForm"
>
<DatePicker v-model="date" :rules="[notAfterToday, required]" :warning-rules="[notBeforeToday]"  label="NotAfterToday"/>
<button type="submit">Rechercher</button>
</v-form>
</template>
```
</code>
=> improve validDate rule ans set it by default

packages/form-builder/src/components/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/form-builder/src/components/FormField/fields/tests/__snapshots__/ChoiceField.spec.ts.snap, packages/vue-dot/src/patterns/SelectBtnField/SelectBtnField.vue, packages/vue-dot/src/patterns/SelectBtnField/tests/__snapshots__/SelectBtnField.spec.ts.snap
<details>
```vue
<template>
<SelectBtnField
v-model="value"
:items="items"
label="Moyen de contact"
/>
</template>
import { SelectBtnItem } from '@cnamts/vue-dot/src/patterns/SelectBtnField/types';
@Component
export default class SelectBtnFieldUsage extends Vue {
value: string[] = [];
items: SelectBtnItem[] = [
{
text: 'Email',
value: 'email'
},
{
value: 'courrier'
},
{
text: 'SMS',
value: 'sms'
}
];
}
</script>
```
</details>
=> refactor: Improve focus handling in SelectBtnField component

packages/synapse-bridge/CHANGELOG.md, packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue, packages/synapse-bridge/src/patterns/DatePicker/tests/DatePicker.spec.ts
<details>
```vue
```
</details>
- Refactoring
- Maintenance
=> add noIcon props in datepicker

packages/docs/src/data/api/date-picker-bridge.ts, packages/docs/src/data/api/date-picker.ts, packages/docs/src/data/examples/date-picker/usage.vue, packages/vue-dot/src/patterns/DatePicker/DatePicker.vue
Ajout d'une prop permettant de masquer l'icone calendar en mode outlined
<details>
```vue
<template>
<div>
<DatePicker
v-model="birthdate"
label="Date de naissance"
birthdate
no-icon
/>
<p
v-if="birthdate"
class="mt-4 mb-0"
>
Date saisie : {{ birthdate }}
</p>
</div>
</template>
@Component
export default class DatePickerBirthdate extends Vue {
birthdate: string | null = null;
}
</script>
```
</details>
- Maintenance
=> DatePicker : add no-icon prop

packages/synapse-bridge/src/elements/DialogBox/DialogBox.vue, packages/synapse-bridge/src/elements/DialogBox/tests/DialogBox.spec.ts, packages/synapse-bridge/src/elements/DialogBox/tests/__snapshots__/DialogBox.spec.ts.snap
Permettre de gérer la tabulation quand les éléments focusables sont dynamiques
<details>
```vue
import DialogBox from '@/elements/DialogBox/DialogBox.vue'
import { onMounted, ref } from 'vue'
import { VBtn } from 'vuetify/lib/components/index.mjs'
const disabled = ref(true)
const dialog = ref(false)
onMounted(() => {
setInterval(() => {
disabled.value = !disabled.value
console.log('disabled', disabled.value)
}, 5000)
})
</script>
<template>
<div>
<VBtn @click="dialog = true">Open</VBtn>
<VBtn>toto</VBtn>
<VBtn>toto</VBtn>
<DialogBox v-model="dialog">
<button :disabled="disabled">random btn</button>
</DialogBox>
<VBtn>toto</VBtn>
<VBtn>toto</VBtn>
<VBtn>toto</VBtn>
<VBtn>toto</VBtn>
</div>
</template>
<style lang="scss" scoped></style>
```
</details>
- Nouvelle …
=> dialog box focus dynamic elements

packages/synapse-bridge/src/form-builder/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue, packages/synapse-bridge/src/patterns/DatePicker/tests/__snapshots__/DatePickerField.spec.ts.snap, packages/synapse-bridge/src/patterns/PeriodField/tests/__snapshots__/PeriodField.spec.ts.snap, pnpm-lock.yaml
fix du padding supérieur du date picker
<details>
```vue
import DatePicker from '@/patterns/DatePicker/DatePicker.vue';
const date = ref('11/11/2021');
</script>
<template>
<div>
<DatePicker v-model="date" />
</div>
</template>
<style lang="scss" scoped></style>
```
</details>
=> DatePicker fix hint padding

packages/synapse-bridge/src/patterns/NirField/NirField.vue, packages/synapse-bridge/src/patterns/NirField/tests/NirField.spec.ts
<details>
```vue
import NirField from '@/patterns/NirField/NirField.vue';
const nir = ref('1234567890123');
</script>
<template>
<div>
<NirField
v-model="nir"
:required="true"
/>
</div>
</template>
<style lang="scss" scoped></style>
```
</details>
=> retirer la validation de la clé en mode sinple

packages/vue-dot/src/elements/DialogBox/DialogBox.vue, packages/vue-dot/src/elements/DialogBox/tests/__snapshots__/DialogBox.spec.ts.snap
Add aria-labelledby on component 
<details>
```vue
<template>
<div>
<VBtn
>
</VBtn>
<DialogBox
:width="dialogWidth"
@confirm="dialog = false"
>
</DialogBox>
</div>
</template>
import { tokens } from '@cnamts/design-tokens';
@Component
export default class DialogBoxWidth extends Vue {
dialogWidth = tokens.dialogWidth.dialogSmall;
}
</script>
```
</details>
=> DialogBox: fix aria

packages/vue-dot/src/patterns/SelectBtnField/SelectBtnField.vue
fix selectBtnField padding
<details>
```vue
<template>
<RatingPicker
v-model="rating"
label="Êtes-vous satisfait de ce service ?"
type="emotion"
>
<FormField
v-model="field"
class="mb-4"
/>
<div class="d-flex">
<VSpacer />
<VBtn
right
>
Terminé
</VBtn>
</div>
</RatingPicker>
</template>
@Component
export default class RatingPickerEmotion extends Vue {
rating = -1;
title: 'Comment avez-vous connu ce service ?',
items: [
{
text: 'Via une recherche internet',
value: 'internet'
},
{
text: 'Via un professionnel de santé',
value: 'professional'
},
{
text: 'Via un ami',
value: 'friend' …
```
=> SelectBtnField: fix list padding

packages/synapse-bridge/CHANGELOG.md, packages/synapse-bridge/src/form-builder/FormBuilder/tests/__snapshots__/FormBuilder.spec.ts.snap, packages/synapse-bridge/src/form-builder/FormField/fields/tests/__snapshots__/ChoiceField.spec.ts.snap, packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue, packages/synapse-bridge/src/patterns/NirField/tests/NirField.spec.ts, packages/synapse-bridge/src/patterns/NotificationBar/NotificationBar.vue, packages/synapse-bridge/src/patterns/SelectBtnField/SelectBtnField.vue, packages/synapse-bridge/src/patterns/SelectBtnField/tests/__snapshots__/SelectBtnField.spec.ts.snap
Fix padding + inline display
<details>
```vue
<template>
<SelectBtnField
v-model="value1"
:items="items"
label="Moyen de contact"
/>
<br /><br />
<SelectBtnField
v-model="value2"
:items="items"
multiple
label="Moyen de contact"
/>
<br /><br />
<SelectBtnField
v-model="value3"
:items="items"
inline
label="Moyen de contact"
/>
<br /><br />
<SelectBtnField
v-model="value4"
:items="items"
label="Moyen de contact"
hint="Par défaut, le moyen de contact est l’email."
/>
<br /><br />
<SelectBtnField
v-model="value5"
:items="items"
v-model:error="error"
v-model:error-messages="errorMessages"
label="Moyen de contact"
/>
<VBtn
class="mt-3"
@click="resetExample"
>
Réinitialiser
</VBtn>
</template>
import { defineComponent } from …
```
=> selectBtnField: fix padding + inline display

packages/vue-dot/src/elements/DialogBox/DialogBox.vue
Add title in aria-labelledby
<details>
```vue
<template>
<div>
<VBtn
>
</VBtn>
<DialogBox
:width="dialogWidth"
@confirm="dialog = false"
>
</DialogBox>
</div>
</template>
import { tokens } from '@cnamts/design-tokens';
@Component
export default class DialogBoxWidth extends Vue {
dialogWidth = tokens.dialogWidth.dialogSmall;
}
</script>
```
</details>
- Refactoring
- Maintenance
- Ce changement nécessite une mise à jour de la …
=> DialogBox: fix aria title

packages/synapse-bridge/src/patterns/DatePicker/DatePicker.vue, packages/synapse-bridge/src/patterns/DatePicker/config.ts
<details>
```vue
import { notAfterDate, notBeforeDate, required } from '@/main';
import DatePicker from '@/patterns/DatePicker/DatePicker.vue';
import { reactive } from 'vue';
const piece = reactive({
dateRedaction: '',
dateReception: '',
});
const date = ref('')
</script>
<template>
<DatePicker
v-model="piece.dateRedaction"
label="Date de rédaction (optionnel)"
bg-color="white"
outlined
:rules="[
notAfterDate(piece.dateReception || ''),
]"
/>
<br>
<DatePicker
v-model="piece.dateReception"
label="Date de réception"
bg-color="white"
outlined
:rules="[
required,
notBeforeDate(piece.dateRedaction || ''),
]"
/>
<DatePicker
v-model="date"
label="Date "
outlined
:rules="[
required,
notBeforeDate(piece.dateRedaction || ''),
]"
/>
</template> …
```
=> Refactor DatePicker component to improve validation behavior

packages/synapse-bridge/src/patterns/NirField/nirValidations.ts, packages/synapse-bridge/src/patterns/NirField/tests/nirValidation.spec.ts
<details>
```vue
components: {
NirField,
},
data: ()=>({
value: null,
valid: false
}),
mounted() {
setTimeout(()=>{
}, 5000);
}
});
</script>
<template>
<h3>Valides</h3>
nir valide: 2 94 03 75 120 005  clef: 91
Corse: 2 94 03 2B 120 005 clef: 18
Martinique 1 85 07 972 120 005 clef: 45
NIR homme né en 1990 à Paris (75), en janvier, 12e naissance du mois : 190017501012097 <br>
NIR femme née en 1985 en Corse (2B), en février, 45e naissance du mois : 285022B045987 <br>
NIR homme né en 1975 dans un département d'outre-mer (Martinique, 972), en mars, 123e naissance du mois : 175039720123594 <br>
NIR femme née en 1967 à l'étranger, dans un pays avec code …
```
=> improve nirValidation

packages/design-tokens/src/boostrapColors.ts
En essayant de faire plaisir au SonarQube je me retrouve a devoir enlever une option
- Maintenance
=> Update boostrapColors.ts to use type import
